### ISSUE TITLE
Critical security fix firefox 58.0.1 not available

### ISSUE THREAD

**Issue by zfil** [linuxmint/linuxmint#1]
Firefox 58.0.1 is available since a while from upstream ubuntu repos but not in Mint.

It contains a critical security fix (https://www.mozilla.org/en-US/security/advisories/mfsa2018-05/).

I understand that you repackage firefox, but now it is 5 days since it has been updated upstream, so this really sucks.

**Comment by xenopeek** [comment]
Thanks for reporting your concern. I see Firefox was upgraded to 58.0.2 on Linux Mint within a few days after your report.
