### ISSUE TITLE
Ability to install snapd on Linux Mint 17.3

### ISSUE THREAD

**Issue by mauromol** [linuxmint/linuxmint#10]
When trying to install snapd on my Linux Mint 17,3, I get:

    sudo apt-get install snapd

    Following packages have unsatisfied dependencies:
    snapd: Depends: systemd (>= 204-5ubuntu20.20) but not to be installed

aptitude reveals that 204-5ubuntu20.15linuxmint1 version of systemd libraries is installed, which conflicts with the requirement >= 204-5ubuntu20.20.

I think snapd is an important component if 17.3 is going to be supported until April 2019. Even more important since this is an old version of Mint and may be needed to run recent software.

**Comment by xenopeek** [comment]
For support questions please use the forums. For this question there is an earlier topic found there: https://forums.linuxmint.com/viewtopic.php?t=238894

**Comment by mauromol** [comment]
Why do you consider this a support question? I already saw that forum topic, which simply states there is this problem.

**Comment by xenopeek** [comment]
Would have been helpful to include you already new the solution. Linux Mint 17.3 will continue to get security updates for the (short) remainder of its lifetime but no new releases are done. snapd can be installed on Linux Mint 18 and above.

**Comment by mauromol** [comment]
Thank you. However, please note the following:
- I understand the distinction between "new features" and "security updates", but packages like snapd are a very special case; they were designed to let people install new software even on older systems; for this reason, I would say that an exception to the "security-only updates" rule would be worth considering by the Mint team, especially because we're talking about something that IS officially supported by Canonical on the Ubuntu 14.04 base Mint 17 builds on
- also, if we want to stick to "security-only" update policy anyway, please note that systemd packages have received a security update for trusty, with version 204-5ubuntu20.26, which is not currently landing to Mint 17 because of the patched version it's using - see: http://changelogs.ubuntu.com/changelogs/pool/main/s/systemd/systemd_204-5ubuntu20.26/changelog

So, if you deliver something like a 204-5ubuntu20.26linuxmint1 patched version, it should also solve the dependency requirement of snapd. And probably it will then work "out-of-the-box".
