### ISSUE TITLE
Mint 19.1: timeshift not able to restore encrypted home folder correctly when restoring after a hard disk failure

### ISSUE THREAD

**Issue by menthenchocolat** [linuxmint/linuxmint#100]
When restoring your system to a blank partition (e.g. after drive failure or any replacing of your hard disk), timeshift does not create the necessary symbolic links in the users' $HOME-folders. Thus Linux Mint is unable to automount the users' encrypted home-folders.

When backing up an encrypted home-folder with timeshift, several symbolic links in the home-folder are not being backed up (because they reside in $HOME and not in /home/.ecryptfs/$USER). The links not being backed up (and thus not being restored) by timeshift are:

> .ecryptfs -> /home/.ecryptfs/$USER/.ecryptfs

and

> .Private -> /home/.ecryptfs/$USER/.Private

If those two links are missing, Linux Mint upon first start after restoration creates new generic contents from template in the user's home folder instead of automounting the encrypted contents.

I found this behaviour with Linux Mint 19.1
I could not figure out if this also applies to other Versions or even to Ubuntu, too. (From what I found on web forums I had the impression, that Ubuntu might have a different way of mounting encrypted home folders.)

I saw that Linux Mint has its own fork of timeshift. Please notify me if this bug report should go to the main branch of timeshift instead.

**Comment by xenopeek** [comment]
If this is something that still needs attention it would be better to report it to the Timeshift developer. By default Linux Mint uses Timeshift only for system snapshots, not for home directory backups.
