### ISSUE TITLE
High CPU usage due to wifi card

### ISSUE THREAD

**Issue by helioschechtman** [linuxmint/linuxmint#101]
I am running Mint 19.1 on a dual boot Dell Vostro 3558. I monitor the computer with Gkrellm and I noticed that there is a high CPU usage (as well as processes). Running "top" I was able to pinpoint it to Root.
After googleing a lot, I saw a similar complaint for another system, and the culprit was the wifi card. I disable the wifi card (the computer has a switch for that) and the CPU usage (and processes) became normal (very low).
![screenshot from 2019-01-18 12-00-06](https://user-images.githubusercontent.com/33531368/51392427-1b25b100-1b1c-11e9-82c2-8ec866a2f56d.png)

**Comment by Lumumba** [comment]
https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1759836?comments=all

https://askubuntu.com/questions/1028883/ubuntu-18-04-systemd-udevd-uses-high-cpu-conflict-with-wifi

might be those bugs

**Comment by xenopeek** [comment]
According to https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1759836/comments/112 that bug was fixed on Bionic so I'm closing it here.
