### ISSUE TITLE
LMDE3 gnome-screenshot

### ISSUE THREAD

**Issue by gatons** [linuxmint/linuxmint#102]
LMDE3 Cinnamon Gnome Screenshot tool not remember last saving directory. This is not gnome issue - in Ubuntu this error not detected. I see, that in Mint patched tool version included. This error some time ago i find out in Linux Mint Cinnamon version also.

**Comment by gatons** [comment]
One more issue - when create screenshot, sometimes shot created with selection overlay, sometimes - as normal picture.

**Comment by xenopeek** [comment]
This can't reproduced on package version 3.18.0+2linuxmint3; that does remember last saving directory. I assume it was fixed somewhere after you reported this but the issue wasn't updated (or it was also reported elsewhere and updated there). Sorry this took so long.
