### ISSUE TITLE
whatsapp-desktop not working and abandoned by its developer

### ISSUE THREAD

**Issue by alexmex90** [linuxmint/linuxmint#104]
The package whatsapp-desktop, hosted on the Linux Mint import repository (http://packages.linuxmint.com/pool/import/w/whatsapp-desktop/whatsapp-desktop_0.5.0-1_amd64.deb) was abandoned by its developer and is currently in a non-working state.

![image](https://user-images.githubusercontent.com/43529725/51958678-f8af6400-2448-11e9-89b8-fa3e48ea0928.png)

https://github.com/Enrico204/Whatsapp-Desktop

![image](https://user-images.githubusercontent.com/43529725/51958688-0f55bb00-2449-11e9-8189-8383ad5065dc.png)

The package refers to a very popular application, and it is featured on the main screen of the software manager, which may lead users to install it, only to find out that is not working, and may give Linux Mint a bad image.

**Comment by rbbernardino** [comment]
Hello there!
@alexmex90, there has been released a new version (0.6) a couple of days ago. It works just fine! Try it out.

**Comment by xenopeek** [comment]
Many other developers forked the project after the original developed halted development. Linux Mint uses one of those forks, not the abandoned project.
