### ISSUE TITLE
Broadcom BCM43142 driver

### ISSUE THREAD

**Issue by apinunt** [linuxmint/linuxmint#106]
The proprietary driver in Driver Manager must be installed to get bluetooth and WiFi to work properly.
After doing so, WiFi works but bluetooth does not, and dmesg shows a failure to find BCM.hcd in /lib/firmware/brcm. This problem has existed for some time now, and was resolved in the past by searching for and downloading a file named BCM43142A0-0a5c_216d.hcd, renaming it BCM.hcd and placing it in /lib/firmware/brcm. We first encountered this problem with Mint 17 and every upgrade since has required us to make a change in the root folder to resolve this issue. We do not like to have to make changes in root and would like to see this fixed, or a reasonable explanation of why not, and if it will not be fixed at least the addition of some test in Driver Manager telling of the necessity to make some change in root to get bluetooth to work and how to accomplish it safely and properly.
Verification can be done by installing the driver from Driver Manager, booting the computer, and looking at the output of dmesg which complains of being unable to find BCM.hcd.
Currently we are experiencing this problem after installing Mint 19.1 Mate 64bit version on a number of HP Notebooks.

**Comment by apinunt** [comment]
Is there somewhere else I should be referring this issue?

**Comment by xenopeek** [comment]
Closing this issue. I hope you found your way with it, perhaps with help from the [support forum](https://forums.linuxmint.com/viewforum.php?f=53). Assuming it was the broadcom-sta-dkms package that got installed for your device (see if the package is installed in Synaptic) I think the place to report an issue for Ubuntu 18.04 Bionic (the package base for Linux Mint 19.x) would have been: https://bugs.launchpad.net/ubuntu/+source/broadcom-sta
