### ISSUE TITLE
mint-meta-codecs demote Depends on adobe-flashplugin

### ISSUE THREAD

**Issue by glenpp** [linuxmint/linuxmint#108]
adobe-flashplugin is in the process of being phased out by Adobe and is barely used on the web today aside from a number of other concerns that have been raised (security, privacy etc.)

Currently in mint-meta-codecs 2018.06.08 it remains as Depends forcing it to be installed. Given it's status I believe it would be more appropriate if it was demoted to Suggests or at most Recommends so that it is possible to remove adobe-flashplugin.

**Comment by xenopeek** [comment]
Thanks for your suggestion. For more information about our suggestions workflow see the [FAQ](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html).

Adobe will [continue](https://theblog.adobe.com/adobe-flash-update/) to distribute and update Flash Player till end of 2020.
