### ISSUE TITLE
No Sound HDMI Output

### ISSUE THREAD

**Issue by pavelkomarov** [linuxmint/linuxmint#11]
```
 * Distribution - Mint 17.3
 * Intel HD Graphics 5500 with Intel Corporation Broadwell-U Integrated Graphics (rev 09) (prog-if 00 [VGA controller])
 * 64 bit
 ```

**Issue**
I have been using Linux Mint since 2014 across four different computers and have never in all this time been able to output sound over HDMI. There are numerous issues on the linux mint forums about it (https://forums.linuxmint.com/viewtopic.php?t=242328, for example), but none have ever provided a solution that has worked for me.

**Steps to reproduce**
Install Linux Mint, plug your computer in to a TV via HDMI, and try to play a video. The picture will appear just fine, but audio will continue to come from the laptop.

**Expected behaviour**
Both audio and video should be output to the TV.

**Other information**
I've heard whispers of this occurring with other distros, though a friend who uses Ubuntu claims he has not had this problem. If any of you know better than I which Mint subsystem should be responsible for this, tell me so I can migrate this issue to that repo instead.

**Comment by JosephMcc** [comment]
The version of Cinnamon you are using is quite old. I do this all the time on current Cinnamon, playing videos on my TV and it works fine.

**Comment by pavelkomarov** [comment]
No, this problem persists even with the most recent version of Cinnamon. My point is it was a problem all the way back in 2014, and it never got fixed! I've already posted this bug on the Cinnamon github, and they claim they aren't responsible.

**Comment by JosephMcc** [comment]
Did you go into Cinnamon's sound setting and make sure the audio is being output to the HDMI? I do have to do that on mine. But it works fine.

**Comment by pavelkomarov** [comment]
That did work, and for the last several months I've been doing that. Made me feel dumb. It would be nice if Mint could automatically route the sound to HDMI and then to speakers again when you plug and unplug. My guess is this is confusing to many new users.
