### ISSUE TITLE
Linux Mint Mate 19.1 VPN creation Button isn't choiceable

### ISSUE THREAD

**Issue by kudomk** [linuxmint/linuxmint#112]
Sorry for my bad Englih
I use a VPN connection to conect with my University
I usually make that connection with a file configuration my University give me, althought this connection can be set manually. In Linux Mint Mate 18.2 I could make it both. But this time, when I press over the button to CONFIGURE VPN, this button can't be clickable.
If I try another via... "Edit connections". That is imposiblle either.
I had a talk in IRC Linux Mint Help... but nobody was able to help me. 
This should work in the same way 18.2 and before version worked...

I hope you can take this bug in consideration. Thanks a lot

**Comment by xenopeek** [comment]
I hope you managed to solve this already. I can't reproduce it on Linux Mint 19.3 MATE. If you still help with thus I suggest to take help from the [support forum](https://forums.linuxmint.com/) by making a topic there.
