### ISSUE TITLE
grub2 ignores /etc/default/grub settings

### ISSUE THREAD

**Issue by oz42** [linuxmint/linuxmint#115]
Mint 19.1 x64:
grub-efi-amd64 ignores /etc/default/grub settings:```

```
GRUB_DEFAULT=2
# GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=3

``````
Timeout is still at 30 seconds. I have tried both update-grub (what's this?) and update-grub2

**Comment by JosephMcc** [comment]
This might be a silly question but you did run this as `sudo update-grub` correct?

**Comment by smurphos** [comment]
https://forums.linuxmint.com/viewtopic.php?f=46&t=287026

**Comment by oz42** [comment]
Thanks to smurphos, he pointed me to a workaround. The solution is not complicated, so I hope we will get a bug fixed version soon.

**Comment by xenopeek** [comment]
The issue so far as the change in grub is upstream at Ubuntu. See topic linked by smurphos. It doesn't look like that change is going to be reverted. If others have more information please add to the forum topic.
