### ISSUE TITLE
Cannot get LinuxMint's publich key for verifying ISO files

### ISSUE THREAD

**Issue by JordanMartinez** [linuxmint/linuxmint#116]
I recently downloaded a version of Linux Mint. While verifying the downloads using the instructions [from this page](https://linuxmint.com/verify.php), specifically the `Authenticity Check`, I came across a problem.

Requesting the key from the key server returned an error with this result
```
$ gpg --keyserver hkps://keyserver.ubuntu.com:443 --recv-key "27DE B156 44C6 B3CF 3BD7  D291 300F 846B A25B AE09"
gpg: requesting key A25BAE09 from hkps server keyserver.ubuntu.com
gpgkeys: HTTP fetch error 1: unsupported protocol
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: ?
gpg: keyserver communications error: g10err=127
gpg: keyserver receive failed: g10err=127
```

**Edit:** Turns out the problem was that I did not have `gnupg-curl` installed. See [this answer](https://unix.stackexchange.com/questions/113586/i-fail-to-fetch-gpg-keys-over-hkps-with-gpgkeys-http-fetch-error-1-unsupporte) for why.

Steps for resolving
1. `sudo apt-get install gnupg-curl`
2. `gpg --keyserver hkps://keyserver.ubuntu.com:443 --recv-key "27DE B156 44C6 B3CF 3BD7  D291 300F 846B A25B AE09"`

**Comment by clefebvre** [comment]
Thanks, fixed.

**Comment by JordanMartinez** [comment]
Thanks for the fast response!
