### ISSUE TITLE
new install, xfce, Settings is useless.

### ISSUE THREAD

**Issue by gfodale** [linuxmint/linuxmint#119]
After installing from scratch, the small size of the settings menu is illegible, fonts are microscopic.  As such, it's impossible to fix also.

**Comment by xenopeek** [comment]
I assume you had a high resolution for your display (aka HiDPI). Linux Mint 19.3 Xfce ships with Xfce 4.14 which has HiDPI support: https://www.linuxmint.com/rel_tricia_xfce_whatsnew.php
