### ISSUE TITLE
LMDE 3 release version not sourcing ~/.profile ~/.xprofile /etc/profile /etx/xprofile

### ISSUE THREAD

**Issue by orcus-de** [linuxmint/linuxmint#120]
LMDE 3 release version does not source

  ~/.profile
  ~/.xprofile
  /etc/profile
  /etx/xprofile

on x-session startup. This does result in various other side-effects too. (Using a console-session will source *profiles as part of bash being a login-shell as expected)

Expected: files should get read/evaluated on x-session startup.

steps to reproduce (using a fresh install or vm - fully updated):

add echo-output (just for the test) to the  according files    (choosing different labels according to actual files);  or observe expected env-variable being set there:

`echo "~/.profile" >>/tmp/profile.txt`

After login to the x-session there does not exist /tmp/profile.txt   (and env will not get setup as expected).

After using my suggested fix below and a reboot (is required to load lightdm after the adjustments) the *profile -files get sourced.

================================

As a temporary fix and for a test  (which should obviously not be shared/used in the long run this way :-) ) on could use at the moment:

1) to get a short description from the tool (not doing any modifications this way)
`. <(wget https://www.orcus.de/Entities/linux/lmde3-fix-profile.sh -O - ) VERINFO`

(markdown is seemingly fascinated by the output - even if a wrapped as "code" - sorry for that)

`
================================
general information
  ----------------------------------------------------------------------
 LMDE 3 (cindy) did switch the default DM from mdm to lightdm.
 With LMDE 2 (betsy) mdm did care about sourcing "*profiles".
 With LMDE 3 (cindy) lightdm is missing an according functionality with
 the default installation.
  ----------------------------------------------------------------------
 Thus defined export env-variales will not be usabele with this files:

	/etc/profile
	/etc/xprofile
	/home/<your-user-name-here>/.profile		(aka $HOME/.profile)
	/home/<your-user-name-here>/.xprofile	(aka $HOME/.xprofile)

 Accordingly it is not possible to setup (install- or) user-specific
 environment variables in a common/expected way for the x-session.
  ----------------------------------------------------------------------
 This workaround does
 - add missing/required files (lightdm-wrapper and a helper-file for
   error-/message-display)
 - adjust lightdm config to override a pre-compiled lightdm setting
   to honor/use the lightdm-wrapper.
 ----------------------------------------------------------------------
 Remark: lightdm does use precompiled config-values, where defaults
 differ between the debian- and ubuntu-based versions regarding usage
 of lightdm-wrapper!
	ubuntu/mint 19.x -version = active
	debian/LMDE3     -version = inactive

 Thus an according config-option has to be set explicitly with LMDE3,
 to activate the usage of an available lightdm-wrapper.
 ----------------------------------------------------------------------
 Before doing any modifications to the installation, the tool does test
 if 
  - you are using a matching version of LMDE 3
  - lightdm is used (a lightdm-session is running) at all
  - there are no other/previous versions of the required additional
    files present
  - the lightdm-wrapper setting is not configured

 If any of this tests wont match, the system will NOT get modified.
`
================================

2) and to run it actually:
` . <(wget https://www.orcus.de/Entities/linux/lmde3-fix-profile.sh -O - )`
================================
3) After a reboot the *profiles will get sourced (and add entries to /tmp/profile.txt (or whichever name has been used for debugging purpos) and variables should get exported as expected.

================================
4) Remarks:
In the essence the fix does add
/usr/sbin/lightdm-session  (the wrapper)
/usr/lib/lightdm/config-error-dialog.sh (the internal used helper)
I did grab both files  from a mint 19.0 cinnamon install

And does set/activate in /etc/lightdm/lightdm.conf
session-wrapper=lightdm-session

================================
5) I did nearly pull out my hair as new mint 19.1  (xfce for example) is missing /etc/lighdm/lightdm.conf initially entirely and after adjustment of lightdm-related options only expose a condensed file.

Which made it horrible to track down the issue at all. And the only other finding of the session-wrapper=lightdm-session   (the "lightdm-session" string of that) has been lightdm-binary itself.

Finally it turned out that the binaries of LMDE 3 and mint 19.x for lightdm differ in the
preset/compiled-in default-values for  session-wrapper=lightdm-session.

As I noticed the spreading dissease of going binary on all occasions - I fear that, the more applications get "optimized" in this way = going away from findable and used configs (like in the good/bad old days) it will almost be impossible to find such glitches in the future by a normal means.

cheers orcus

**Comment by xenopeek** [comment]
As commented on the LMDE 4 issue for the same, this is upstream: https://github.com/linuxmint/lmde-4-cinnamon-beta/issues/2#issuecomment-596081230. In any case, LMDE 3 has reached end of support so closing this here.
