### ISSUE TITLE
Please update fwupdmgr so as to fix problem with its old version (esp. since the following all fail: snap; flatpak; build from source)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/linuxmint#121]
There is a fairly serious bug with the version of `fwupdmgr` offered currently by Mint. That bug has been fixed in fwupdmgr. Please see [here](https://github.com/hughsie/fwupd/issues/1139) on all that. You will see in that bug report that the maintainer of fwupdmgr asked me to ask you to update your version of fwupdmgr. That is what I do here. Thanks.

**Comment by LinuxOnTheDesktop** [comment]
I could get neither the snap nor the flatpak versions of `fwupdmgr` to work.

That adds some urgency.

The problems with snap are documented in the the bug report I referenced (viz., [this one](https://github.com/hughsie/fwupd/issues/1139)).

**Comment by xenopeek** [comment]
This was fixed upstream https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1773307 and backported to Bionic, the package base for Mint 19.x.
