### ISSUE TITLE
Firefox 66.0.4 and 66.0.5: Fix for Armagadd-on 2.0

### ISSUE THREAD

**Issue by UltramarineBlue0** [linuxmint/linuxmint#128]
Mozilla released Firefox [66.0.4](https://www.mozilla.org/en-US/firefox/66.0.4/releasenotes/) on May 5 and [66.0.5](https://www.mozilla.org/en-US/firefox/66.0.5/releasenotes/) on May 7 to fix a severe bug, where all extensions were disabled due to the expiration of a signing certificate.

Firefox 66.0.4 has been released in the upstream Ubuntu 18.04 [10 hours ago](https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1827727/comments/107) and Ubuntu's team is currently testing [Firefox 66.0.5](https://launchpad.net/ubuntu/+source/firefox/66.0.5+build1-0ubuntu1).

Is there a public issue / bug tracker where users can track the status of the update, see if there has been any new development? (I'm thinking similar to Mozilla's Bugzilla or Canonical's Launchpad)

**Comment by xenopeek** [comment]
All issues are tracked on GitHub. For 3rd party software packaged by Linux Mint such as Firefox, there is no separate bug tracker from upstream.
