### ISSUE TITLE
Install localized applications with Mint

### ISSUE THREAD

**Issue by Kebap** [linuxmint/linuxmint#129]
Hi all, not sure where to report, please propose better places.

So I installed Mint 19.1 recently but did not choose English. Now I notice some programs (like Thunderbird, Rhythmbox, etc.) are still shown in English. I need to install additional packages to get localized menus there. Those packages exist, all right. But shouldn't they come with Mint, when I inform the Mint installer to install Mint in a different language to begin with?

At least some checkbox "add everything needed" would be nice, wouldn't it?

Guess you wanted to keep the impact as low as possible - only setting up the os-gui itself + might be some optimization to make the install "faster" + probably avoiding the requirement of being connected during install... On the other hand if people do not need all applications to be in some different language some opt-out (again the checkbox) would be sufficient.

I didn't look at the mint-documentation. Could be it's just mentioned there.

This issue can hold as a solving ground or link-hub on how to activate translations for most common preinstalled apps, so users don't have to go deep dive some years old 3rd party forums posts for solutions that may or may not work anymore.

**Comment by xenopeek** [comment]
This has been implemented in Linux Mint 19.3 though in a different way: the System Reports utility on Linux Mint 19.3 detects when there are not-installed language packs for installed programs for the user's language and recommends the user to install them. This isn't tied to the action of installing a program; it detects such for all installed programs after a user changes their language settings and re-logins. System Reports will show in the system tray (showing as a warning sign icon).

For example I switched my language to Dutch and shortly after logging in anew (to effect the language change) System Reports showed in the system tray and when clicked showed me recommendation to install Dutch (nl) language packs for installed programs such as Firefox and Thunderbird:

![system-reports-nl](https://user-images.githubusercontent.com/21159972/72204369-3ac59000-3477-11ea-85b4-369b99194457.png)
