### ISSUE TITLE
The version of the dock applet in the repositories does not work with Mint 18.2 and 18.3

### ISSUE THREAD

**Issue by robint99** [linuxmint/linuxmint#13]
I'm not sure if this is the right place to report this, but this seemed the most suitable.

The version of MATE in the Mint repositories is 1.18, and is Gtk3. The version of the dock applet is taken from the Ubuntu Universe repository and is V0.70, compiled for Gtk2. The mismatch in Gtk versions means that the applet does not work in Linux Mint. See [this](https://github.com/robint99/mate-dock-applet/issues/118) bug report on the dock applet github for more details.

To fix this, would it be possible for you to provide in the Mint repositories a version of the applet compiled against Gtk3? Note: the latest versions of the applet require Gtk3 V3.22 or above, and therefore the last version which works in Linux Mint is V0.80.

I am the author of the dock applet so please get in touch if you need any more information...

**Comment by Isakku** [comment]
This is indeed a problem and I hope they will update the repositories when they launch Mint 19.0. Having Mate with GTK 3 and having applets within the repositories compiled for GTK2 makes them unusable. I personally like robint99's mate dock applet and I have had the problem he describes here.

**Comment by xenopeek** [comment]
As a workaround the 0.79 version is available from Ubuntu 17.10 repository and works on Linux Mint 18.3 MATE. Users can download the needed file from here https://packages.ubuntu.com/artful/mate-dock-applet. After downloading the .deb file (amd64 for 64-bit Linux Mint installs; i386 for 32-bit) just double-click that file in your file manager to install it.

For upcoming Linux Mint 19 nothing special needs to be done and mate-dock-applet installed from the default repository works. I retested on Linux Mint 19 pre-beta (beta should be out today).
