### ISSUE TITLE
File Manager Gets Stuck in Panel

### ISSUE THREAD

**Issue by StealthStalker** [linuxmint/linuxmint#130]
I posted this at https://github.com/mate-desktop/mate-panel/issues/860 but nothign seems to be done about it.  

**Expected behaviour**
When File Manager is Minimized into the Panel it should be able to be Maximized from there.

**Actual behaviour**
When File Manager is Minimized into the Panel it cannot be Maximized from there after opening the Mate "Menu" at lease once. I constantly have to Right Click "Close" and start over.  This only happens when you Click on the Mate Menu at least once first.  Then go back and try to Maximize File Manager from Panel and it won't.

**Steps to reproduce the behaviour**
Open File Manager with something like a USB Flash Drive with files on it, then Minimize it. Open the Menu Once or more, then try to Maximize the File Manager from the Panel again, and it won't Maximize, it is now stuck.

**MATE general version**
Linux Mint Mate , 18.xx Series
All computers regardless of CPU and Graphics
64 bit
**Linux Distribution**
Mint Mate 18.0-18.1-18.2-18.3

I don't understand this site format either. This is a huge issue and I cannot believe that more folks don't shout out about it. I've tried this with multiple iso's all verified, on different computers, over years of time, really, why is there not more folks shouting about this? I've tried it on Intel, AMD, Laptops, Desktops, AIO's, really really really! I have seen a few folks talk about it but not as many as I would expect. Mostly on the Mint Forums, a few folks there have seen it, but not the exact way I am seeing it.

Thanks

**Comment by StealthStalker** [comment]
Nothing?

**Comment by xenopeek** [comment]
The upstream fix looks to be included in Linux Mint 19.3. After minimizing a window to the panel only the Unminimize action is enabled:

![Linux Mint 19 3 Screenshot](https://user-images.githubusercontent.com/21159972/71962782-83bce080-31fa-11ea-8a6c-6cdf0b52f3f0.png)

**Comment by StealthStalker** [comment]
When did you download your image because the issue still exists in my Mint Mate 19.3

Plug in a USB Flash Drive

Open it in File Manager, then Minimize it to the Panel

Open the Menu Once, Click on File Manager in the Panel to Maximize it and you will see it is stuck.  

Problem still exists for me.  Image downloaded on "Saturday, ‎December ‎21, ‎2019, ‏‎9:32:44 PM"

**Comment by xenopeek** [comment]
There's only one Linux Mint 19.3 MATE ISO so not relevant when you downloaded it.

I tried to follow your steps:
- Plug in USB flash drive
- Open it in Caja then minimize it to the panel
- Open the menu (I assume you mean Mint Menu), click on Caja in the panel and it maximizes

What does "you will see it is stuck" mean?

**Comment by StealthStalker** [comment]
> There's only one Linux Mint 19.3 MATE ISO so not relevant when you downloaded it.
Your telling me they never update that ISO?
> I tried to follow your steps:
> 
> * Plug in USB flash drive
> * Open it in Caja then minimize it to the panel
> * Open the menu (I assume you mean Mint Menu), click on Caja in the panel and it maximizes
Yes, Mint Menu
> What does "you will see it is stuck" mean?
It means, Caja is stuck at that point in the panel and won't Maximize by just clicking on it, or by using the Right Click Unminimize either.

**Comment by StealthStalker** [comment]
My only test recently is from a Live Linux USB Flash Drive made with Yumi, thought that should not matter.

**Comment by xenopeek** [comment]
The Linux Mint 19.3 MATE final release was made public on Dec 18: https://blog.linuxmint.com/?p=3833. The ISO file itself isn't updated; updates arrive on the system through Update Manager.

I'd suggest to try it from a single boot USB, with the ISO written using Etcher or `dd`.

Can you reproduce the issue on other computers, or say in a virtual machine like VirtualBox? I've tried two machines and a VM and can't reproduce it here with your steps.

**Comment by StealthStalker** [comment]
I don't know what happened but I just tried it using Etcher on an old Dell
Inspiron laptop and it worked fine.  Needless to say I am very happy and
want to thank you guys for making me aware of what was happening.
