### ISSUE TITLE
Frozen Video in Expo View

### ISSUE THREAD

**Issue by aroundi** [linuxmint/linuxmint#132]
When going to expo view, via hot corner, video in the other workspaces is frozen.

Edit:
Behavior includes all window updates. For example, I hot corner to Expo to view my opened Gmail on another workspace. New emails are not updated until I switch to Gmail the workspace.

**Comment by xenopeek** [comment]
This is specific to Cinnamon. There's an issue on the same reported for Cinnamon: https://github.com/linuxmint/cinnamon/issues/8655

**Comment by aroundi** [comment]
Hello,

Is there a fix for this issue (aside from downgrading)?

Thanks,

mark

**Comment by xenopeek** [comment]
I don't know; I'm just closing this issue as there's an issue reported for the same on Cinnamon and that is where it should go.

**Comment by aroundi** [comment]
Okay, Thanks
