### ISSUE TITLE
Unable to load Virtualbox's VM after a kernel-headers update : "kernel driver not installed (rc=-1908)"

### ISSUE THREAD

**Issue by Choupinounours** [linuxmint/linuxmint#137]
Hi everyone ;

First time for me reporting a bug, so please tell me if this is not the good place or procedure to report it ^^'

I regularly use Virtualbox for some specific software on windows (guest : Windows 8.1 ; host : linux mint 19.0 or 19.1) ; it worked really fine.

After a kernel update some days ago (changing from 4.15.0.51.53 to 4.15.0.52.54) : 

![Sélection_288](https://user-images.githubusercontent.com/52127067/59975499-9d793c00-95b8-11e9-9a17-999c39511d9b.jpg)

I got a error when launching the VM : 

![Sélection_287](https://user-images.githubusercontent.com/52127067/59975516-d74a4280-95b8-11e9-9811-22586cd3714e.jpg)

The command modeprobe vboxdrv returning this : 
<pre><font color="#8AE234"><b>raph@raph-AB350M-Gaming-3</b></font>:<font color="#729FCF"><b>~</b></font>$ sudo modprobe vboxdrv
[sudo] Mot de passe de raph :         
modprobe: FATAL: Module vboxdrv not found in directory /lib/modules/4.15.0-52-generic
</pre>

I took a look on internet, and the issue seems to be known : 

https://www.virtualbox.org/ticket/3037

I tried different options, following the advices of the forums : 
- Reinstall virtualbox
- Checked in my BIOS if anything changed, but everything is fine and the virtualisations settings nedded for VB are enabled
- Reinstall "virtualbox-dkms"
- Tried the command "sudo apt install --reinstall virtualbox-dkms && sudo apt install libelf-dev"
- Reboot and use the previous kernel with grub, but the problem were still here and as i am not used to manipulate the kernel (I even tried to uninstall the most recent one but... I think i feared to break something and stopped ^^')
- Update from Mint 19.0 to 19.1

...But none of them worked.

So, as far as I understand, virtualbox seems to use kernel modules, usually available ; but not for the last one. I understood the problem came from the kernel_headers.

Does anyone have informations about this issue ?

I don't need to rapidly solve this problem but i was curious ^^'

Btw i give you the return of "inxi -Fxxrzc0" : 

<pre><font color="#8AE234"><b>raph@raph-AB350M-Gaming-3</b></font>:<font color="#729FCF"><b>~</b></font>$ inxi -Fxxrzc0
System:    Host: raph-AB350M-Gaming-3 Kernel: 4.15.0-52-generic x86_64 bits: 64 compiler: gcc v: 7.3.0 
           Desktop: Cinnamon 4.0.10 wm: muffin dm: LightDM Distro: Linux Mint 19.1 Tessa base: Ubuntu 18.04 bionic 
Machine:   Type: Desktop System: Gigabyte product: AB350M-Gaming 3 v: N/A serial: &lt;filter&gt; 
           Mobo: Gigabyte model: AB350M-Gaming 3-CF v: x.x serial: &lt;filter&gt; UEFI: American Megatrends v: F23 date: 08/08/2018 
CPU:       Topology: Quad Core model: AMD Ryzen 5 2400G with Radeon Vega Graphics bits: 64 type: MT MCP arch: Zen 
           L2 cache: 2048 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 57493 
           Speed: 1571 MHz min/max: 1600/3600 MHz Core speeds (MHz): 1: 1596 2: 1596 3: 1419 4: 1419 5: 1456 6: 1427 7: 1505 
           8: 1447 
Graphics:  Device-1: AMD Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] vendor: Gigabyte driver: amdgpu 
           v: kernel bus ID: 06:00.0 chip ID: 1002:15dd 
           Display: x11 server: X.Org 1.19.6 driver: amdgpu,ati unloaded: fbdev,modesetting,radeon,vesa 
           resolution: 1280x1024~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: AMD RAVEN (DRM 3.23.0 4.15.0-52-generic LLVM 7.0.0) v: 4.5 Mesa 18.2.8 compat-v: 4.4 
           direct render: Yes 
Audio:     Device-1: Advanced Micro Devices [AMD/ATI] driver: snd_hda_intel v: kernel bus ID: 06:00.1 chip ID: 1002:15de 
           Device-2: Advanced Micro Devices [AMD] vendor: Gigabyte driver: snd_hda_intel v: kernel bus ID: 06:00.6 
           chip ID: 1022:15e3 
           Device-3: Logitech Webcam C170 type: USB driver: snd-usb-audio,uvcvideo bus ID: 1-5:2 chip ID: 046d:082b 
           Sound Server: ALSA v: k4.15.0-52-generic 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Gigabyte driver: r8169 v: 2.3LK-NAPI 
           port: e000 bus ID: 03:00.0 chip ID: 10ec:8168 
           IF: enp3s0 state: down mac: &lt;filter&gt; 
           Device-2: Realtek RTL8812AE 802.11ac PCIe Wireless Network Adapter vendor: D-Link System driver: rtl8821ae 
           v: kernel port: d000 bus ID: 04:00.0 chip ID: 10ec:8812 
           IF: wlp4s0 state: up mac: &lt;filter&gt; 
Drives:    Local Storage: total: 2.04 TiB used: 900.77 GiB (43.2%) 
           ID-1: /dev/sda vendor: Kingston model: SA400S37240G size: 223.57 GiB speed: 6.0 Gb/s serial: &lt;filter&gt; temp: 35 C 
           ID-2: /dev/sdb vendor: Seagate model: ST2000DM006-2DM164 size: 1.82 TiB speed: 6.0 Gb/s serial: &lt;filter&gt; temp: 38 C 
Partition: ID-1: / size: 91.17 GiB used: 9.29 GiB (10.2%) fs: ext4 dev: /dev/sda3 
           ID-2: /boot size: 923.0 MiB used: 220.2 MiB (23.9%) fs: ext4 dev: /dev/sda2 
           ID-3: /home size: 1.72 TiB used: 883.59 GiB (50.2%) fs: ext4 dev: /dev/sdb4 
           ID-4: /tmp size: 29.21 GiB used: 107.2 MiB (0.4%) fs: ext4 dev: /dev/sdb1 
           ID-5: /var size: 13.69 GiB used: 7.55 GiB (55.1%) fs: ext4 dev: /dev/sdb3 
           ID-6: swap-1 size: 29.80 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sdb2 
Sensors:   System Temperatures: cpu: 47.4 C mobo: N/A gpu: amdgpu temp: 0 C 
           Fan Speeds (RPM): N/A 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/additional-repositories.list 
           1: deb [trusted=yes] https://cinelerra-gg.org/download/pkgs/mint19 bionic main
           Active apt repos in: /etc/apt/sources.list.d/google-chrome.list 
           1: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http://mirror6.layerjet.com/linuxmint/packages tessa main upstream import backport
           2: deb http://ubuntu.mirrors.ovh.net/ubuntu bionic main restricted universe multiverse
           3: deb http://ubuntu.mirrors.ovh.net/ubuntu bionic-updates main restricted universe multiverse
           4: deb http://ubuntu.mirrors.ovh.net/ubuntu bionic-backports main restricted universe multiverse
           5: deb http://security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
           6: deb http://archive.canonical.com/ubuntu/ bionic partner
           Active apt repos in: /etc/apt/sources.list.d/skype-stable.list 
           1: deb [arch=amd64] https://repo.skype.com/deb stable main
           Active apt repos in: /etc/apt/sources.list.d/teamviewer.list 
           1: deb http://linux.teamviewer.com/deb stable main
Info:      Processes: 270 Uptime: 30m Memory: 14.69 GiB used: 4.15 GiB (28.2%) Init: systemd v: 237 runlevel: 5 Compilers: 
           gcc: N/A Shell: bash v: 4.4.19 running in: gnome-terminal inxi: 3.0.27</pre>

Have a nice day !

**Comment by xenopeek** [comment]
Considering age of this issue I hope you previously managed to find a solution or workaround. I don't know what could have been the problem but for help with [troubleshooting](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) it's better to use the [support forums](https://forums.linuxmint.com/viewforum.php?f=231) and only report it as an issue on this GitHub if the responsible component is one developed by Linux Mint.
