### ISSUE TITLE
dkms line 784 contains an error

### ISSUE THREAD

**Issue by TakenTakenTakenTaken** [linuxmint/linuxmint#142]
I am using Linux Mint MATE v19.

/usr/sbin/dkms line 784 is:
`read -a kernels_module < <(find_module "$lib_tree" "${4}")`
however the function / method / procedure / subroutine "find_module" invoked by this line is absent in Mint's version of /usr/sbin/dkms. It is present in [master dkms](https://github.com/dell/dkms/blob/master/dkms) as:
```
find_module()
{
    # tree = $1
    # module = $2
    find "$1" -name "$2$module_uncompressed_suffix" -o -name "$2$module_suffix" -type f
    return $?
}
```
but this seems to have been removed from Mint's version of dkms and not caught by system testing.

Therefore when using Update Manager to update dkms, the kernel, or VirtualBox, opening the details of the progress window shows me:

> DKMS: build completed.
>
> vboxdrv.ko
> Running module version sanity check.
> /usr/sbin/dkms: line 784: find_module: command not found
> modinfo: ERROR: missing module or filename.

![find_module not found](https://user-images.githubusercontent.com/53368631/61994690-1b9d9680-b0c1-11e9-8b6d-0f701e1ff166.png)

System details follow:
```
$ inxi -Fxz
System:    Host: pavilion Kernel: 4.15.0-54-generic x86_64
           bits: 64 gcc: 7.4.0
           Desktop: MATE 1.20.1 (Gtk 3.22.30-1ubuntu4)
           Distro: Linux Mint 19 Tara
Machine:   Device: desktop System: HP product: 510-p049a serial: N/A
           Mobo: HP model: 81B4 v: 01 serial: N/A
           UEFI: AMI v: F.04 date: 05/10/2016
CPU:       Dual core Intel Core i3-6100T (-MCP-) 
           arch: Skylake-S rev.3 cache: 3072 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 12768
           clock speeds: max: 3200 MHz 1: 800 MHz 2: 800 MHz
Graphics:  Card: Intel HD Graphics 530 bus-ID: 00:02.0
           Display Server: x11 (X.Org 1.19.6 )
           drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.00hz
           OpenGL: renderer: Mesa DRI Intel HD Graphics 530 (Skylake GT2)
           version: 4.5 Mesa 19.0.2 Direct Render: Yes
Audio:     Card Intel 100 Series/C230 Series Family HD Audio Controller
           driver: snd_hda_intel bus-ID: 00:1f.3
           Sound: Advanced Linux Sound Architecture v: k4.15.0-54-generic
Network:   Card-1: Realtek RTL8111/8168/8411 PCIE Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: e000 bus-ID: 01:00.0
           IF: enp1s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
           Card-2: Realtek RTL8723BE PCIe Wireless Network Adapter
           driver: rtl8723be port: d000 bus-ID: 02:00.0
           IF: wlp2s0 state: down mac: <filter>
Drives:    HDD Total Size: 1000.2GB (3.2% used)
           ID-1: /dev/sda model: TOSHIBA_DT01ACA1 size: 1000.2GB
Partition: ID-1: / size: 63G used: 12G (20%) fs: ext3 dev: /dev/sda7
           ID-2: swap-1 size: 17.18GB used: 0.00GB (0%)
           fs: swap dev: /dev/sda6
RAID:      Device-1: /dev/zdata - ONLINE components: online: gdata1 gdatax
           Info: raid: zfs mirror size: 199G available: 160G allocated: 38.7G
Sensors:   System Temperatures: cpu: 30.0C mobo: 27.8C
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 324 Uptime: 10:44 Memory: 2168.9/7838.9MB
           Init: systemd runlevel: 5 Gcc sys: 7.4.0
           Client: Shell (bash 4.4.201) inxi: 2.3.56 
```
DKMS contents follow:
[dkms.gz](https://github.com/linuxmint/linuxmint/files/3438167/dkms.gz)

**Comment by TakenTakenTakenTaken** [comment]
This may be upstream's responsibility as [this](https://github.com/gnab/rtl8812au/issues/154#issuecomment-511658198) indicates a **Ubuntu** user has also seen this `line 784: find_module: command not found` error.

**Comment by Flamefire** [comment]
I filed an upstream bug: https://bugs.launchpad.net/ubuntu/+source/dkms/+bug/1838245

**Comment by xenopeek** [comment]
That bug looks to have been solved for Bionic (LM19.x base) and won't impact Focal (LM20 base). Thanks both for reporting. Closing it here.
