### ISSUE TITLE
Mate: LIVE USB - Left and Right Desktop Panel Components missing with UEFI boot 

### ISSUE THREAD

**Issue by altimumdelta** [linuxmint/linuxmint#143]
System specs and OS Info: https://termbin.com/chdk

It's a secondary PC which I just got from someone temporairly, I have no prior experience with Linux distros on this hardware, or any other OS other than Win10 for a few weeks.

Can't open any programs or do anything, can't see the clock, network, it is possible to open terminal via right clicking, the icons appear the same, it does not look like a desktop size/scaling issue.

**Comment by xenopeek** [comment]
Hope you managed to solve the issue. For problems with installation or booting I suggest to first take help from the [support forums](https://forums.linuxmint.com/viewforum.php?f=46) with troubleshooting.
