### ISSUE TITLE
upgrade to Mesa 19.0.8-0ubuntu0~18.04.1 crashinh LM19.2

### ISSUE THREAD

**Issue by DaveC49** [linuxmint/linuxmint#145]
Hi I upgraded to Mint 19.2 yesterday from 19.1. The first update in the update manager was an update to the mesa 19.0.8-0ubuntu0~18.04.1 library.  When I tried to install it, it crashes Mint
System info:
RELEASE=19.2
CODENAME=tina
EDITION="Cinnamon"
DESCRIPTION="Linux Mint 19.2 Tina"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=https://www.linuxmint.com/rel_tina_cinnamon_whatsnew.php
RELEASE_NOTES_URL=https://www.linuxmint.com/rel_tina_cinnamon.php
USER_GUIDE_URL=https://www.linuxmint.com/documentation.php
GRUB_TITLE=Linux Mint 19.2 Cinnamon
4.15.0-58-generic
[syslog.1.tar.gz](https://github.com/linuxmint/linuxmint/files/3503810/syslog.1.tar.gz)
 Not sure if this an upstream problem or specifically Mint related. The only reference i could find to mesa 19.0.8-0ubuntu0~18.04.1 was http://ubuntuhandbook.org/index.php/2019/07/install-mesa-19-0-8-ubuntu-18-04-19-04/ and no mention of issues with crashing.

**Comment by xenopeek** [comment]
Version 19.0.8-0ubuntu0~18.04.1 of the mesa drivers was a regular update from the upstream package base: https://changelogs.ubuntu.com/changelogs/pool/main/m/mesa/mesa_19.0.8-0ubuntu0~18.04.1/changelog. Current version is 19.0.8-0ubuntu0~18.04.3.

Hope you managed to solve the issue. I suggest to first take help from the [support forums](https://forums.linuxmint.com/) with troubleshooting on such issues.
