### ISSUE TITLE
Optimus Intel Driver consumes all resources, fans do not stop

### ISSUE THREAD

**Issue by Excalibur8201** [linuxmint/linuxmint#146]
When using Optimus Nvidia mode, everything works fine. When selecting Intel, after rebooting in order to changes take effect, coolers fans won't stop working, cinnamon process consumes all processors and memory. It happens on Linux Mint 19, screenshots attached.
![Selección_113](https://user-images.githubusercontent.com/31777395/63137874-6159ca80-bfae-11e9-8334-a590dee007d6.png)
![Selección_114](https://user-images.githubusercontent.com/31777395/63137882-674fab80-bfae-11e9-9256-27c74873176e.png)
![Selección_116](https://user-images.githubusercontent.com/31777395/63137918-99f9a400-bfae-11e9-983c-1e5639ddbca6.png)

**Comment by xenopeek** [comment]
Considering age of this issue I hope you previously found a solution or workaround, or maybe upgraded to Linux Mint 20 and have improved drivers on that. If you're still having this issue I suggest to first take help with [troubleshooting](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) it from the [support forums](https://forums.linuxmint.com/viewforum.php?f=59).
