### ISSUE TITLE
Removing foreign packages breaks the system

### ISSUE THREAD

**Issue by jmssil** [linuxmint/linuxmint#147]
Hi,

After upgrading to 19.2 today I restarted and ran Update Manager. Under Update Manager I used the feature to find foreign packages and removed them. After a reboot the graphical interface did not run (got into run level 3).

How can this happen?

Thanks.

**Comment by xenopeek** [comment]
I hope you managed to solve this, perhaps with help of the [support forum](https://forums.linuxmint.com/index.php). It's hard to diagnose such issues after the fact.

Software Sources' Remove foreign packages maintenance actions shows which packages are installed on your system but not available from the repositories (such as when you installed something from a PPA and later removed the PPA). You can select from the list of detected packages which to remove. When in doubt—as when something in the list isn't a program you installed yourself previously—please do get input from the support forum as to whether it's something you need.
