### ISSUE TITLE
gtk text fields do not redraw background correctly

### ISSUE THREAD

**Issue by mithodin** [linuxmint/linuxmint#148]
Since a few months, all gtk text input fields behave weirdly in my linux mint install (mate edition, upgraded to 19.2 today). I can input text, but the background is not redrawn correctly, so it is pretty much impossible to ready anything.
This includes applications like atril, xed or mintupdate, all gtk as far as I can tell.
![atril](https://user-images.githubusercontent.com/3817786/63417796-4352f680-c402-11e9-8736-63b779947f1c.png)
![xed](https://user-images.githubusercontent.com/3817786/63417800-451cba00-c402-11e9-8e34-e25807ee4e8c.png)

**Comment by xenopeek** [comment]
I hope you managed to solve this already. If not I suggest you first get help with [troubleshooting](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) from the [support forum](https://forums.linuxmint.com/index.php). If you still need help, please add when posting there which program each screenshot is from.

**Comment by mithodin** [comment]
I have already posted on the linux mint forums, but there has been no response. https://forums.linuxmint.com/viewtopic.php?f=47&t=307377&p=1729211#p1729211
The problem persists still.
