### ISSUE TITLE
cannot change grub menu

### ISSUE THREAD

**Issue by SiKing** [linuxmint/linuxmint#150]
I just installed mint 19.2 on a new machine.
When I reboot, I always see 30sec countdown for the grub menu. I would like to hide the grub menu.

I have a second machine with LM 19.1, where the grub menu stays hidden.

```
$ grep -v "#" /etc/default/grub

GRUB_DEFAULT=0
GRUB_TIMEOUT=0
GRUB_HIDDEN_TIMEOUT=0
GRUB_HIDDEN_TIMEOUT_QUIET=true
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
GRUB_CMDLINE_LINUX=""
```

On the new 19.2 machine I have identical settings, and I executed `sudo update-grub`. I still see the grub menu.

**Comment by SiKing** [comment]
Just as a test I set `GRUB_TIMEOUT=11` and ran `sudo update-grub`, but I still get a 30 second countdown. Is `/etc/default/grub` even the correct file to change?

**Comment by SiKing** [comment]
After reading through the info page, I narrowed the config file to:
```
GRUB_DEFAULT=0
GRUB_TIMEOUT=0
GRUB_TIMEOUT_STYLE=hidden

GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
GRUB_CMDLINE_LINUX=""
```

This works es expected on my LM 18 and 19.1 machines. But not on LM19.2.

**Comment by xenopeek** [comment]
This looks to be the same issue as #115. Not being able to hide the grub menu happens for LVM or EFI installs. See the forum topic for more information: https://forums.linuxmint.com/viewtopic.php?f=46&t=287026. It's an upstream grub issue.
