### ISSUE TITLE
VPN interactive login on GUI (for OTP SMS)

### ISSUE THREAD

**Issue by KAMI911** [linuxmint/linuxmint#153]
Please provide a solution to do interactive login during VPN access.
I am currently using this command line to 
openvpn --config client.ovpn --auth-retry interact
and get OTP SMS during the login process. Could you implement the OTP SMS/interactive login support?

**Comment by xenopeek** [comment]
Thanks for making a suggestion to improve Linux Mint. It was logged as a feature request for future consideration. See the [workflow](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html#why-are-ideas-and-feature-requests-closed) for feature request as to why this is closed here.
