### ISSUE TITLE
Mint's version of Firefox 70 broke various Javascript on lots of sites when not in private browsing

### ISSUE THREAD

**Issue by hjaltman** [linuxmint/linuxmint#157]
I originally reported this issue [to Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1591163), but it turns out it's specific to Mint's version of Firefox 70 (it did not occur with the Firefox binary I downloaded directly from their site), so I'm reporting it here.  (Although hoping the discussion there may be helpful?)

Basically, the Javascript on lots of sites is now broken in various ways.  For whatever reason, this problem doesn't occur when in private browsing.

Examples include:
*. On Facebook, nothing loads except the top bar.
*. On Tweetdeck, the site gets stuck at the spinner.
*. (Old-style) Reddit largely works, but you can't vote, collapse or expand comments, or do various other things.

It's not clear what the distinction is between what things work and what things don't, since various other sites seem to work fine.  No idea to the cause.  Also, as mentioned, everything works fine in private browsing.

System/environment information:
*. Release Linux Mint 19.1 Tessa 64-bit
*. Kernel Linux 4.15.0-66-generic x86_64
*. MATE 1.20.1
Package version information:
*. firefox 70.0+linuxmint1+tina

Thank you!  Hoping this can be fixed quickly.

**Comment by smurphos** [comment]
I can't reproduce a problem with Facebook. My Firefox is vanilla (as it's not my usual browser) - maybe test with Extensions disabled? Or allow Extensions one by one in private browsing mode to see if particular extension is breaking things.

**Comment by haltman-at** [comment]
It doesn't seem to be a matter of extensions.  All my extensions are set to still be enabled in private browsing, so that can't be the difference.  I also tried disabling them all and the problem still occurred.

**Comment by hjaltman** [comment]
It doesn't seem to be a matter of extensions.  All my extensions are set to still be enabled in private browsing, so that can't be the difference.  I also tried disabling them all and the problem still occurred.

(Deleted and reposted comment since I initially posted it with the wrong account...)

**Comment by hjaltman** [comment]
Also worth noting that the issue doesn't seem to be related to enhanced tracking protection; turning that off does not seem to affect this problem.

**Comment by hjaltman** [comment]
So, uh, is there any information I can collect or anything that could be helpful here?  Because this is still very much occurring, and it's breaking a number of websites.

Would listing more websites where it's occurring -- or perhaps also ones where it's not occurring, because like I said some JS-based websites work fine -- be helpful?  Perhaps simpler, lighter-weight examples than Facebook that might allow for easier isolation of the problem?  (Well, I already mentioned old-style Reddit...)

Let me include some examples of sites that work or mostly work, actually.  Hacker News works fine, including collapsing and expanding comments (unlike on Reddit, where as mentioned this is broken).  Twitter (not via TweetDeck) mostly works, although I think (not sure) new tweets added while you're browsing won't load (but think about how much else JS it's using that is working).  GitHub works fine!

Also, Imgur is another site that doesn't work, in that the image won't load.  Again, I can go on with more examples and non-examples if you like.

I actually noticed the problem on a webpage generated by TypeDoc (just running on a web server on my own machine; the menu and checkboxes that determine what it should display did nothing), so that's probably a fairly small example.  Maybe if I have some time I can try to pare this down further and try to find a more minimal example, but this isn't really my area.

Hope all this is helpful!

**Comment by hjaltman** [comment]
Ugh, turns out that example is not so small/comprehensible after all, blech...

**Comment by hjaltman** [comment]
OK, since (old-style) Reddit is probably the simplest example I have, I decided to see if I could check that out by seeing what goes on in the console when I click a collapse comment button.

The toggle effect on the comments is invoked by the toggle buttons having an `onclick` attribute of `return togglecomment(this)`.  However, when I click on it, I get the error message
```
TypeError: togglecomment is not a function
```

I also get
```
TypeError: click_thing is not a function
```
when I click on anything.

So, it would seem the script that sets up these functions is not getting run for some reason?

**Comment by hjaltman** [comment]
Or, no, it's getting run, but something is going wrong.  It's generating error messages.  Let me just copypaste the initial few error messages (and warnings) here, with my commentary:

```
Client Error: "UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code." thrown at L373:0 in https://c.aaxads.com/aax.js?pub=AAX763KC6&hst=www.reddit.com&ver=1.2 Message: "UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code." 
Object { tag: "unknown" }
reddit-init.en-us.43lPG1EdYMs.js:6:1798
```
Just an ad thing, probably unrelated.
```
Not sending debug log; already sent 3 reddit-init.en-us.43lPG1EdYMs.js:6:872
```
No idea what this is.
```
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. aax.js:373
```
On expanding, this is more ad stuff.  (I can post the expansions of these errors if you want but I'm skipping it for now.)
```
Error running module reddit.js : TypeError: this.$el.find(...).validator is not a function reddit-init.en-us.43lPG1EdYMs.js:6:1798
```
What!  What happened here??
```
TypeError: r.sendError is not a functionreddit-init.en-us.43lPG1EdYMs.js:9:25565
```
What!  None of this happens in private mode!
```
Request to access cookie or storage on “<URL>” was blocked because it came from a tracker and content blocking is enabled. 12
```
Something similar happens in private mode.
```
Error sending debug logs to server: parsererror ; SyntaxError: "JSON.parse: unexpected end of data at line 1 column 1 of the JSON data"
    parseJSON https://www.redditstatic.com/reddit-init.en-us.43lPG1EdYMs.js:3
    ajaxConvert https://www.redditstatic.com/reddit-init.en-us.43lPG1EdYMs.js:1
    S https://www.redditstatic.com/reddit-init.en-us.43lPG1EdYMs.js:3
    t https://www.redditstatic.com/reddit-init.en-us.43lPG1EdYMs.js:3
```
More errors in that file.
```
A call to document.write() from an asynchronously-loaded external script was ignored.
```
This looks unrelated (ad-related).

Note that just about none of this happens in private mode!  Theres a slightly different content blocking warning, and that's it.

So, something's going wrong running the Reddit init script?  Which loads just fine but then...?  IDK what to make of this.

**Comment by hjaltman** [comment]
Btw, on trying this again, some of these messages happen in a different order; in particular, this time, the `r.sendError` problem happened before the `this.$el.find(...).validator` problem.

**Comment by hjaltman** [comment]
Also probably worth noting that on the first click, there's an error message
```
Client Error: "TypeError: togglecomment is not a function" thrown at L1:8 in https://old.reddit.com/r/AskHistorians/comments/dqcpzg/18th_century_calorie_intake_did_they_really_eat/ Message: "TypeError: togglecomment is not a function" 
Object { tag: "unknown" }
reddit-init.en-us.43lPG1EdYMs.js:6:1798
```
(and a similar for `click_thing`) before the usual `togglecomment` error message; subsequent clicks don't include this extra error.

Anyway I can't get Firefox's debugger working so this is about as far as I can get I think.  Hope it's helpful!

**Comment by hjaltman** [comment]
OK, I have no idea what the problem was but I just installed 70.0.1 (via the package manager) and it fixed it!  Thanks anyway, closing this.
