### ISSUE TITLE
Problems with at-spi-bus-launcher after update

### ISSUE THREAD

**Issue by ghost** [linuxmint/linuxmint#158]
### Description
`at-spi-bus-launcher` it's hung on closing session. After forcing process termination there's a delay before closing around 30 seconds. I've tried to disable `at-spi-bus-launcher` from `mate-session-properties` but that process keeps loading on next session. Forcing process termination before a click on session close button, system closes session quickly as it should, but it turns out that there's the same delay from login window to desktop on startup.
### Version
Tessa

**Comment by xenopeek** [comment]
Considering age of this issue I hope you previously found a solution or workaround, maybe from upgrading to a newer Linux Mint version. If you're still having this issue I suggest to take help with [troubleshooting](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) from the [support forums](https://forums.linuxmint.com/).
