### ISSUE TITLE
Ktouch doesn't load past setup

### ISSUE THREAD

**Issue by mortalsdemise13** [linuxmint/linuxmint#159]
when you install Ktouch on linux mint 19.+ then launch the application it has a setup screen, after putting in your name and selecting an option hitting the button that says "start training" does absolutely nothing whatsoever.

**Comment by xenopeek** [comment]
Launching ktouch from the terminal shows, among others, these messages:
```
QSqlDatabase: QSQLITE driver not loaded
QSqlDatabase: available drivers: 
"Driver not loaded Driver not loaded"
```
So it needs a SQL database backend. Looking at the ktouch package in Synaptic shows it will work with various database backends: libqt5sql5-sqlite | libqt5sql5-mysql | libqt5sql5-odbc | libqt5sql5-psql | libqt5sql5-tds  | libqt5sql5-ibase.

Suggest you install libqt5sql5-sqlite as the simplest backend and that should immediately let you start ktouch afterward. Check the recommends dependencies of libqt5sql5-sqlite in Synaptic if some other functionality is incomplete, there are more recommended optional packages besides the database backend. You can install libqt5sql5-sqlite from Synaptic or from terminal with command: `apt install libqt5sql5-sqlite`

For future reference, problems with programs not starting are faster answered on the [support forum](https://forums.linuxmint.com/viewforum.php?f=47).
