### ISSUE TITLE
No way to file Issues in the "*guide" GitHub projects

### ISSUE THREAD

**Issue by BillDietrich** [linuxmint/linuxmint#161]
In GitHub, the "Issues" and "New Issue" functionality is disabled in the Mint "*guide" projects, such as https://github.com/linuxmint/doc-translation-guide and https://github.com/linuxmint/doc-developer-guide

Please enable that functionality so issues can be reported, tracked, and fixed.  Thanks.

**Comment by xenopeek** [comment]
The guides look to accept pull requests so changes are tracked. If somebody has a correction or improvement for the documentation they can fork the project, make a branch for their change, do the change and then do a pull request to the project.

**Comment by BillDietrich** [comment]
Received this comment:

    The guides look to accept pull requests so changes are tracked. If somebody
    has a correction or improvement for the documentation they can fork the project,
    make a branch for their change, do the change and then do a pull request to the project.

I responded:

Pull requests are different from issues.  If someone says "here's
a bad/missing thing in the guides but I don't know how to fix it",
that's an issue.  Same thing for software.  Preventing people from
filing issues means only people who know how to fix something
can give any feedback on it, by doing fork/branch/change/pullrequest.

**Comment by xenopeek** [comment]
I posted that comment but deleted it afterwards for a reason :) Not my place to answer; I just made an observation of what is possible currently.

**Comment by xenopeek** [comment]
Issue can now also be reported against the documentation projects.
