### ISSUE TITLE
OpenArena Segmentation fault

### ISSUE THREAD

**Issue by Ekstreme** [linuxmint/linuxmint#167]
Running OpenArena installed from Software Manager will start fine. However when starting a map the game crashes.
----- Client Shutdown (Received signal 11) -----
RE_Shutdown( 1 )
OpenAL capture device closed.
-----------------------
----- Server Shutdown (Received signal 11) -----
tty]Segmentation fault (core dumped)

**Comment by smurphos** [comment]
It's an issue with the Ubuntu packaged version  - https://bugs.launchpad.net/ubuntu/+source/openarena/+bug/1651561

Last time I checked the flatpak version from Software Manager was fine.
