### ISSUE TITLE
Black screen when installing Linux Mint MATE 19.3 in Virtualbox

### ISSUE THREAD

**Issue by Petrouchka** [linuxmint/linuxmint#169]
I'm installing Linux Mint MATE 19.3 64 bit in a Virtualbox machine.
Virtualbox version is 5.2.34_Ubuntu r133883. It's running on Linux Mint MATE 19.2 64 bit.

If the installation is too long, the screen becomes black and remains black, impossible to see again the desktop even if I move and click the mouse or press keyboard.

I must reboot the virtual machine.

**Comment by xenopeek** [comment]
Try switching the VirtualBox display to VMSVGA if it's currently VBoxVGA or VBoxSVGA. The former is recommended by VirtualBox on Linux.

**Comment by Petrouchka** [comment]
I've got VirtualBox 5, so I can't test this. I will test when I will have version 6.0.

**Comment by xenopeek** [comment]
Above is the workaround mentioned in the release notes of 19.3 so I'll close this for now.
