### ISSUE TITLE
Aquantia atlantic module does not work after reboot

### ISSUE THREAD

**Issue by davidhw057** [linuxmint/linuxmint#17]
Atlantic is the name for Aquantia's 10Gb ethernet chip used in the Asus XG-C100C.  It's also known as AQtion AQC107.  Using Linux Mint 19 or Ubuntu 18.04 and other Linuxes with 4.15.xx kernel, the network card works from a cold boot if the power has been off long enough or turn the power off at the power supply for 10 sec, but will not work after a reboot.  NetworkManager says the cable is unplugged.  Restarting the network from systemd or ifdown ifup, unplugging plugging the cable, using the reset switch, nothing works.  It must be powered off.  Kernel 4.16.xx has no problem.  The module version is the same from kernel to kernel.  I downloaded the 4.16 source, compiled the module for 4.15 and had the same issue.  I'm currently running Linux Mint 19 with kernel 4.16.14 from http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.16.14.  Would you consider jumping ahead of Ubuntu and making 4.16.xx the Linux Mint 19 kernel?

**Comment by xenopeek** [comment]
Linux Mint 19 uses the HWE kernels from Ubuntu 18.04 repository. If you have problematic hardware that needs an even newer kernel you have various options. Like using Ukuu to install the kernel for you. For support with such things one can ask on the [forums](https://forums.linuxmint.com/).
