### ISSUE TITLE
Directories /media and /mnt missing in xnviewMP 0.93.1

### ISSUE THREAD

**Issue by logan82** [linuxmint/linuxmint#174]
Hello, I found a bug in xnview 0.93.1 and reported it to the developer. /media and /mnt directories does not show. This is fixed in 0.94.2. Linux Mint still serves 0.93.1. I manually upgraded to 0.94.2, so I have no issues. But other users may profit from the new version.

Installed Version: Linux Mint 19.3 Tricia
working Package:
philipp@latitude:~$ apt policy xnview
xnview:
  Installiert:           0.94.2
  Installationskandidat: 0.94.2
  Versionstabelle:
 *** 0.94.2 100
        100 /var/lib/dpkg/status

**Comment by xenopeek** [comment]
I can't find the package `xnview` in either Linux Mint, Ubuntu or Debian repositories. I assume you installed it from previously installed it from a repository or PPA you added or from downloaded .deb package.
