### ISSUE TITLE
The touchpad no longer works after installing linux-4.15.0-72.81 (kernel)

### ISSUE THREAD

**Issue by tabache** [linuxmint/linuxmint#175]
Hi, whenever I try to install package linux-4.15.0-72.81 my touchpad stop working.
So, I am force every time to come back to an old system snapshot.

I'm using a Dell Vostro 3546

Kernel 4.15.0-54-generic x86_64 bits
Distro: linux Mint 19.2 Tina base: ubuntu 18.04 bionic

**Comment by xenopeek** [comment]
This is a bug in that kernel version. See https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1854798. This should be fixed in kernel 4.15.0.74 please try installing that.
