### ISSUE TITLE
un repairable bug with VB DKMS and Beta 19

### ISSUE THREAD

**Issue by signmeuptoo** [linuxmint/linuxmint#18]
Rather than repost all the terminal windows of the problem, I'm referring the devs to this thread:

https://forums.linuxmint.com/viewtopic.php?f=231&t=271191

I installed the Beta of LM 19.0 on my Lenovo core i5 laptop (G580 with 8 GB RAM and 3210 processor) and it installed beautifully, but while installing the 5.2 version of Virtual Box in it using the software manager, and it seeming to do fine, Windows 10 in a VB would not run, as seen in that thread.

Our attempts to diagnose the problem yielded confusing results and I'm not literate enough to know if this is a bug, and if so, in the beta OR the VB product. LM was a totally fresh bare metal install and I had used software manager to add the VB version it provided.

**Comment by signmeuptoo** [comment]
Also, I am now unable to use the update manager, it won't run the update.

**Comment by xenopeek** [comment]
With secure boot enable you need to sign your kernel modules, which you didn't do. Apparently you're supposed to be prompted for this but the prompt isn't displayed. See upstream bug report: https://bugs.launchpad.net/ubuntu/+source/dkms/+bug/1775672.
