### ISSUE TITLE
MintReport keeps on telling to add Xapp-Status-Applet to the Xfce4-panel though it is there

### ISSUE THREAD

**Issue by KHeilen** [linuxmint/linuxmint#181]
Hello, dear Mint developers.

**Summary:**
Once per session, MintReport keeps on telling me to add Xapp-Status-Applet to the Xfce4-panel. But Xapp-Status-Applet has been added to the Xfce4-panel already.
This happens on Linux Mint 19.3 32-bit xfce, in-place upgraded from Linux Mint 19.1 32-bit xfce via Update Manager. Cf. [here](https://forums.linuxmint.com/viewtopic.php?f=60&t=307591), no obvious issues encountered.

**Details:**

Below is a screenshot of my Mint 19.3 xfce4 bottom panel.
![Mint19 3xfce-panel](https://user-images.githubusercontent.com/11710301/71523956-9581b800-28cb-11ea-8a69-8f3cb06c22e7.png)

Below is a screenshot of the objects which are present in the panel. As should be easily found out, the xapp-status-plugin (German: Xapp-Statuserweiterung) is listed. So it has been added to the panel already.
![xfce4-panel-xapp-status-plugin](https://user-images.githubusercontent.com/11710301/71523964-ac280f00-28cb-11ea-9f22-f55b5904fb94.png)

Nonetheless, once per Mint session, Mint Report will confront me with the problem diagnosed below and suggest to me to add the Xapp-Status-Applet to the panel.
![mintreport-add-xapp-status-applet](https://user-images.githubusercontent.com/11710301/71523979-bc3fee80-28cb-11ea-9fc8-5f83f6ee4aaa.png)

As illustrated above, the Xapp-Status-Applet has been added already.

- Why then tell me to add it?
- Has it been added incorrectly? (How to achieve so?)
- Is it because the Xapp-Status-Applet is not the right most item in the panel?
- What else could be wrong?
- Or is the Mint Report simply wrong in diagnosing the Xapp-Status-Applet still needed to be added to the panel?

**System information**

The obligatory **inxi** report, in particular because Mint Report kindly provides it anyway. 
[Zotac_inxi.txt](https://github.com/linuxmint/linuxmint/files/4005770/Zotac_inxi.txt)

The file **xfce4-panel.xml**, because it might hold a hint, why MintReport correctly or incorrectly complaints about Xapp-Status-Applet. 
[xfce4-panel.xml.txt](https://github.com/linuxmint/linuxmint/files/4005767/xfce4-panel.xml.txt)

**The list of installed packages (dpkg -l)**
[Zotac_Mint19.3_dpkg-l.txt](https://github.com/linuxmint/linuxmint/files/4005763/Zotac_Mint19.3_dpkg-l.txt)

In case there is anything else I should provide, please, let me know.

Cheers,
Karl

**Comment by KHeilen** [comment]
**Continued:**

As stated initially, the problem occurs on Linux Mint 19.3 32-bit xfce, in-place upgraded from Linux Mint **19.1** 32-bit xfce via Update Manager. 
It seems, however, that the same issue does not occur on a second Linux Mint 19.3 32-bit xfce, in-place upgraded from Linux Mint **19.2** 32-bit xfce via Update Manager.
Cf. [here](https://forums.linuxmint.com/viewtopic.php?f=47&t=308172&p=1734753#p1734753)

I.e. on Mint 19.3 xfce, upgraded in-place from Mint 19.2 xfce, mintreport does not keep on recommending Xapp-Status-Applet, after this applet has been added to the xfce4-panel once.

**inxi report:**
[Paulchen_inxi.txt](https://github.com/linuxmint/linuxmint/files/4006465/Paulchen_inxi.txt)

**dpkg -l output**
[Paulchen_dpkg-l.txt](https://github.com/linuxmint/linuxmint/files/4006466/Paulchen_dpkg-l.txt)

**Comment by samilanki** [comment]
I have similar problem.

**Comment by samilanki** [comment]
Same issue here with Linux Mint 19.3 32-bit xfce.

**Comment by dfortier2346** [comment]
Same issue here with Linux Mint 19.3 64-bit Cinnamon upgrade from 19.1 64-bit Cinnamon.

**Comment by snemes** [comment]
Same here with Linux Mint 19.3 Cinnamon (64-bit) upgraded from 19.2.

**Comment by mtwebster** [comment]
Hi, can any of you who still experience this please run the commands I've described in this link the next time it occurs?

https://github.com/linuxmint/mintreport/issues/39#issuecomment-571149907

Thanks!

**Comment by dfortier2346** [comment]
Will do.

**Comment by snemes** [comment]
Happened today again, here is the command output:
```
$ dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames | grep org.x
      string "org.x.StatusIcon.PID-2119-0"
      string "org.x.StatusIconMonitor.PID-2089-0"
      string "org.x.editor"
      string "org.x.StatusIcon.PID-2629-0"
      string "org.x.StatusIcon.PID-31533-0"

$ python3 -c "import gi; gi.require_version('XApp', '1.0'); from gi.repository import XApp; print(XApp.StatusIcon.any_monitors());"
True
```

**Comment by HelloMrKrinkle** [comment]
Try this:

go into the applet manager and remove the system tray applet while the xapp status applet is enabled - then reboot your pc

**Comment by KHeilen** [comment]
> Hi, can any of you who still experience this please run the commands I've described in this link the next time it occurs?
> [linuxmint/mintreport#39 (comment)](https://github.com/linuxmint/mintreport/issues/39#issuecomment-571149907)
Has not happened today, yet. This is why I have not executed the commands, yet.
Hopefully snemes's feedback above will be helpful.

**Comment by HelloMrKrinkle** [comment]
dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames | grep org.x
      string "org.x.StatusIconMonitor.PID-1460-0"
      string "org.x.StatusIcon.PID-1507-0"
      string "org.x.StatusIcon.PID-1511-0"
      string "org.x.StatusIcon.PID-1759-0"
      string "org.x.StatusIcon.PID-1619-0"
      string "org.x.StatusIcon.PID-1917-0"

**Comment by mtwebster** [comment]
Hi, there's a new version of xapps (1.6.10) that should be available, if not now, very soon (depending on your download mirror).

Thanks

**Comment by KHeilen** [comment]
These packages I assume:
ii  libxapp1:i386               1.6.10+tricia
ii  xapps-common                1.6.10+tricia 
Arrived here 09-Jan-2019 21:00 CET
Thanks a lot.
Will watch whether any more complaints will be raised by mintreport to add xapps-status-icon, though it has been added long ago.

**Comment by HelloMrKrinkle** [comment]
Cool - i just installed them myself also and i'll let you know how it goes

**Comment by HelloMrKrinkle** [comment]
so far so good.....

**Comment by KHeilen** [comment]
So far no more false alert has been raised by Mint System Report to add the xapps-status-applet, after
libxapp1:i386 1.6.10+tricia
xapps-common 1.6.10+tricia
had been installed on 09-Jan-2020 21:00 CET.
Keeping my fingers crossed.

**Comment by KHeilen** [comment]
Thanks a lot, mtwebster, for eliminating this small annoyance.
