### ISSUE TITLE
cvt delivers wrong modeline to xrandr

### ISSUE THREAD

**Issue by warepilot** [linuxmint/linuxmint#183]
### Description
As system is not showing more screen resolutions higher than `1024x768` by default, I used `cvt` to create a new one according to hardware specifications, say `1366x768`.
### Error
Modeline returned for that resolution is based on 136**8**x768 which may cause misunderstanding between graphic card and monitor. Those values are different from expected ones from a resolution 136**6**x768 formerly working.
### Versions
Tessa 32 bit, Tricia 64 bit

**Comment by xenopeek** [comment]
cvt calculates VESA CVT modelines and the VESA standard does dimensions in multiples of 8 which 1366 isn't. If you search for "cvt 1366 768" there are many reports on this and may provide a workaround.

cvt comes from xserver-xorg-core-hwe-18.04 / xserver-xorg-core package from the Ubuntu 18.04 LTS package base. As far as I can see cvt didn't previously recognize the non-standard width dimension.

If you need help with solving this issue I suggest to make a topic on the Graphics Cards & Monitors forum: https://forums.linuxmint.com/viewforum.php?f=59
