### ISSUE TITLE
Sound icon is huge

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#184]
After updating from Linux Mint MATE 19.2 to 19.3, I have two huge icons, sound and network. I installed Xapp and network icon becomes normal. But sound icon remains too big and not beautiful :
![image](https://user-images.githubusercontent.com/3955499/71555655-b1ea3580-2a2e-11ea-8e7e-d08a2cdf3fb1.png)

**Comment by mtwebster** [comment]
Are you in 'hidpi' mode? (such as for a 4k monitor)

**Comment by Petrouchka** [comment]
I don't think so. I did not have this problem with Mint MATE 19.2.
![image](https://user-images.githubusercontent.com/3955499/71630811-72297680-2c05-11ea-9283-59a76fe3bb34.png)

**Comment by mtwebster** [comment]
Ok, what's the resolution of your monitor?  That might be simpler.

I'll try to see if I can reproduce this.

**Comment by Petrouchka** [comment]
$ xrandr 
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 16384 x 16384
DVI-I-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 510mm x 287mm
   1920x1080     60.00*+
   1680x1050     59.88  
   1280x1024     60.02  
   1440x900      59.90  
   1280x800      59.91  
   1152x864      75.00  
   1024x768      70.07    60.00  
   800x600       60.32    56.25  
   640x480       66.67    59.94  
   720x400       70.08  
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)

**Comment by Petrouchka** [comment]
And when I'm printing, the printer icon is now strange :
![image](https://user-images.githubusercontent.com/3955499/72277728-bd467f00-3632-11ea-8eff-740be7f90e44.png)

**Comment by InfoLibre** [comment]
It's OK now in Linux Mint MATE 20. I close this bugreport.
