### ISSUE TITLE
mint theme resolution

### ISSUE THREAD

**Issue by PierrePharel** [linuxmint/linuxmint#185]
After update to 19.3, I installed the new grub mint theme but the resolution is low.
I don't know if is because I installed Mint on BIOS.

**Comment by xenopeek** [comment]
Do you mean the animated logo appears very large or small on the screen, or that your display resolution is lower than is native to your screen?

**Comment by PierrePharel** [comment]
I solved the problem, but the solution was not only install grub2-theme-mint-2k but install it, reinstall grub and delete default theme script which was with him

**Comment by PierrePharel** [comment]
So I close issue and Thank U  !
