### ISSUE TITLE
Mint 19 internet access failure (on an older Mac)

### ISSUE THREAD

**Issue by edwardc69** [linuxmint/linuxmint#19]
This is a regression from Mint 17.3 - neither ethernet cable nor wifi will connect to the internet using the LiveCD version of Mint 19, while both methods of getting onto the internet work in Mint 17.3.  I have not checked Mint 18.

Having no internet access at all makes it somewhat difficult to envision installing Mint 19 on this machine.

Here are the insxi results from both operating systems on the same hardware:

[insxi-from-mint19.txt](https://github.com/linuxmint/linuxmint/files/2153453/insxi-from-mint19.txt)

[inxi-from-mint17.3.txt](https://github.com/linuxmint/linuxmint/files/2153454/inxi-from-mint17.3.txt)

**Comment by xenopeek** [comment]
Linux Mint doesn't do kernel or hardware driver maintenance. If you have a problem with your hardware not working correctly I suggest you ask for help with solving that by posting a new topic on the [support forum](https://forums.linuxmint.com/).
