### ISSUE TITLE
Built-in mic showing odd behavior on laptop

### ISSUE THREAD

**Issue by RudahXimenes** [linuxmint/linuxmint#194]
Good day.

While using communications apps, like Discord, Steam, Pidgin, I cannot communicate by voice without using external mic.

If I plug any external mic on my laptop (I used beewi headset with mic), I could use voice chats properly. If I try to use built-in mic, it only record white noise. I must say that in Windows the built-in mic is working properly, so it's not a hardware issue.

To be even more bizarre, I notice that while I'm using built-in mic to record my voice, the signal-to-noise ratio go backwards. In other others words, looks like while I talk, the mic try to mute.

So I opened Alsamixer in terminal, pressed F4 to open mic settings and reduced all settings (Mic boost, Capture and Internal Mic Boost) to 0, raising slowly and trying to speak. Interesting I stoped to listen to white noise and start to hear my voice, but too low in volume.

Finally I noticed that I was listening my voice through my mic, that's why it was so low in volume.

So, in few words, my mic is not recording properly and the system is using my mic as speaker.

I'm using Linux Mint 19.3 on a Lenovo B40-30

```
System:    Host: rudah-mint Kernel: 5.0.0-37-generic x86_64 bits: 64 compiler: gcc v: 7.4.0 
           Desktop: Cinnamon 4.4.6 wm: muffin dm: LightDM Distro: Linux Mint 19.3 Tricia 
           base: Ubuntu 18.04 bionic 
Machine:   Type: Laptop System: LENOVO product: 80F10002BR v: Lenovo B40-30 serial: <filter> 
           Chassis: type: 10 v: Lenovo B40-30 serial: <filter> 
           Mobo: LENOVO model: Lenovo B40-30 v: SDK0E50515STD serial: <filter> UEFI: LENOVO 
           v: 9CCN30WW(V2.08) date: 11/26/2014 
Audio:     Device-1: Intel Atom Processor Z36xxx/Z37xxx Series High Definition Audio 
           vendor: Lenovo driver: snd_hda_intel v: kernel bus ID: 00:1b.0 chip ID: 8086:0f04 
           Sound Server: ALSA v: k5.0.0-37-generic
```

**Comment by xenopeek** [comment]
An annoying issue to troubleshoot. I suggest to first take help from the [support forums](https://forums.linuxmint.com/viewforum.php?f=49) to complete troubleshooting on this issue. I expect you'll need to wrestle with your hardware's drivers a bit, which are not developed by Linux Mint. If the root cause is found to be in a component developed by Linux Mint this issue can be reopened.
