### ISSUE TITLE
asus tuf series touchpad freezing after while 

### ISSUE THREAD

**Issue by NoWay619** [linuxmint/linuxmint#195]
i hava asus tuf series laptop. my mouse touchoad stop working after a while. i google for fix this problem but got no permanent solution.  in xinput list its shows a ELAN12000 driver show and people say this is the problem. i am new to linux os. i find a guy having a same problem in linux community https://forums.linuxmint.com/viewtopic.php?t=275161 plz help to solve this

**Comment by xenopeek** [comment]
Hope you already managed to solve this issue. If not, please do make a new topic on the forums to ask for help with solving it. I think this is a driver issue, not something Linux Mint can fix.
