### ISSUE TITLE
telegram-desktop version is obsolete

### ISSUE THREAD

**Issue by shentino** [linuxmint/linuxmint#198]
For telegram-desktop, the version currently in the mint repo is 1.2.17, but the upstream version at telegram.org is 1.7.14

**Comment by xenopeek** [comment]
This is not under control of Linux Mint. The telegram-desktop package comes from the Ubuntu Bionic universe repository: https://packages.ubuntu.com/bionic/telegram-desktop. The universe repositories in general see few if any feature upgrades, mostly only security fixes. New feature releases are generally added to repositories of new Ubuntu releases. So you can expect a newer Telegram version on Linux Mint 20 due mid this year.

Assuming you don't want to wait for that, and you're on Linux Mint 18.3 or newer, you can install Telegram from the Flatpak category in your Software Manager. That has version 1.8.15 currently: https://flathub.org/apps/details/org.telegram.desktop

For such questions the [support forums](https://forums.linuxmint.com/viewforum.php?f=47) are generally faster to answer.

**Comment by shentino** [comment]
For the record since you cited ubuntu as the source of the package in question I went ahead and filed a bug with them

https://bugs.launchpad.net/ubuntu/+source/xubuntu-meta/+bug/1862875
