### ISSUE TITLE
Some suggestions to make the system better.

### ISSUE THREAD

**Issue by ghost** [linuxmint/linuxmint#201]
I have some suggestions for Mint. 
Exclude Flash from "Install proprietary software" option
 Add keyboard layout settings to installer 
Enable "Don't break my PC" and "Older versions" by default  in update manager 
Replace 4.15 with the latest LTS kernel
Autoselect fastest mirror in apt and mintupdate

**Comment by xenopeek** [comment]
Thanks for your suggestions. I the future please do one suggestion per issue, post it in relevant repository (e.g., suggestions for mintupdate should go to mintupdate) and search before posting if a related (open or closed) issue exists. For more information about the feature request workflow see the [FAQ](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html).
