### ISSUE TITLE
POWER (ppc64le) support

### ISSUE THREAD

**Issue by madscientist159** [linuxmint/linuxmint#207]
With most Linux distributions already supporting the ppc64le (POWER) desktop and server architecture (including Debian and Ubuntu), would it be possible to add ppc64le builds for Linux Mint?  If hardware cost is a concern, we could very likely provide a physical build server free of charge to the project.

Thanks!

**Comment by leo-lb** [comment]
Yes please! :-)

**Comment by Matthew-Bradley** [comment]
Dito! Would love to see Mint support power!

**Comment by xenopeek** [comment]
Hi, thanks for making a suggestion for Linux Mint and for offering a build server. Most generous! Right now Linux Mint only support Intel & AMD. To those that upvoted, thanks for your interest for Linux Mint on POWER. See the [workflow](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html#why-are-ideas-and-feature-requests-closed) for suggestions for why this is closed here.
