### ISSUE TITLE
Kernel update freezes key board and cursor

### ISSUE THREAD

**Issue by beeshyams** [linuxmint/linuxmint#21]
The latest release of kernel 4.15.0-24.26-generic freezes my keyboard cursor and keyboard also (There was gnome control center update too but I am not sure if that can cause this problem)- this I discovered on booting my system today . Asus X541NA. Rolled back to previous version

I cannot generate any reports from terminal to share about this since keyboard freezes

Aside, starting from beta, keyboard cursor only Freezes on hibernating or suspending

shyam@shyam-X541NA:~$ inxi -Fxxrzc0
System:    Host: shyam-X541NA Kernel: 4.15.0-23-generic x86_64
           bits: 64 gcc: 7.3.0
           Desktop: Cinnamon 3.8.6 (Gtk 3.22.30-1ubuntu1) dm: lightdm
           Distro: Linux Mint 19 Tara
Machine:   Device: laptop System: ASUSTeK product: X541NA v: 1.0 serial: N/A
           Mobo: ASUSTeK model: X541NA v: 1.0 serial: N/A
           UEFI: American Megatrends v: X541NA.318 date: 02/27/2018
Battery    BAT0: charge: 34.4 Wh 98.2% condition: 35.0/34.6 Wh (101%)
           volts: 10.8/10.8
           model: ASUSTeK ASUS serial: N/A status: Discharging
CPU:       Quad core Intel Pentium N4200 (-MCP-) arch: N/A cache: 1024 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 8755
           clock speeds: min/max: 800/2500 MHz 1: 1044 MHz 2: 1012 MHz
           3: 896 MHz 4: 932 MHz
Graphics:  Card: Intel Celeron N3350/Pentium N4200/Atom E3900 Series Integrated Graphics Controller
           bus-ID: 00:02.0 chip-ID: 8086:5a84
           Display Server: x11 (X.Org 1.19.6 )
           drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1366x768@60.02hz
           OpenGL: renderer: Mesa DRI Intel HD Graphics 505 (Broxton)
           version: 4.5 Mesa 18.0.0-rc5 (compat-v: 3.0) Direct Render: Yes
Audio:     Card Intel Celeron N3350/Pentium N4200/Atom E3900 Series Audio Cluster
           driver: snd_hda_intel bus-ID: 00:0e.0 chip-ID: 8086:5a98
           Sound: Advanced Linux Sound Architecture v: k4.15.0-23-generic
Network:   Card-1: Realtek RTL8101/2/6E PCIE Fast/Gigabit Ethernet controller
           driver: r8169 v: 2.3LK-NAPI port: e000
           bus-ID: 01:00.0 chip-ID: 10ec:8136
           IF: enp1s0 state: down mac: <filter>
           Card-2: Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter
           driver: ath9k bus-ID: 02:00.0 chip-ID: 168c:0036
           IF: wlp2s0 state: up mac: <filter>
Drives:    HDD Total Size: 1000.2GB (17.8% used)
           ID-1: /dev/sda model: ST1000LM035 size: 1000.2GB serial: <filter>
Partition: ID-1: / size: 46G used: 7.3G (17%) fs: ext4 dev: /dev/sda6
           ID-2: /home size: 428G used: 75G (19%) fs: ext4 dev: /dev/sda8
           ID-3: swap-1 size: 7.00GB used: 0.00GB (0%)
           fs: swap dev: /dev/sda7
RAID:      System: supported: N/A
           No RAID devices: /proc/mdstat, md_mod kernel module present
           Unused Devices: none
Sensors:   System Temperatures: cpu: 39.0C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Repos:     Active apt sources in file: /etc/apt/sources.list.d/official-package-repositories.list
           deb http://packages.linuxmint.com tara main upstream import backport #id:linuxmint_main
           deb http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse
           deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse
           deb http://archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse
           deb http://security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
           deb http://archive.canonical.com/ubuntu/ bionic partner
Info:      Processes: 237 Uptime: 2:47 Memory: 2110.2/3776.8MB
           Init: systemd v: 237 runlevel: 5 Gcc sys: 7.3.0
           Client: Shell (bash 4.4.191 running in gnome-terminal-) inxi: 2.3.56

**Comment by JosephMcc** [comment]
Not sure what the problem is, but I've seen multiple people reporting issues with that kernel update.

**Comment by xenopeek** [comment]
This may be a regression issue specific to your hardware or it may be a more general regression issue. I suggest you ask for help with troubleshooting / finding workaround by posting a new topic on the [support forum](https://forums.linuxmint.com/).
