### ISSUE TITLE
Wrong forums link in os-release file

### ISSUE THREAD

**Issue by mhampl** [linuxmint/linuxmint#211]
/usr/lib/os-release from the package base-files (e.g. version 19.3.0) contains
SUPPORT_URL="https://forums.ubuntu.com/"

In my opinion this is wrong and should be replaced by
SUPPORT_URL="https://forums.linuxmint.com/"

**Comment by xenopeek** [comment]
It's incorrect on Linux Mint 20 as well. The `/usr/lib/os-release` file, to which `/etc/os-release` links, from the `base-files` package also has the Ubuntu forums instead of Linux Mint forums:
```
NAME="Linux Mint"
VERSION="20 (Ulyana)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20"
VERSION_ID="20"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.ubuntu.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=ulyana
UBUNTU_CODENAME=focal
```

**Comment by clefebvre** [comment]
Fixed.
