### ISSUE TITLE
where to report firefox apparmor bugs? and what is "upstream" in packages.linuxmint.com?

### ISSUE THREAD

**Issue by qdinar** [linuxmint/linuxmint#212]
there is linux mint's firfox package, but no firefox page here in linux mint's github page. there it is written "upstream" in http://packages.linuxmint.com/search.php?release=Tricia&section=any&keyword=firefox , what does it mean?

**Comment by xenopeek** [comment]
It means the software is not developed by Linux Mint but by an upstream project and that is is packaged by Linux Mint. For example to provide a newer version or different configuration than the package in the base repository.
