### ISSUE TITLE
dkms is broken - according to the Wireguard team, and admittedly on an unsupported kernel

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/linuxmint#213]
On kernels <=5.3, Wireguard works fine on Mint. On kernels 5.4.x, it does not but instead produces errors when building the Wireguard module - please see the log I attach.

[make.log](https://github.com/linuxmint/linuxmint/files/4134914/make.log)

I asked the Wireguard people about this. They told me: 'Tell your distro dkms is broken.'

Cf. perhaps #142.

I am aware that this problem might be with Ubuntu.

EDIT: Here are my system details.
```

~ $ inxi -Fxz
System:    Host: x1 Kernel: 5.3.18-050318-generic x86_64 bits: 64 compiler: gcc v: 9.2.1 
           Desktop: Cinnamon 4.4.8 Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic 
Machine:   Type: Laptop System: LENOVO product: 20KHCTO1WW v: ThinkPad X1 Carbon 6th 
           serial: <filter> 
           Mobo: LENOVO model: 20KHCTO1WW serial: <filter> UEFI: LENOVO v: N23ET69W (1.44 ) 
           date: 11/25/2019 
Battery:   ID-1: BAT0 charge: 50.7 Wh condition: 52.6/57.0 Wh (92%) model: LGC 01AV494 
           status: Unknown 
           Device-1: hidpp_battery_0 model: Logitech M720 Triathlon Multi-Device Mouse 
           charge: 55% status: Discharging 
CPU:       Topology: Quad Core model: Intel Core i7-8550U bits: 64 type: MT MCP arch: Kaby Lake 
           rev: A L2 cache: 8192 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 31999 
           Speed: 800 MHz min/max: 400/4000 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 4: 800 
           5: 800 6: 800 7: 800 8: 800 
Graphics:  Device-1: Intel UHD Graphics 620 vendor: Lenovo driver: i915 v: kernel 
           bus ID: 00:02.0 
           Display: x11 server: X.Org 1.20.5 driver: modesetting unloaded: fbdev,vesa 
           resolution: 2560x1440~60Hz 
           OpenGL: renderer: Mesa DRI Intel UHD Graphics 620 (Kabylake GT2) v: 4.5 Mesa 19.2.1 
           direct render: Yes 
Audio:     Device-1: Intel Sunrise Point-LP HD Audio vendor: Lenovo driver: snd_hda_intel 
           v: kernel bus ID: 00:1f.3 
           Sound Server: ALSA v: k5.3.18-050318-generic 
Network:   Device-1: Intel Ethernet I219-V vendor: Lenovo driver: e1000e v: 3.2.6-k port: efa0 
           bus ID: 00:1f.6 
           IF: enp0s31f6 state: down mac: <filter> 
           Device-2: Intel Wireless 8265 / 8275 driver: iwlwifi v: kernel port: efa0 
           bus ID: 02:00.0 
           IF: wlp2s0 state: up mac: <filter> 
           IF-ID-1: lxcbr0 state: down mac: <filter> 
           IF-ID-2: mullvad-gb4 state: unknown speed: N/A duplex: N/A mac: N/A 
Drives:    Local Storage: total: 476.94 GiB used: 184.07 GiB (38.6%) 
           ID-1: /dev/nvme0n1 model: LENSE20512GMSP34MEAT2TA size: 476.94 GiB 
Partition: ID-1: / size: 39.25 GiB used: 18.65 GiB (47.5%) fs: ext4 dev: /dev/nvme0n1p4 
           ID-2: /home size: 404.42 GiB used: 165.41 GiB (40.9%) fs: ext4 dev: /dev/nvme0n1p2 
           ID-3: swap-1 size: 20.43 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/nvme0n1p3 
Sensors:   Missing: Required tool sensors not installed. Check --recommends 
Info:      Processes: 268 Uptime: 36m Memory: 15.53 GiB used: 3.83 GiB (24.7%) Init: systemd 
           runlevel: 5 Compilers: gcc: 7.4.0 Shell: bash v: 4.4.20 inxi: 3.0.32
```

**Comment by LinuxOnTheDesktop** [comment]
The solution is here: https://github.com/xanmod/linux/issues/33 (sorry; linking is not working the editor at present, for some reason). The solution amount to the following, which installs new versions of the c compiler (and updates various other packages).

  sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  sudo add-apt-repository ppa:savoury1/gcc-defaults-9
  sudo apt-get update
  sudo apt-get upgrade && sudo apt-get dist-upgrade

All seems to work. I infer that the (terse) description given by the Wireguard team ('DKMS is broken') may be inaccurate.

**Comment by Ldfa** [comment]
Try :
sudo apt remove dkms-wireguard
sudo apt install dkms-wireguard

dkms-wireguard does not seem to update during an : 
sudo apt update
sudo apt upgrade

**Comment by dcpontius** [comment]
None of the solutions worked for me.  On my Mint 19.3 system, I had to:
- clone the https://git.zx2c4.com/wireguard-linux-compat repo
- Find the commit that broke the build: 
* 1325bed 2020-05-04 | compat: Ubuntu 19.10 and 18.04-hwe backported skb_reset_redirect [Jason A. Donenfeld]
- Checkout the last tag before that commit was pushed:
git checkout v1.0.20200429
- Recompile and install per the published wireguard build instructions
- Reboot
and then my existing wireguard VPN config came right up.
