### ISSUE TITLE
External USB drive enclosure light does not work properly on USB3.0 ports on Mint 19.3 mate

### ISSUE THREAD

**Issue by wpshooter** [linuxmint/linuxmint#216]
Am having a problem in that the access/activity light on my Startech external USB drive enclosure on some (but not all) occasions does not go OFF (as it is supposed to) when performing a safe removal, sometimes the light will just blink on and off after safe removal is clicked on, it should just go OFF.

This only happens when I have the USB3.0 ports enabled in BIOS.  As long as I keep USB3.0 ports turned off in BIOS, the light works correctly on the system's remaining USB2.0 ports.   If, however, I have the USB3.0 ports enabled in BIOS, the problem happens sometimes on both the USB2.0 and USB3.0 ports.

I called Startech about this and their conclusion was that this is a problem with handling of USB3.0 ports by Linux.  I am seeing that from my testing and a friends testing this problem is not exhibited on a MS$ OS machine.

My research revealed that this problem is also exhibited on other brands of USB external enclosures.

Contact me at joverstreet1@verizon.net if you need further details.

Did some further testing and found that the above described problem occurs on Linux Mint and Ubuntu but NOT on MX Linux.

Thanks.

**Comment by xenopeek** [comment]
I hope you already found a solution for this, possibly by upgrading to a newer kernel release (as MX Linux had at the time) or upgrading to LM20. That LM and Ubuntu showed the same symptoms is not surprising as LM uses the kernel and udev (the dynamic device manager, for USB storage devices and others) from Ubuntu.  If you're still having this issue I suggest to take help with [troubleshootaing](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) it from the [support forums.](https://forums.linuxmint.com/viewforum.php?f=49). Hopefully this can be solved by setting some kernel parameter or upgrading to a different kernel version.
