### ISSUE TITLE
Not booting - missing mmx64.efi

### ISSUE THREAD

**Issue by spirulin** [linuxmint/linuxmint#217]
**Describe the bug**

I can't even boot because mmx64.efi is missing.
This is the error I was getting right after my Acer logo and the laptop was shutting down:

> Failed to open \EFI\BOOT\mmx64.efi - Not Found
> 
> Failed to load image \EFI\BOOT\mmx64.efi: Not Found
> 
> Failed to start MokManager: Not Found
> 
> Something has gone seriously wrong: import_mok_state() failed : Not Found

**To Reproduce**

Burn the the latest Mint 19.3 (All versions do the same thing) to USB and try to boot.
This maybe on Acer laptop with UEFI boot so not sure if it will happen to everyone.

**Expected behavior**

It should boot with no problems.

**Platform Information**

Intel Celeron Processor N2840, up to 2.58 GHz
4 GB DDR3L
1 TB HDD
Intel HD Graphics

**Additional context**

I was able to fix it myself:
In the USB: Copied the grubx64.efi from /boot/efi folder to another folder, renamed it to mmx64.efi and put it back in the folder. So now I have grubx64.efi and mmx64.efi in the EFI folder on my USB drive. And it boots with no problems.

It would be nice if you add it to the next iso so new people coming to your OS don't have to deal with this.

Had no problem booting Ubuntu 19.10 because it has both grubx64.efi and mmx64.efi in the EFI folder when burned to USB.

**Comment by xenopeek** [comment]
I can't say what the cause of this was on LM19.3 but glad you had a workaround. I checked on LM20 and it did install that file to that location for me. If any are having similar issue on LM20 I would suggest to first take help with [troubleshootaing](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) it from the [support forums.](https://forums.linuxmint.com).
