### ISSUE TITLE
a freeze case

### ISSUE THREAD

**Issue by qdinar** [linuxmint/linuxmint#218]
[freeze 2020-02-13.txt](https://github.com/linuxmint/linuxmint/files/4197112/freeze.2020-02-13.txt)

i attach part of syslog. i think, i woke laptop up at 01:09:56, then after several minutes it freezed, then i turned it off with power button, then started. i think, the time it restarted is 01:12:28. before the restart logs there are multiple \00 s, i think, they are 0 bytes, copied as \00.

linux mint 19.3 64bit. some latest updates were not installed. last apt upgrade was runned on february 3.

several hours before the freeze, when the laptop was in sleep, an android phone, which was connected to same local wifi, has freezed, and was similarly restarted.

**Comment by xenopeek** [comment]
I hope you already managed to solve this issue. Perhaps by upgrading to a newer kernel release or upgrading to Linux Mint 20. In any case, this sounds like it was a Linux kernel issue which isn't developed or maintained by Linux Mint but upstream. The Linux Mint developers can't do much on this issue.  If you're still having this issue I suggest to take help with [troubleshootaing](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) it from the [support forums.](https://forums.linuxmint.com/viewforum.php?f=49). Hopefully this can be solved by setting some kernel parameter or upgrading to a different kernel version.
