### ISSUE TITLE
Delayed Firefox updates

### ISSUE THREAD

**Issue by terr72** [linuxmint/linuxmint#219]
Firefox 73 was released 3 days ago fixing several serious vulnerabilities.
Yet there are still no updated packages offered.
The same applies to the latest Thunderbird.
Unfortunately this happens regularly with every new Mozilla release. I remember waiting up to a week after Mint distributes updated packages.

What is the reason behind this?
IMHO this should be improved to a maximum of 1-2 days after release.

**Comment by clefebvre** [comment]
Thunderbird is maintained by Ubuntu directly. Firefox updates follow Ubuntu's closely as well. They're planned for today for bionic. The xenial release is awaiting a C++ backport.
