### ISSUE TITLE
Cannot log in to desktop session with LightDM

### ISSUE THREAD

**Issue by lordairivis** [linuxmint/linuxmint#22]
I attempted to do an in-place upgrade of my 18.3 installation and to meet the 19.0+ installation prerequisites I switched my default greeter from MDM to LightDM using `sudo dpkg-reconfigure lightdm` and selected LightDM. After a reboot I attempted to log in but was just cycled back to the login screen. The greeter appears to accept my password (i.e. I am not presented with any authentication errors, or any errors at all for that matter), but does not send me to my desktop.

Things that do work:
I am able to log in to a terminal using `Ctrl+Alt+F3` and from there I am able to run `sudo` without issue. I am also able to log in using the guest option from LightDM, after which I am presented with a Cinnamon desktop.

Things that do not work:
I am unable to log in from LightDM using my own user account.

Output of `lspci`: [lspci.txt](https://github.com/linuxmint/linuxmint/files/2164216/lspci.txt)
Output of `dpkg -l`: [dpkg -l.txt](https://github.com/linuxmint/linuxmint/files/2164223/dpkg.-l.txt)

lightdm.log: [lightdm.log](https://github.com/linuxmint/linuxmint/files/2164214/lightdm.log)
.xsession-errors: [xsession-errors.txt](https://github.com/linuxmint/linuxmint/files/2164215/xsession-errors.txt)

**Comment by xenopeek** [comment]
I hope you were already able to solve the problem with your account. I would otherwise suggest to ask for help on the [support forum](https://forums.linuxmint.com/) by posting a new topic.
