### ISSUE TITLE
Problem with the touchpad in kernel 5.3 *

### ISSUE THREAD

**Issue by ArtificialReminisce** [linuxmint/linuxmint#220]
In kernel version 5.3 *, the touchpad does not work properly. On the login screen it works, but after logging in, only the left half of the touchpad works. Both click buttons work. Here I leave the files with the hardware information, etc. (The names of each are the commands I used).

[xinput -list.txt](https://github.com/linuxmint/linuxmint/files/4204966/xinput.-list.txt)
[inxi -Fxxrzc0.txt](https://github.com/linuxmint/linuxmint/files/4204967/inxi.-Fxxrzc0.txt)

By the way, thanks for the effort you make every day. :)

**Comment by xenopeek** [comment]
Hope you already managed to solve this issue, maybe by upgrading to LM20. If you're still having this issue I suggest to take help with [troubleshootaing](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) it from the [support forums.](https://forums.linuxmint.com/viewforum.php?f=49). Hopefully this can be solved by setting some kernel parameter or upgrading to a different kernel version.
