### ISSUE TITLE
gnote confusses: even when I have uninstalled tomboy, gnote contains references to tomboy

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/linuxmint#221]
It's very confusing: one reads [these release notes](https://www.linuxmint.com/rel_tricia_cinnamon_whatsnew.php); one uninstalls tomboy (if one has upgraded an earlier version of Mint); one installs gnote; and then gnote looks just like tomboy (is that the idea?) and gnote even contains references - that is shows the user - to tomboy. Screenshot:

![image](https://user-images.githubusercontent.com/47056543/74597199-d20f9b80-5052-11ea-8a6c-2c60abe6d735.png)

Perhaps the reference to tomboy within the application is an artefact of upgrading; if so, well, you should have thought of this. Or so it seems to me. Please somehow make this matter less muddled.

**Comment by xenopeek** [comment]
Thanks for this suggestion. Indeed Gnote and Tomboy use the same notes database so what you write in one also appears in the other. Normally that may be a great feature (you can switch applications and continue using your notes without need to export/import or retype them all) but indeed Tomboy inserts its own notes with getting started tips for users which then are also shown in Gnote.
