### ISSUE TITLE
Wine and other packages cannot be installed LM19.3 + Cinnamon

### ISSUE THREAD

**Issue by Silveriomrs** [linuxmint/linuxmint#223]
Good evening,
Well... there is a long thread in a Spanish forum:
 https://forums.linuxmint.com/viewtopic.php?f=68&t=311264&start=20

So let me quote it in order to save pictures and so on.
The main issue is after updating to **LM 19.3 with Cinnamon** desktop enviroment, it is not possible to Install any version of WINE, the thread explain the problems, farther than it... also happen the same with winff, it shows that not possible to install it, even when it is, tried many times, many ways... comment in that forum and others... nothing solve it. 

To discard any additional issue I installed **LM 19.3 in a VM with VirtualBox**, so it was fresh and the issue is there also. 

Many engineers, students and teachers need it in order to be able to work with WindowsXP or 7 software (usually electronic simulators and so on) it is really annoying, the only way to be able to install what we had before... is to roll back the release. 

Also in Ubuntu exist this problem, but somehow they can solve it with...
https://askubuntu.com/questions/1205550/cant-install-wine-on-ubuntu-actually-lubuntu-18-04/1205624

**it works not for us.**

> silverio@Loki-ligero:~$ sudo apt-get update

Obj:1 http://linux.teamviewer.com/deb stable InRelease
Obj:2 http://download.virtualbox.org/virtualbox/debian bionic InRelease        
Obj:3 https://repo.skype.com/deb stable InRelease                              
Obj:4 http://archive.canonical.com/ubuntu bionic InRelease                     
Obj:5 http://ppa.launchpad.net/cybermax-dexter/sdl2-backport/ubuntu bionic InRelease
Obj:6 http://archive.ubuntu.com/ubuntu bionic InRelease                        
Des:7 http://security.ubuntu.com/ubuntu bionic-security InRelease [88,7 kB]    
Obj:8 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                
Obj:9 http://ppa.launchpad.net/danielrichter2007/grub-customizer/ubuntu bionic InRelease
Obj:10 http://archive.ubuntu.com/ubuntu bionic-backports InRelease             
Ign:11 http://packages.linuxmint.com tricia InRelease                          
Obj:12 http://ppa.launchpad.net/freecad-maintainers/freecad-stable/ubuntu bionic InRelease
Obj:13 http://packages.linuxmint.com tricia Release                            
Obj:14 http://ppa.launchpad.net/geany-dev/ppa/ubuntu bionic InRelease          
Obj:15 https://download.sublimetext.com apt/stable/ InRelease                  
Obj:16 http://ppa.launchpad.net/js-reynaud/kicad-5.1/ubuntu bionic InRelease   
Obj:17 http://ppa.launchpad.net/openshot.developers/ppa/ubuntu bionic InRelease
Obj:18 http://ppa.launchpad.net/thopiekar/cura/ubuntu bionic InRelease      
Descargados 88,7 kB en 2s (48,4 kB/s)                  
Leyendo lista de paquetes... Hecho
silverio@Loki-ligero:~$ 

silverio@Loki-ligero:~$ LC_ALL=C apt install --install-recommends wine-installer
[sudo] password for silverio:         
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 wine-installer : Depends: libsdl2-2.0-0:i386
E: Unable to correct problems, you have held broken packages.
silverio@Loki-ligero:~$ 

silverio@Loki-ligero:~$ apt policy libpulse0:i386
libpulse0:i386:
  Instalados: (ninguno)
  Candidato:  1:11.1-1ubuntu7.4
  Tabla de versión:
     1:11.1-1ubuntu7.4 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages
     1:11.1-1ubuntu7 500
        500 http://archive.ubuntu.com/ubuntu bionic/main i386 Packages
silverio@Loki-ligero:~$
> 

In the next images you observes that it is not possible to install any version but 64bits... what I tried it, but not useful at all. 
I wonder if it is bounded also with the Winff that has the same issue.
Thank you

![otra mas](https://user-images.githubusercontent.com/33696002/74615933-1a978980-5125-11ea-9d8d-4974764b3194.png)
Winff software that was **available before the upgrade to LM19.3**

![Sin título](https://user-images.githubusercontent.com/33696002/74615873-c2608780-5124-11ea-939d-6d9c29264f96.jpg)
![wine-stable](https://user-images.githubusercontent.com/33696002/74615875-c391b480-5124-11ea-83f7-a3c05994d0b1.png)
![wine_64](https://user-images.githubusercontent.com/33696002/74615877-c391b480-5124-11ea-89cf-c877b6f939f2.png)
![wine_flatpak_nd](https://user-images.githubusercontent.com/33696002/74615878-c42a4b00-5124-11ea-8584-628bfe21e8b3.png)
![wine en MV](https://user-images.githubusercontent.com/33696002/74615879-c42a4b00-5124-11ea-9010-874cef85418f.png)

**Comment by SimonIremonger** [comment]
@Silveriomrs from what I can see, wine 4.0 pictured above is no longer relevant, not the version in ubuntu 18.04 any-more
Please check this bug is still relevant, close if you can.
From what I can see you can just install Mint-20 and have 'wine' package verison 5.0-3ubuntu1 now anyway, without needing to add additional/optional repositories.

**Comment by Silveriomrs** [comment]
> @Silveriomrs from what I can see, wine 4.0 pictured above is no longer relevant, not the version in ubuntu 18.04 any-more
> Please check this bug is still relevant, close if you can.
> From what I can see you can just install Mint-20 and have 'wine' package verison 5.0-3ubuntu1 now anyway, without needing to add additional/optional repositories.

You are compleately right. It is not a problem nowadays. It was a big problem with the before release. :) I will close the thread. Thank you SimonIremonger
