### ISSUE TITLE
black screen after kernel update

### ISSUE THREAD

**Issue by griga-upjs** [linuxmint/linuxmint#23]
Hello!

I have a black screen instead of login screen after last update on my Linux Mint 18.3. The kernel version changed from 4.13.0-45 to 4.15.0-24. After kernel downgrade back to 4.13.0-45 everythings fine. 'nomodeset' kernel parameter doesn't helped - just software rendering session after login.

The machine is laptop HP ProBook 650 with two graphics card:

00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Mars [Radeon HD 8730M] (rev ff)

I am using it with docking station with two external displays connected. Some time ago (do not remember exact kernel versions) I had simmilar problem, but it was fixed after some kernel release. Any suggestions what to try?

**Comment by xenopeek** [comment]
I hope you were already able to solve the problem with your account. I would otherwise suggest to ask for help on the [support forum](https://forums.linuxmint.com/) by posting a new topic.
