### ISSUE TITLE
LMDE based on Devuan. feature request.

### ISSUE THREAD

**Issue by DI555** [linuxmint/linuxmint#233]
i'd like to ask about LMDE based on Devuan! (not Debian please!)
imo, it will bring more popularity and productivity in LMDE!

**Comment by JosephMcc** [comment]
Thank you for the request but I don't think you will see this happening.

**Comment by DI555** [comment]
@JosephMcc ,
Hello again!
May be now it's the time to LMDE be based on Devuan distro ???
