### ISSUE TITLE
Feature request: New windows cannot be greater than 60%

### ISSUE THREAD

**Issue by myfirstnameispaul** [linuxmint/linuxmint#234]
This is pretty much a dream feature for me at least since Windows 95:

No new window can be greater than 60% unless maximized. I don't care what I had it at the last time I closed it, I don't want a new one like this. I especially don't want a new window not maximized to be at 100%, especially since Mint seems to behave such that I have approximately 1 pixel's width to grab a window edge.

**Comment by xenopeek** [comment]
Thanks for making a suggestion for Linux Mint. See the feature request [workflow](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html#why-are-ideas-and-feature-requests-closed) for why this is closed here.

As a suggestion for right now: you can possibly achieve something similar with a tool like devilspie2. It's a window matching tool that lets you script window actions (like resizing the window if it's not maximized by larger than you want). You can ask on the [support forums](https://forums.linuxmint.com/viewforum.php?f=47) if you need more pointers on getting it working.
