### ISSUE TITLE
[Mint 18.3] Firefox 61.0 Scrollbar marker unproportionally big

### ISSUE THREAD

**Issue by Nebelkind** [linuxmint/linuxmint#24]
After installing todays Updates the position marker on the scrollbar of firefox 61.0+linuxmint1+sylvia is displayed unproportionally big compared to other applications and previous versions. 
Behavior could be observed on two independent machines running 18.3.
The mint 19 version of Firefox 61 does display the marker in the expected normal proportions.
A fix for 18.3 would be appreciated.

**Comment by JosephMcc** [comment]
I only have 19 installed at the moment. Could you post a screenshot of what you're talking about?

**Comment by xenopeek** [comment]
What desktop environment. Cinnamon, MATE, Xfce or KDE?
