### ISSUE TITLE
Keyboard Custom Shortcut disappeared

### ISSUE THREAD

**Issue by myfirstnameispaul** [linuxmint/linuxmint#240]
It is hard to confirm when the bug began, but I discovered a Keyboard Custom Shortcut has disappeared and I discovered it immediately after upgrading to 5.3.0-46.

The shortcut was for `Ctrl+Q` to run `true` so that I do not close windows when intending to press `Ctrl+W`.

**Comment by xenopeek** [comment]
For such it's usually better to first take help with [troubleshootaing](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) and finding the exact from the [support forums.](https://forums.linuxmint.com). I can't see who the two would have been related; package updates don't touch user configuration or preferences files stored in home directories. Packages updates only touch files in system directories. Custom keyboard shortcuts are configured per user and stored in their home directory.
