### ISSUE TITLE
Firefox 75.0 Mint-specific patches cripple search.json.mozlz4

### ISSUE THREAD

**Issue by terr72** [linuxmint/linuxmint#242]
It already happened in FF74, that the Mint version of Firefox replaced my search.json.mozlz4 (Google as default search engine) with a Mint-specific search.json.mozlz4 with Yahoo as default and no Google at all.

It was able to re-add Google using the link on https://www.linuxmint.com/searchengines.php, although it lacked the Google icon due to it not being included in https://www.linuxmint.com/searchengines/anse.php?sen=Google&c=y.

Now FF75 came out and it happened again: search.json.mozlz4 was replaced with the Mint-specific search.json.mozlz4 with Yahoo as default. And again no more Google.

The exact same happens when I copy a search.json.mozlz4 from a Kubuntu FF75 over to my Mint FF, it's being replaced as well. Copying from Kubuntu FF75 to a FF75 inside Arch or Xubuntu works fine.

Please improve your patching mechanism so that the automatic replacements don't happen anymore.

**Comment by terr72** [comment]
And it has happened again with Firefox 76.
Why are you still overwriting the search.json.mozlz4 with your own default version by force?

**Comment by clefebvre** [comment]
You shouldn't modify these by hand. Adding an engine as user should stick and not be modified by updates. There might have been changes as Firefox modified the way engines worked. Other than that it shouldn't affect it.
