### ISSUE TITLE
REQUEST : replace PDF-Shuffler by pdfarranger in MATE repository (and in other editions repositories)

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#245]
In MATE 19.3 edition, I did not find pdfarranger (I don't know if it's the same in other Linux Mint editions). I had to add the pdfarranger PPA.
pdfarranger is a better fork of the unmaintained PDF-Shuffler. Could you replace PDF-Shuffler by pdfarranger in the Linux Mint repositories ?

pdfarranger : https://github.com/jeromerobert/pdfarranger
pdfarranger binaries : https://github.com/jeromerobert/pdfarranger/wiki/Binary-packages

**Comment by InfoLibre** [comment]
pdfarranger is in debian and Ubuntu, not in Linux Mint : https://repology.org/project/pdfarranger/versions

**Comment by xenopeek** [comment]
pdfarranger is available in Linux Mint 20 (upcoming release) and in LMDE 4.

As pdfarranger isn't available in Ubuntu 18.04 LTS it wasn't available on Linux Mint before. Linux Mint 20 will be based on Ubuntu 20.04 LTS and that has pdfarranger.
