### ISSUE TITLE
 Linux mint 19 Cinnamon not booting after installing with UEFI bios 

### ISSUE THREAD

**Issue by jeroenst** [linuxmint/linuxmint#25]
Cinnamon Mint 19

When installing Linux Mint 19 on a pc with uefi boot enabled, the system won't boot after installation. Only switching to legacy boot mode makes the system work.

I did a manual partition setup with a / partition of 130gb and a swap partition of 10gb

**Comment by NikoKrause** [comment]
What's the output of:
```
dmesg | grep "EFI v"
```

**Comment by jeroenst** [comment]
No output is given because now I have booted in legacy mode.

**Comment by jeroenst** [comment]
dmesg | grep "EFI" gives: [    0.000000] ACPI: UEFI 0x000000008A6C7A78 000042 (v01                 00000000      00000000)

**Comment by jaszhix** [comment]
If you're using pascal-based Nvidia cards (gtx 10xx), you need to pass the `nomodeset` kernel flag with grub in UEFI mode. Press e on the compatible boot entry -> add ` nomodeset` after `quiet splash` with a space. Press F10. It will start in software rendering mode. After installing, hold shift on boot to get to grub, pass `nomodeset` again, then install the Nvidia driver.

**Comment by jeroenst** [comment]
I'm using the integrated graphics of an i5 7th generation cpu, no nvidea.

On facebook I was told this issue can occur when booting the usb bootable media in legacy mode instead of by uefi causing the installer to write disk in MBR instead of GPT.

**Comment by NikoKrause** [comment]
> When installing Linux Mint 19 on a pc with uefi boot enabled, the system won't boot after installation. Only switching to legacy boot mode makes the system work.

To me this sound like you installed Mint in legacy mode and not in efi mode.

**Comment by jeroenst** [comment]
I was in error, I didn't create a efi partition. When I did an automatic installation the efi partition was created. and the system boots.
