### ISSUE TITLE
Sleep does not work, immediately resumes from sleep but only blank screen

### ISSUE THREAD

**Issue by JLemur** [linuxmint/linuxmint#250]
I'm dual-booting my Lenovo Flex 14 ARR (Ryzen 7) with Mint 19.3 and Windows.  In Windows, the sleep function is working exactly as expected: when I put it to sleep, it stays asleep until I wake it up, and it resumes from sleep correctly.   But in Mint, sleep is not working.  Immediately after going to sleep, it resumes from sleep, but it is not functional.  The screen turns on to a blank black screen, and the backlit keyboard lights up.  Nothing I do gets it to resume to normal, it just stays on the blank black screen.  All I can do is long-press the power button to power it down.

I've attached the syslog excerpt relating to the issue, from first issuing the sleep order until long-pressing the power button.  Also attached is the inxi information. 
[syslog_failed_sleep.log](https://github.com/linuxmint/linuxmint/files/4587638/syslog_failed_sleep.log)
[inxi.log](https://github.com/linuxmint/linuxmint/files/4587639/inxi.log)

Possibly irrelevant, but for the record, this is a new installation of Mint 19.3.  When I first ran apt update and apt upgrade there was some warning about not having some amd gpu bin file.  I installed the AMD driver from https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux.  It all seemed to go fine.

**Comment by xenopeek** [comment]
Hope you already managed to solve this issue. It sounds like a power management (ACPI) issue, possibly between Linux kernel (which has most hardware drivers) and your hardware. If you're still having this issue I suggest to take help with [troubleshootaing](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) it from the [support forums.](https://forums.linuxmint.com/viewforum.php?f=49). Hopefully this can be solved by setting some kernel parameter or switching to a different kernel series.
