### ISSUE TITLE
Mint 19 Cinnamon: installation seems to hang but actually works

### ISSUE THREAD

**Issue by jeroenst** [linuxmint/linuxmint#26]
When installing linux mint 19 the installer at some point is not responding (I think it's creating partitions).

It should show a message like Creating Partitions, please wait...

**Comment by xenopeek** [comment]
I've done several installs of Linux Mint 19 (on SSD though) and can't recall having stumbled across something like this. It would have been great if this had been reported on the BETA so it could have been worked on then. Can I suggest you retest with Linux Mint 19.1 BETA (around November/December likely, it will be announced on https://blog.linuxmint.com/) so if it is still an issue then, it can be worked on then? As written this issue doesn't have enough information on it to work on. See also our [troubleshooting guide](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/).
