### ISSUE TITLE
[FATAL] Linux Mint 19.3, Visual bug, then crash while on Live USB.  Issue happens on both XCFE and Cinnamon

### ISSUE THREAD

**Issue by Goodgun123456789** [linuxmint/linuxmint#263]
I am currently testing a computer out with Linux Mint via live USB and am experiencing the following visual bug and then a system freeze (complete freeze, can't swap ttys).  The audio still works, so I believe it is a comparability issue with the graphics card.  The issue usually happens when running a program like Gparted, but has happened earlier.  

Link to image of computer screen after freeze:
https://transfer.sh/15FZFj/IMG_20200623_220614545_BURST000_COVER_TOP.jpg 

Steps to reproduce:
Have the following hardware specifications and use everything default for such a system:
AMD Phenom(tm) II X4 965 Processor (4 CPUs), ~3.4GHz
NVidia GeForce GTX 650 Ti BOOST
8 GB of Ram
Launch Linux Mint Via USB
open Firefox, go to some website like Youtube and play a video
install a program (I used youtube-dl for instance)
open GParted and try to make a change to the hard drive
Wait until visual bugs then crash proceed.  

Any requested information will be provided to the best of an ability, I would provide logs, but since everything is fine up to the point of crashing and once crashed the logs would be irrecoverable without something along the lines of SSH (and even then, if the OS is frozen I likely couldn't communicate with it) being used to retrieve them.

**Comment by xenopeek** [comment]
Suggest you take help from the [support forum](https://forums.linuxmint.com/) with further [troubleshooting](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) this observation to find the responsible component. If you can narrow down on the cause being a component developed or maintained by Linux Mint you can open a new issue here for the developers to work on.
