### ISSUE TITLE
Linux Mint 20 "Initramfs unpacking failed: Decoding failed"

### ISSUE THREAD

**Issue by jainkila** [linuxmint/linuxmint#268]
Linux Mint 20 installation media boot fails with error message "Initramfs unpacking failed: Decoding failed"

Same issue with Cinnamon & XFCE. Same issue when booting from USB stick and DVD-R. On the same desktop computer LM19.3 installation media and installed LM19.3 works ok.

Video of the issue
https://youtu.be/R0wAAvCXHyA

Hardware info
https://jainkila.kapsi.fi/temp/lshw.txt

**Comment by xenopeek** [comment]
The "Initramfs unpacking failed: Decoding failed" issue was found [during beta]( https://github.com/linuxmint/mint20-beta/issues/90) and is upstream. This isn't the cause of the system not booting. Seeing as you have a Nvidia GPU please try booting in compatibility mode. See the section "Solving freezes during the boot sequence" in the [release notes](https://linuxmint.com/rel_ulyana_cinnamon.php) for more explanation. If you need further help with [troubleshooting](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) make a new topic on the [Installation & Boot](https://forums.linuxmint.com/viewforum.php?f=46) support forum.
