### ISSUE TITLE
Can't access forums.linuxmint.com - "The connection has timed out"

### ISSUE THREAD

**Issue by Jackson1347** [linuxmint/linuxmint#271]
Haven't been able to access the forums for 3-4 days.  Running Firefox 78.0.1 on Linuxmint 19.3 on my primary machine, but also tried on old linux system using Mint 19.3 and still running Firefox 75.x, Windows 8.1 system running Firefox, Windows 10 system running Edge, Android system running Firefox, and Chromebook running Google something.  Only common element is all systems go through the same router, connected to Verizon Fios.  I can access Linuxmint.com, but when I try to drill down into blogs.linuxmint.com it times out also.  So main site is accessible, but sub-sites aren't reachable.  I spent an hour on the phone with Verizon support and the guy finally hung up on me, after trying many things behind the scenes.  I opened a chat that is accessible via linuxmint.com, and another kind person indicated that he was having the same problem.  Consensus of chat advice was to call my ISP, which unfortunately didn't work.  Mainly wondering if others are having the same problem, since it sounds like a Verizon problem to me.

**Comment by xenopeek** [comment]
Only Verizon customers are affected by this issue, mostly on the east coast of the US. Forums are up and working for others. As workaround till this is solved you can use a VPN or Tor Browser. There's a topic on the forums (I know…) from other affected users: https://forums.linuxmint.com/viewtopic.php?f=157&t=323736.
