### ISSUE TITLE
mint-meta-codecs Depends on chromium-codecs-ffmpeg-extra -> chromium-codecs-ffmpeg snap

### ISSUE THREAD

**Issue by daviddyess** [linuxmint/linuxmint#273]
Update Manager reports an update for the package `chromium-codecs-ffmpeg-extra` to be replaced by `chromium-codecs-ffmpeg snap`. Upon attempting to remove this package, Software Manager shows it is a dependency of `mint-meta-codecs=2020.06.19`.

`chromium-codecs-ffmpeg-extra` Update Changelog states:

* New upstream release: 83.0.4103.97
* Do not attempt to install the snap on systems where snapd isn't running
    (including chroots and WSL) (LP: #1882232)

**Comment by clefebvre** [comment]
Fixed.
