### ISSUE TITLE
LuckyBackup doesn't start as super user

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#277]
In Linux Mint MATE 20 (new install), I installed LuckyBackup package. I can start it from the Mint menu, as usual user. But when I start it from the Mint menu as super user (it's better to make backup), Linux asks me my password and after that, tries to start LuckyBackup (the mouse cursor becomes a rotating wheel). But LuckyBackup doesn't start. After 10-20 seconds, the mouse cursor becomes as usual.

![Capture du 2020-07-11 12-02-04](https://user-images.githubusercontent.com/3955499/87221786-09b71100-c36f-11ea-9063-b6c117bcbaae.png)

**Comment by xenopeek** [comment]
What happens when you run the associated command ```pkexec "/usr/bin/luckybackup"``` from the terminal?

**Comment by InfoLibre** [comment]
It asks my password in a small window and after typing it, the window closes and nothing else. In the terminal :

```
$ pkexec "/usr/bin/luckybackup"
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Abandon (core dumped)

```

**Comment by xenopeek** [comment]
There are a lot of hits when you search the internet for either qt.qpa error but nothing I can make sense of. I can't find what you would need to install to do to make it work.

Developer of LuckyBackup thinks this issue is solved with the version you have: http://luckybackup.sourceforge.net/bugs.html.  Suggest from that page to contact the developer. If the package is missing a dependency, report that to the package maintainers: https://launchpad.net/ubuntu/+source/luckybackup/+bugs.

**Comment by InfoLibre** [comment]
Thank you for these links.

The MATE menu is using this command (that does not work) :
![Capture du 2020-07-12 12-06-54](https://user-images.githubusercontent.com/3955499/87243782-f96b6880-c438-11ea-8a34-e1e1fe326e5b.png)

An in a terminal, this command works well :
`sudo -H luckybackup`

So, modifying the command in the menu would be indeed a solution. I will ask on https://launchpad.net/ubuntu/+source/luckybackup/+bugs if somebody can do it.

But as on http://luckybackup.sourceforge.net/index.html, the author says that the development of luckybackup is almost frozen and that this will affect future fixes of known bugs, . I will try to find another backup software that is as good good as luckybackup too.
