### ISSUE TITLE
Samba seems broken on Mint 19

### ISSUE THREAD

**Issue by jaszhix** [linuxmint/linuxmint#28]
Moved from https://github.com/linuxmint/Cinnamon/issues/7702, @CottonEaster wrote:
#
```
 * Cinnamon version (cinnamon --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19
 * 32 or 64 bit: 16

Filing this problem here because I cannot find a better place for it.
 ```

**Issue**

```
sudo samba-tool user create <username - redacted> <password - redacted>
ldb: unable to stat module /usr/lib/x86_64-linux-gnu/samba/ldb : No such file or directory
ERROR(<type 'exceptions.ValueError'>): Failed to add user '<redacted>':  - unable to parse dn string
  File "/usr/lib/python2.7/dist-packages/samba/netcmd/user.py", line 380, in run
    smartcard_required=smartcard_required)
  File "/usr/lib/python2.7/dist-packages/samba/samdb.py", line 361, in newuser
    dnsdomain = ldb.Dn(self, self.domain_dn()).canonical_str().replace("/", "")
```

Still, I have little idea of what I am doing with 'samba-tool user create' anyway; my Samba setup stopped working with Mint 19 and I thought that I may need to use this command (which I have not used before) to get things working.

**Comment by jaszhix** [comment]
@CottonEaster Check the output of

 - `systemctl status smbd`
 - `testparm`

Use `sudo smbpasswd -a <username>` to create a samba user, it will prompt for the password. Edit /etc/samba/smb.conf to make configuration changes. Check the [man page](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html). Between changes run `sudo systemctl restart smbd`. Samba is tricky sometimes, but in most cases its usually bad share configs. e.g. if you use `valid users` under the share block, your unix, samba, and windows usernames all need to match. If unix and samba usernames don't match you have to create a username map, so its simpler to keep it all matching. Also, most gui tools are unmaintained, editing smb.conf is your best bet. Good luck!

**Comment by CottonEaster** [comment]
Thank you,  jaszhix. However, I was aware of all that (though you do put it well) and I thought (1) the fail I quoted was a bad, messy one and so not to be expected even from misconfiguration, (2) that the problem might arise from something that had changed with Mint 19.
