### ISSUE TITLE
No more close button in Disks window

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#280]
It's impossible to quit Disks because there's no more button to close the window. I changed the place where window buttons are placed (left and right of the window) but the buttons always stay at the left of the window (first bug) and in both cases, there's no more close button (second bug) :

![Capture du 2020-07-14 10-38-32](https://user-images.githubusercontent.com/3955499/87404816-e84c6400-c5be-11ea-870e-8f778e17eccf.png)

Linux Mint MATE 20
gnome-disk-utility 3.36.1
UDisks 2.8.4 (build with 2.8.4)

**Comment by mtwebster** [comment]
Grab that little vertical line next to the icon whose menu you have popped up, and drag it right.  This is a bug in Disks - https://gitlab.gnome.org/GNOME/gnome-disk-utility/-/issues/148.

The inability to change which side the buttons is on is I think a limitation in the configuration of these buttons in mate-control-center - it only lets you configure traditional window controls, not the new-style titlebars like Disk uses.  To modify it, see:

https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-decoration-layout
and use:
```
gsettings set org.mate.interface gtk-decoration-layout "menu:minimize,maximize,close"
```
or however you prefer the layout.

**Comment by InfoLibre** [comment]
Thank you for your help. For the left/right buttons, I will let them at left.

**Comment by smurphos** [comment]
It might be possible to workaround the issue in the theme. This issue is apparent with Mint Y, but not Mint X. It is apparent with Adwaita (so is likely a genuine Disks bug). Of third party themes tried it is apparent with Adapta, but not Cinnamox.
