### ISSUE TITLE
Misc. Mint 20 issues

### ISSUE THREAD

**Issue by coolhandluke57** [linuxmint/linuxmint#281]
1. Update from 19.3 to 20.0 requires a specific Java version to be installed. Does not recognize Oracle Java which I need for certain programs to work. Installing required Java allows update, but overrides Oracle Java dependencies preventing those programs from operating under 20.0.

2. Standalone Adobe Flash Player 32,0,0,303 (debugger) runs choppy then becomes unresponsive when multiple instances are open at the same time. Have had as many as nine players open simultaneously in 19.3 without any issues. Mint 20 shows performance drop-off with as few as two.

**Comment by xenopeek** [comment]
Sorry you're having these issue. I assume/hope you managed to re-install Oracle Java? Linux Mint 20 comes with LibreOffice installed with SQL support, which requires Java. If Oracle Java isn't installed through the package manager or doesn't provide the required Java packages it will need removing of the LibreOffice SQL to remove the other Java from your system. That shouldn't impact you unless you're using SQL import in Base or Calc. If you need further help with removing SQL support for LibreOffice and the OpenJRE Java you can ask on the [support forums](https://forums.linuxmint.com/viewforum.php?f=47).

For Adobe Flash Player I wouldn't know. IIRC it's EOL end this year. If you still need it you can ask on the support forums if any can help with [troubleshooting](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) the cause.
