### ISSUE TITLE
Panel options in mate-tweak not working

### ISSUE THREAD

**Issue by cbv-wizzdom** [linuxmint/linuxmint#285]
This issue is only seen in the linuxmint version of mate-tweak. The Ubuntu MATE version has no problems.

On opening the Panel option of  mate-tweak, the "Panels" layout is blank and the "Panels Features" items are unusable except for "Enable keyboard LED".
On trying to select a layout, the layouts shown are: Fedora, GNOME2, Linux Mint and OpenSUSE. Whichever of these is selected results in the panel moving from the bottom to the top of the screen and no change to the layout.
Using the "Reset Panel" option from the panel's right-click menu moves the panel to the bottom, gives different icons and the error message "The panel encountered a problem loading "MateMenuAppletFactory::MateMenu Applet".

Starting mate-tweak from the terminal and attempting to change the panel layout gives the following:

user@cbv-MATE-20:~$ mate-tweak
Window Manager is: marco
System installed layouts: 
['fedora', 'default', 'linuxmint', 'opensuse']
Current layout: opensuse
/usr/bin/mate-tweak:773: PyGTKDeprecationWarning: The "buttons" argument must be a Gtk.ButtonsType enum value. Please use the "add_buttons" method for adding buttons. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  dialog = Gtk.Dialog(title, None, Gtk.DialogFlags.MODAL | Gtk.DialogFlags.DESTROY_WITH_PARENT,
/usr/bin/mate-tweak:773: PyGTKDeprecationWarning: The "flags" argument for dialog construction is deprecated. Please use initializer keywords: modal=True and/or destroy_with_parent=True. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  dialog = Gtk.Dialog(title, None, Gtk.DialogFlags.MODAL | Gtk.DialogFlags.DESTROY_WITH_PARENT,
/usr/bin/mate-tweak:779: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  label = Gtk.Label(text)
Switching to: linuxmint
Traceback (most recent call last):
  File "/usr/bin/mate-tweak", line 1095, in combo_fallback
    self.additional_tweaks(schema, key, value[1])
  File "/usr/bin/mate-tweak", line 1079, in additional_tweaks
    self.replace_panel_layout(panel_layout)
  File "/usr/bin/mate-tweak", line 882, in replace_panel_layout
    self.enable_applets()
  File "/usr/bin/mate-tweak", line 618, in enable_applets
    pid = subprocess.Popen(['mate-volume-control-applet'], stdout=DEVNULL, stderr=DEVNULL).pid
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mate-volume-control-applet'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_mate-tweak.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/mate-tweak", line 1095, in combo_fallback
    self.additional_tweaks(schema, key, value[1])
  File "/usr/bin/mate-tweak", line 1079, in additional_tweaks
    self.replace_panel_layout(panel_layout)
  File "/usr/bin/mate-tweak", line 882, in replace_panel_layout
    self.enable_applets()
  File "/usr/bin/mate-tweak", line 618, in enable_applets
    pid = subprocess.Popen(['mate-volume-control-applet'], stdout=DEVNULL, stderr=DEVNULL).pid
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mate-volume-control-applet'

**Comment by xenopeek** [comment]
> This issue is only seen in the linuxmint version of mate-tweak.

mate-tweak is a fork of mintdesktop. On Linux Mint MATE you'll find mintdesktop is installed (Desktop Settings in your menu). Use that.

mate-tweak is [not](http://packages.linuxmint.com/search.php?release=any&section=any&keyword=mate-tweak) included in the Linux Mint repository. If you install it you do so from the Ubuntu package base repository which is possibly for a different MATE version and causes this error.

**Comment by cbv-wizzdom** [comment]
I installed mate-tweak as it was available in the repository as indicated in "official-package-repositories.list". I assumed that if it was listed, it would work. mintdesktop does not have the options I want - the ability to save a custom panel configuration and set it as the default.
