### ISSUE TITLE
Spurious/outdated packages installed on mint-20 new installs

### ISSUE THREAD

**Issue by SimonIremonger** [linuxmint/linuxmint#290]
FAO Clem, xenopeek,  et. al.

I provide helpful notes here on outdated/depracated packages that mint-20 is somehow or other getting installed on 'new' installs (at least, as tested with Cinnamon fully-updated!), should be cleared up for mint 20.1 imho !
Some must be down to hints to ubiquity / installer config, mintreport auto-installation, others may be dependencies outside the mint-ecosystem.
Some may be due to older nemo/cinnamon dependencies that have since been 'fixed' already.

Firstly, Python2 group
=================

- [ ] python-cairo
- [ ] python-gi
- [ ] python-gobject-2
- [ ] python-xdg
- [ ] python2
- [ ] python2-minimal
- [ ] python2.7
- [ ] python2.7-minimal
- [ ] libpython2-stdlib
- [ ] libpython2.7-minimal
- [ ] libpython2.7-stdlib

All the above can be happily removed from mint20, but are for some-reason getting auto-installed anyway [grr!].
Ubuntu 20.04 intentionally without python2, mint20 regresses from this.  A few 20.04 installable packages still depend on python2.
NB: There are 'python-is-python3' 'python-is-python2' special packages available where needed, too!.  I think this may warrant mention in the 20.1 release-notes, in any case we shouldn't be including python2 out of the box at all, already deprecated end-of-the-line and likely not to be in 22.04 at all.

Secondly, deprecated transitional packages are installed, can be immediately removed:-
==================================================================
- [ ] e2fslibs
- [ ] gnome-orca
- [ ] libreoffice-ogltrans
- [ ] libreoffice-pdfimport
- [ ] libreoffice-avmedia-backend-gstreamer
- [ ] openoffice.org-hyphenation
- [ ] system-config-printer-gnome
- [ ] cryptsetup-run
- [ ] dnsutils
- [ ] gnome-themes-standard

Thirdly, older libraries again not needed, can be removed straight away.
======================
- [ ] libgtkmm-2.4-1v5
- [ ] libllvm9

Fourthly, miscellaneous transitional
==================
- [ ] thunderbird-locale-en-gb  [replaced with thunderbird-locale-en]
- [ ] thunderbird-locale-en-us  [replaced with thunderbird-locale-en]
- [ ] libservlet3.1-java  [transitional dep, part of libreoffice??]

Fifthly, misc reports from 'deborphan', maybe important plugins, less likely to warrant removal.
===========================
libproxy1-plugin-gsettings
libproxy1-plugin-networkmanager
gstreamer1.0-clutter-3.0
gstreamer1.0-packagekit
gir1.2-dbusmenu-glib-0.4
gir1.2-dee-1.0
gir1.2-gtop-2.0
gir1.2-gudev-1.0
gir1.2-ibus-1.0

Hope these can at least all be considered/looked-at for 20.1 .
With thanks,

**Comment by iKarith** [comment]
Might I suggest editing your original ticket post above changing those package name lists to checkboxes so that someone (hi!) can go down the list and look for things that pull them in and check them off the list? They're going to appear in various places and some of them have already been purged.

For example python-cairo is manually installed by ubuiquity to resolve some dependency in LM20. I don't know what off the top of my head, but the only current dependency is pychess. Set it to automatic (which you'll have to do yourself) and it'll uninstall if you don't have pychess installed.

This is low-hanging fruit. Any volunteer can look into these, find which are still used, and PR the usually trivial fixes that remove them.

**Comment by SimonIremonger** [comment]
> Might I suggest editing your original ticket post above changing those package name lists to checkboxes so that someone (hi!) 

Think I've done this for you!  Can this be assigned or handled...  I guess key test will be to look at the mint 20.1 beta / test images when they arrive...

**Comment by iKarith** [comment]
I'm not part of the Mint team, I'm just a guy who's willing to submit patches when I can. Looks like some of these have already been fixed?

**Comment by SimonIremonger** [comment]
>  Looks like some of these have already been fixed?
Quite likely/possible, have you any evidence  [LINKS to ubiquiti configs and that sort of thing?] ?
Clearly the above can be 'checked on' when mint 20.1 testing/beta iso's come out, in any case.

**Comment by clefebvre** [comment]
Thanks @SimonIremonger, I couldn't tackle "all" of them (some are dependencies from other packages), but it did help cleaning up a lot.

**Comment by SimonIremonger** [comment]
Can confirm all 3 groups at the top are fixed/removed in current mint 20.1 cinnamon test images.
