### ISSUE TITLE
Linux Mint 20 did not follow upstream usrmerge

### ISSUE THREAD

**Issue by florisvdh** [linuxmint/linuxmint#294]
Both Debian and Ubuntu have shifted to the so called "merged `/usr` directories scheme, i.e. the `/{bin,sbin,lib}/` directories becoming symbolic links to `/usr/{bin,sbin,lib}/`". Quite a lot of others did it as well, e.g. Arch and Fedora.

I wondered why this is not done in Linux Mint 20? Is it planned to implement this?

A general discussion of the topic can be found here: https://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge/ and some info is in the `usrmerge` package readme: https://salsa.debian.org/md/usrmerge/raw/master/debian/README.Debian

Some specific information on how I encountered a problem with not having the usrmerge in Mint 20 + my workaround:

- I discovered this difference between Ubuntu and Mint after I installed a debian package for R for Ubuntu 20.04, from RStudio's own server (the links can be found [here](https://docs.rstudio.com/resources/install-r/#download-and-install-r)). _[Note, I use these builds because they are installed in version-specific folders (under `/opt`), allowing to have several versions side-by-side - which I need. The standard package in the Ubuntu repo or on the [CRAN repositories for Ubuntu](https://cran.r-project.org/bin/linux/ubuntu/) is `r-base`, which installs as `/usr/bin/R`.]_ However, it seems that these builds contain (in the executable `R` file) a hard-coded path to `sed` - `/usr/bin/sed` - which is indeed where it is found since Ubuntu 19.04 because of the usrmerge (`which sed` says `/usr/bin/sed`). However, while working in Mint with RStudio's R-build for Ubuntu, when some R package uses this path, it errors because in Mint, `/bin` and `/usr/bin` are still separate and `sed` is in `/bin`.
- So, in Mint I needed to manually add a symlink `/usr/bin/sed` directing to `/bin/sed`, in order to circumvent this problem. I saw warnings on similar things for the `tar` binary, so added this too.

I'm no Linux expert and I don't know of reasons to not follow the usrmerge, but it seems to me that more of this sort of incompatibilities may be encountered on Mint when trying to install effectively 'Ubuntu-compatible' deb packages in the future.

Thanks for shedding light on this, I really like Linux Mint and I have been using it since quite some years.

**Comment by clefebvre** [comment]
Did you install usrmerge in Ubuntu? Afaik it's not installed by default. There shouldn't be any difference in that respect between Mint and Ubuntu.

**Comment by florisvdh** [comment]
No, Ubuntu has the merged paths by default (see e.g. in a live session).

**Comment by florisvdh** [comment]
@clefebvre This post provides interesting leads: https://askubuntu.com/a/1248543

Also, it seems it is not implemented in upgrades, only in the fresh installs.

**Comment by clefebvre** [comment]
Confirmed

![image](https://user-images.githubusercontent.com/1138515/91837102-9d0c1480-ec43-11ea-9e4d-822bc39453b6.png)

**Comment by clefebvre** [comment]
Alright, it's done during the ISO build: http://launchpadlibrarian.net/397393145/live-build_3.0~a57-1ubuntu36_3.0~a57-1ubuntu37.diff.gz.

```
diff -Nru live-build-3.0~a57/debian/changelog live-build-3.0~a57/debian/changelog
--- live-build-3.0~a57/debian/changelog	2018-06-27 04:39:47.000000000 +0000
+++ live-build-3.0~a57/debian/changelog	2018-11-12 20:11:36.000000000 +0000
@@ -1,3 +1,10 @@
+live-build (3.0~a57-1ubuntu37) disco; urgency=medium
+
+  * Cherrypick Debian's patches for handling binary/chroot includes with
+    merged-usr.
+
+ -- Dimitri John Ledkov <xnox@ubuntu.com>  Mon, 12 Nov 2018 20:11:36 +0000
+
 live-build (3.0~a57-1ubuntu36) cosmic; urgency=medium
 
   * debian/control: Need to depend on initramfs-tools which isn't in chroots.
diff -Nru live-build-3.0~a57/debian/patches/0001-Handle-includes.chroot-files-installed-over-symlinke.patch live-build-3.0~a57/debian/patches/0001-Handle-includes.chroot-files-installed-over-symlinke.patch
--- live-build-3.0~a57/debian/patches/0001-Handle-includes.chroot-files-installed-over-symlinke.patch	1970-01-01 00:00:00.000000000 +0000
+++ live-build-3.0~a57/debian/patches/0001-Handle-includes.chroot-files-installed-over-symlinke.patch	2018-11-12 20:11:36.000000000 +0000
@@ -0,0 +1,57 @@
+From 52908422880f8d5cfa18c577d4138d5449af37f6 Mon Sep 17 00:00:00 2001
+From: =?UTF-8?q?Rapha=C3=ABl=20Hertzog?= <hertzog@debian.org>
+Date: Fri, 27 Jul 2018 09:46:55 +0200
+Subject: [PATCH] Handle includes.chroot files installed over symlinked
+ directories
+
+With the merged /usr feature now enabled in debootstrap, we have
+/bin and /lib which are symlinks to /usr/bin and /usr/lib. If
+the live-build configuration provides files in
+config/includes.chroot/lib/ or config/includes.chroot/bin/ then
+lb chroot_includes will replace the /lib or /bin symlink with real
+directories having only the content provided in chroot.includes and
+problems will follow... the build will usually fail later with a
+cryptic error message (for example a hook failing to execute
+/usr/bin/env).
+
+Work around the issue by creating a tarball of the files to install
+and by unpacking that tarball from within the chroot with appropriate
+options.
+---
+ xnox: adapted for Ubuntu's livebuild
+
+ scripts/build/chroot_includes | 6 +++++-
+ 1 file changed, 5 insertions(+), 1 deletion(-)
+
+--- a/scripts/build/lb_binary_includes
++++ b/scripts/build/lb_binary_includes
+@@ -42,8 +42,12 @@
+ then
+ 	# Copying includes
+ 	cd config/includes.binary
+-	find . | cpio -dmpu --no-preserve-owner "${OLDPWD}"/binary
++	Echo_message "Creating a tarball with files from includes.binary..."
++	tar cf "${OLDPWD}"/binary/includes.binary.tar .
+ 	cd "${OLDPWD}"
++	Echo_message "Extracting the tarball in the chroot..."
++	tar -C binary -xvf binary/includes.binary.tar --no-same-owner --keep-directory-symlink --overwrite
++	rm binary/includes.binary.tar
+ 
+ 	# Removing symlinks
+ 	case "${LB_BINARY_IMAGES}" in
+--- a/scripts/build/lb_chroot_includes
++++ b/scripts/build/lb_chroot_includes
+@@ -42,8 +42,12 @@
+ then
+ 	# Copying includes
+ 	cd config/includes.chroot
+-	find . | cpio -dmpu --no-preserve-owner "${OLDPWD}"/chroot
++	Echo_message "Creating a tarball with files from includes.chroot..."
++	tar cf "${OLDPWD}"/chroot/includes.chroot.tar .
+ 	cd "${OLDPWD}"
++	Echo_message "Extracting the tarball in the chroot..."
++	Chroot chroot "tar -xvf includes.chroot.tar --no-same-owner --keep-directory-symlink --overwrite"
++	rm chroot/includes.chroot.tar
+ 
+ 	# Creating stage file
+ 	Create_stagefile .build/chroot_includes
diff -Nru live-build-3.0~a57/debian/patches/series live-build-3.0~a57/debian/patches/series
--- live-build-3.0~a57/debian/patches/series	2018-06-26 23:06:31.000000000 +0000
+++ live-build-3.0~a57/debian/patches/series	2018-11-12 19:50:52.000000000 +0000
@@ -38,3 +38,4 @@
 no-apt-key.patch
 late-resolv.conf-symlink.patch
 ubuntu-initramfs-handling.patch
+0001-Handle-includes.chroot-files-installed-over-symlinke.patch

```

**Comment by clefebvre** [comment]
I'll add that to the roadmap so we can consider doing the same for 20.1.

**Comment by florisvdh** [comment]
Thanks so much for the consideration :+1: , looking forward to it!
Loving Mint...

**Comment by noloader** [comment]
>  However, it seems that these builds contain (in the executable R file) a hard-coded path to sed - /usr/bin/sed - which is indeed where it is found since Ubuntu 19.04 because of the usrmerge (which sed says /usr/bin/sed). However, while working in Mint with RStudio's R-build for Ubuntu, when some R package uses this path, it errors because in Mint, /bin and /usr/bin are still separate and sed is in /bin.

I hope I am not wandering off-topic, but this is a R problem. It should not hard code `/usr/bin/sed`. 

The user provides the path to find binaries through the `PATH` variable. R should not ignore the user's `PATH` preferences. Consider, what happens if a user builds `sed` from sources to fix a bug, and installs it in `/usr/local/bin`?

R will break on other OSes. For example, to get a non-anemic `sed` on Solaris, R will need to use the one in `/usr/gnu/bin`, `/usr/sfw/bin` or `/usr/xpg4/bin`.
