### ISSUE TITLE
FONT problem on mint 18.3

### ISSUE THREAD

**Issue by ijash** [linuxmint/linuxmint#3]
```
 * Cinnamon version (Cinnamon 3.6.7)
 * Distribution - (Mint 18.3)
 * Graphics hardware: Nvidia GTX 950
 * 64 bit
extra info: https://git.io/vAIjE
have tested both in virtual box and real pc
 ```

**Steps to reproduce**
fresh install 18.3
and open font setting

**Expected behaviour**
no squared symbol/code, font rendered exactly the font supposed to be

**Other information**
look at the screenshot.

![screenshot from 2018-02-10 02-38-43](https://user-images.githubusercontent.com/30673286/36046732-81834b06-0e0c-11e8-857a-61b9849cf2c7.png)

it's not just noto, mostly non-english fonts such as Tamil, Arab, Hebrew, Thai etc..

so, can't i just instal english-only linux mint?

**Comment by xenopeek** [comment]
Near the bottom of your screenshot you can see the edit box with the example phrase that is rendered with each font in the list of fonts. The Noto Sans fonts for Cham and Cherokee languages, as shown in your screenshot, don't include glyphs for latin characters. You'll find that is the case for all Noto Sans fonts for non-latin languages.

This isn't a Linux Mint issue but rather an incorrect expectation, that Noto Sans fonts for non-latin languages would include glyps for latin characters. For such issues please use the forums in future to confirm your expectation is correct when you have some observation. There are many more people helping out on the forums than we have developers here. Please refer to our troubleshooting guide for more info https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/. 

If you do want to see what glyphs are in Noto Sans fonts for non-latin languages like Cham or Cherokee, you would either replace the example phrase with one using characters from that language or you can browse to the fonts here https://www.google.com/get/noto/ which shows you some specimens from each font's glyphs.
