### ISSUE TITLE
Mint 19 Cinnamon: can't hybernate on low battery

### ISSUE THREAD

**Issue by jeroenst** [linuxmint/linuxmint#30]
When linux Mint 19 Cinnamon is on low battery the only options is to do nothing or to shutdown. Both options cause to lose data when unsaved documents are open.

Linux mint should default hybernate when battery is low assuring any unsaved data is remained.

**Comment by jeroenst** [comment]
In addition, there is no option to hybernate anywhere at the power manager setting..

Possible caused because there is no swap device when linux mint is installed (see bug https://github.com/linuxmint/linuxmint/issues/34)

Also when adding a large enough swap space the hybernation options are still not displayed in the power manager.

**Comment by xenopeek** [comment]
See the Linux Mint 19 release notes. Assuming you have home directory encryption, there is a known issue with swap that you have to manually correct post-install as explained in the release notes. This known error may possibly not have been in the release notes at the date you reported above.

**Comment by jeroenst** [comment]
Doing things by hand isn't really user friendly what mint supposed to be imo.

**Comment by iHad169** [comment]
xenopeek talk this:
[Linux Mint 19 release notes](https://www.linuxmint.com/rel_tara_cinnamon.php)
[[FIX] no swap on fresh LM19 install with home directory encryption](https://forums.linuxmint.com/viewtopic.php?f=90&t=274157)

xenopeek. Please write the LINK.
People do not know you talk about.
