### ISSUE TITLE
[Feature Request] Choose software to install on OS Installation

### ISSUE THREAD

**Issue by trymeouteh** [linuxmint/linuxmint#302]
I would like to suggest a feature in the Install Linux Mint app which is an additional step which will ask the user to install all recommended software (default setting) or choose what applications to install.

However this will only allow you to choose GUI applications which you would normally find in the menu. This way users can choose weather to install LibreOffice, Rhythmbox Thunderbird, etc. I do believe some apps should not be optional and be made mandatory such as the terminal app, file explorer, basic text editor, setting app(s) and any app that is needed for Linux Mint distro to work and any apps needed for the desktop environment to work.

This will allow users to not have to install software they do not need when installing Linux Mint.

**Comment by xenopeek** [comment]
Thanks for making a suggestion for Linux Mint. See our [workflow](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html#why-are-ideas-and-feature-requests-closed) for feature request for why this is closed here.
