### ISSUE TITLE
Shutting down and Restarting takes over a minute

### ISSUE THREAD

**Issue by kameshkotwani** [linuxmint/linuxmint#304]
**Issue**
There is some process which is delaying the shutdown and restart process. While shutting down, there is a message in log, "waiting for process crond" and it takes over a minute to respond.

**Steps to reproduce**

- Update your linux mint to latest kernel.

- Shut down the OS.

**Expected behaviour**
The laptop/desktop should shutdown within 10-15 seconds.

**Other information**
I have attached my laptop info and also the photo of the log where the shutdown gets stuck for over a minute.
![cinnamon-issue](https://user-images.githubusercontent.com/36355951/94828480-24a59880-0427-11eb-9574-71776408673d.png)
![1601565423502](https://user-images.githubusercontent.com/36355951/94828822-7fd78b00-0427-11eb-83f7-72c37460b807.jpg)

**Comment by xenopeek** [comment]
I suspect this is a remnant of LM19.3 or something previously installed or configured yourself. I'm on a clean LM20 install with the same kernel and have no system shutdown waiting for crond. There is no crond process or even crond file on my system. I do have a cron process running, that's started by systemd cron.service.

Does `pgrep crond` return the PID of a crond process running? Does `locate crond` find any crond files? Then that might be something to uninstall. If locate found any files, run `dpkg -S /path/to/a/crond/file` to check from which package it was installed.

If locate didn't find any crond files, check if `systemctl status cron` provides any clues.

**Comment by kameshkotwani** [comment]
Unfortunately, it has not fixed the issue. When I am writing pgrep crond I get a process ID I have attached the commands mentioned above, let me know if there is something I can do about it.
![error](https://user-images.githubusercontent.com/36355951/96218170-d4d7dd00-0fa1-11eb-861b-730c16b48d38.png)

**Comment by xenopeek** [comment]
Run the command instead as `pgrep -a crond` which also outputs the command line of the process. That should give you the path to the executable. Then run `dpkg -S` on that path.

**Comment by kameshkotwani** [comment]
Still, there is no path being showed up.

![crond-ii](https://user-images.githubusercontent.com/36355951/96538524-5a1b0480-12b6-11eb-9001-5089fd108d2e.png)
