### ISSUE TITLE
Cinnamon doesn't respect screen rotation sensor orientation (60-sensor.hwdb)

### ISSUE THREAD

**Issue by leigh123linux** [linuxmint/linuxmint#31]
@SethosII commented on [Sat Jul 07 2018](https://github.com/linuxmint/Cinnamon/issues/7708)

```
Cinnamon 3.8.7
Linux Mint 19
Intel HD 520 driver=i915
64 bit
 ```

**Issue**

I have a Lenovo Yoga 11e 3rd Gen where the accelerometer readings need to be rotated by 90°. This line in the 60-sensor.hwdb file should take care of this (https://github.com/systemd/systemd/blob/25ea58d37385af27301b7ad25e985eb15f421614/hwdb/60-sensor.hwdb#L256) but the screen orientation is still wrong by 90° degrees with automatic screen rotation activated. I have no other device to test, but I think others devices with non-default accelerometer readings might face the same issue.

**Steps to reproduce**

Activate automatic screen rotation. Screen rotation is off by 90°.

**Expected behaviour**

The screen orientation should be upright with automatic screen rotation activated.

**Comment by leigh123linux** [comment]
This isn't something that can be fixed within cinnamon code.

**Comment by clefebvre** [comment]
does the same happen in GNOME?

**Comment by SethosII** [comment]
@clefebvre I installed Gnome and the same happens there too.

**Comment by Tuxman2** [comment]
@leigh123linux: I have the same problem with Linux Mint 19.1 and Cinnamon 4.0. Automatic screen rotation activated. My issue is : When I tilted the screen to the left or to the right (90°), the display is inverted (taskbar in the top of the screen and desktop icons to the botttom). In normal mode or in 360° mode it is OK.

**Comment by xenopeek** [comment]
As the same happens on Gnome this doesn't look to be fixable in Cinnamon; would need more troubleshooting to find responsible component. The support forums can also be used for that, to get input from more users. For now closing this issue.

**Comment by ovari** [comment]
Screen orientation is always out be 90° on an ASUS VivoBook 12 Touchscreen 2-in-1 laptop with Linux Mint 19.3 Cinnamon and Ubuntu 20.04 beta. When the laptop is rotated 90°, the screen rotates again to remain 90° out of sync.

Can you please paste a link to the discussion in the forums?

Thank you

**Comment by SethosII** [comment]
As a side note: the orientation of touch input is not moved at all also when the screen actually gets rotated.
