### ISSUE TITLE
Feature request : Geany instead of Xed

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#313]
Xed is a very good text editor but Geany is really better than Xed.
Replacing Xed by Geany would be perhaps interesting.

**Comment by xenopeek** [comment]
Thanks for making a suggestion for Linux Mint. See the [workflow](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html#why-are-ideas-and-feature-requests-closed) for feature request as to why this is being closed here.
