### ISSUE TITLE
Vcdimager plug-in can't be enabled in Brasero

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#315]
Linux Mint 20 Cinnamon
Brasero 3.12.2

Vcdimager plug-in can't be enabled in Brasero. Could someone add in LM the patch proposed on https://gitlab.gnome.org/GNOME/brasero/-/issues/343 ?

**Comment by xenopeek** [comment]
Those packages aren't maintained by Linux Mint but upstream in Ubuntu 20.04 package base repository.

You can check from where a package is with command `apt policy <package name>` or by checking the repository online: if it's not found in http://packages.linuxmint.com/ it's not a package maintained by Linux Mint and you will likely find it in https://packages.ubuntu.com/ unless you installed the package from a 3rd party repository you added. You can use this info and the guide on https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/where.html to report such issues in the right place on first try.
