### ISSUE TITLE
Ubiquity : UEFI WIN95 FAT32 partition type doesn't appear in the partitionning confirmation message

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#316]
Linux Mint 20 Cinnamon.

I chose "Clear disk and install Linux Mint" :

![84592426-ebc8c000-ae45-11ea-9c4e-42b425c36513](https://user-images.githubusercontent.com/3955499/97201403-b3050400-17b2-11eb-8e2f-78d5925901d9.png)

In the confirmation message, the type of the partition is empty :

![84592439-04d17100-ae46-11ea-8ead-f9c89dee427b](https://user-images.githubusercontent.com/3955499/97201417-b7312180-17b2-11eb-8667-fb5107004b7c.png)

**Comment by SimonIremonger** [comment]
> Linux Mint 20 Cinnamon.
> I chose "Clear disk and install Linux Mint" :
> In the confirmation message, the type of the partition is empty :

Can you confirm if this was an actual UEFI install, or a Legacy install where bug #312 came into play ?

**Comment by InfoLibre** [comment]
It were installations in a VirtualBox VM and on many computers, old and new.

**Comment by SimonIremonger** [comment]
OK wel VirtualBox defaults to legacy-BIOS (not UEFI) booting so this defintely could be related to bug 312 linked above...

**Comment by InfoLibre** [comment]
Partition type ESP (https://en.wikipedia.org/wiki/EFI_system_partition) is now displayed in Linux Mint 21.2:

![installation Linux Mint_9](https://github.com/linuxmint/linuxmint/assets/3955499/dcb6688c-34fe-4117-a2b1-7679aff0f4dc)

Then I suppose this bug is solved now.
