### ISSUE TITLE
Make latest Thunderbird available in Mint 20.x?

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/linuxmint#332]
Dear Mint Team, 

is it possible to make your own Thunderbird 78 available in Linux Mint 20.x? It is already included in LMDE 4. It would be great if the user can choose between the Ubuntu version (68.10) and the Mint version (78.x).

**Comment by xenopeek** [comment]
This isn't something that can be tackled during beta bug squashing so moved this here.

**Comment by SimonIremonger** [comment]
@jakoblm  This was (eventually) fixed by Ubuntu at least for focal20.04 (upstream of mint20).
Please close this bug on linuxmint as this is clearly fixed already.
