### ISSUE TITLE
Feature request : using OpenPrinting CUPS instead of Apple CUPS

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#335]
Apple doesn't support anymore CUPS. The project is now maintained by OpenPrinting. Could you use it in LM ?

https://openprinting.github.io/projects/00-cups/
https://openprinting.github.io/projects/01-cups-filters/
And for IPP Everywhere : https://github.com/michaelrsweet/pappl

**Comment by InfoLibre** [comment]
https://www.muylinux.com/2021/05/18/apple-cede-cups-openprinting/

**Comment by xenopeek** [comment]
Ubuntu 21.04 and newer already use OpenPrinting CUPS: https://packages.ubuntu.com/hirsute/cups. As such Linux Mint 21 next year will be using this. (As will LMDE 5 as Debian 11 also already uses it.) For Linux Mint 19.x and 20.x these use the CUPS version from their package base and that is supported for duration of their lifetime.
