### ISSUE TITLE
Why is ureadahead removed from LM20? This makes boot process very slow!

### ISSUE THREAD

**Issue by cptX** [linuxmint/linuxmint#337]
Recently I have upgraded my linux mint to version 20. I'm using spinning Hard disks, and I noticed significantly longer boot times. I researched further and realized that ureadahead is not available and installed anymore.
In previous linux mint 19.3 I made experiments with and without ureadahead and had 20secs difference!!! (1min 17s boot time with ureadahead and 1min 37s without). Ureadahead was installed by default and gave a great advantage to the system!

I would like to experiment with ureadahead in LM20 too, but the package is not available! Why is ureadahead removed from Linux mint 20? Now booting is significantly slower! I would like this package to be available for all of us who still are using spinning disks and need it!

**Comment by xenopeek** [comment]
ureadahead was removed from upsteam and therefor no longer available. It's only available on Linux Mint 19.3 and earlier.

**Comment by cptX** [comment]
Can you please guide me how can I compile and install this package myself in Linux Mint 20?

**Comment by xenopeek** [comment]
For support with Linux Mint please use the forums as linked above.
