### ISSUE TITLE
Sound working, but when headphones are plugged in only left or right side works

### ISSUE THREAD

**Issue by PrintfvsCout** [linuxmint/linuxmint#338]
I have this weird issue which often happens it is one of the most annoying thing I have ever experienced. So when I plug my headphones there is sound on both sides normally sometimes, sometimes the right side only works sometimes the left side. And it stays like that for days until it randomly decides it wants to work. Restart does not fix it, it is so random. I have looked at driver updates, kernel updates, alsaudio, pulse audio and other things I can't even remember.
But everything works fine without headphones. And yes I have tested multiple headphones, I have dual boot with Win10 and yes my jack port works good with Win10

Dell Laptop Inspiron 5558
Linux Mint 20 Cinnamon version 4.6.7.
Linux Kernel 5.4.0-58-generic
CPU Intel© Core™ i3-5005U CPU @ 2.00GHz × 2

**Comment by xenopeek** [comment]
At first this sounds like an issue with the headphone jack not correctly plugged in but if — without touching the jack — it works on Win10 after a reboot that makes this sound like a hardware driver issue, possibly. That might be fixable by installing a newer Linux kernel or setting some kernel parameter.

Not a bug that Mint developers can fix for you so if you need further help with this I suggest to make a new topic for this on the support forums: https://forums.linuxmint.com/viewforum.php?f=48. You'll need to register an account before you can post there. And when you post please first open System Reports from your menu, go to the System Information tab in the left sidebar and there click the Copy button to copy your system information. Include that in your new topic so basic hardware information (like your audio chip & driver) are included and hopefully the resident audio guru's can help you solve it.
