### ISSUE TITLE
Mint 19 Cinnamon: doesn't create swap device on install

### ISSUE THREAD

**Issue by jeroenst** [linuxmint/linuxmint#34]
Linux mint 19 doesn't create a swap device on install which causes hybernation not to be available and also this gives errors with for example update-initramfs: update-initramfs: 

Generating /boot/initrd.img-4.15.0-24-generic
W: initramfs-tools configuration sets RESUME=UUID=fe222dcd-0dbe-4aec-8dcf-4e85881e85a6
W: but no matching swap device is available.

The installer should create a swap partition by default to enable hybernation and prevent the above error

**Comment by jeroenst** [comment]
This causes also bug https://github.com/linuxmint/linuxmint/issues/33

**Comment by xenopeek** [comment]
See the Linux Mint 19 release notes. Assuming you have home directory encryption, there is a known issue with swap that you have to manually correct post-install as explained in the release notes. This known error may possibly not have been in the release notes at the date you reported above.

**Comment by iHad169** [comment]
Me too

**Comment by iHad169** [comment]
xenopeek talk this:
[Linux Mint 19 release notes](https://www.linuxmint.com/rel_tara_cinnamon.php)
[[FIX] no swap on fresh LM19 install with home directory encryption](https://forums.linuxmint.com/viewtopic.php?f=90&t=274157)

xenopeek. Please write the LINK.
People do not know you talk about.
