### ISSUE TITLE
three different "minecraft launchers" - none even close to latest

### ISSUE THREAD

**Issue by ash-development** [linuxmint/linuxmint#341]
take a search for minecraft on https://community.linuxmint.com/software/search and you see three different softwares:

- https://community.linuxmint.com/software/view/minecraft-installer
- https://community.linuxmint.com/software/view/minecraft-launcher
- https://community.linuxmint.com/software/view/com.mojang.Minecraft

the download is provided at https://www.minecraft.net/en-us/download, but it would be nice to have it in the software manager

**Comment by thekilluadev** [comment]
also there's a warning saying that the latest version on the minecraft site might be outdated which is wildly untrue. 

![image](https://user-images.githubusercontent.com/75553731/103916291-407da200-50da-11eb-988f-12fc94522dc0.png)

**Comment by xenopeek** [comment]
Package `minecraft-launcher` is in the Linux Mint repository: http://packages.linuxmint.com/search.php?release=any&section=any&keyword=minecraft

**Comment by thekilluadev** [comment]
> Package `minecraft-launcher` is in the Linux Mint repository: http://packages.linuxmint.com/search.php?release=any&section=any&keyword=minecraft

not even close to latest version.

![image](https://user-images.githubusercontent.com/75553731/104267521-bded3d80-545f-11eb-9c86-4d231ba2e544.png)

**Comment by Secret-chest** [comment]
This should be closed.
