### ISSUE TITLE
Feature Request: Upgrade repository version of Bibletime to 3.0

### ISSUE THREAD

**Issue by haggkoos** [linuxmint/linuxmint#350]
The current version of Bibletime in the Linux Mint repositories (accessed through the software manager) is 2.11.1. 
The latest version is 3.0 and comes with many improvements:
https://github.com/bibletime/bibletime/releases/tag/v3.0

Please upgrade the version available through the main repositories to 3.0.

**Comment by xenopeek** [comment]
Bibletime comes from the Ubuntu package base repository and ultimately comes from Debian. Version 3.0 is in Debian testing and in the Ubuntu development release so you can expect it to be included in Linux Mint 21 next year. If you need version 3.0 now Ubuntu's Bibletime maintainers have a PPA you can add to your system to install it from: https://launchpad.net/~pkgcrosswire/+archive/ubuntu/ppa
