### ISSUE TITLE
Feature request : adding Shutter in Linux Mint repository

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#355]
Shutter is available only by PPA : https://www.linuxuprising.com/2020/10/shutter-screenshot-tool-ppa-updated-for.html
Could you add it in the LM repository ?

**Comment by xenopeek** [comment]
Shutter depends on GNOME 2 libraries that are long end-of-life and aren't available on Linux Mint 20+ package base. Shutter was removed from Debian in 2018 for that reason: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=904526. The PPA, or better yet an AppImage, is the better solution for such. Should Shutter migrate to GNOME 3.38 libraries, or better yet GNOME 40, it will likely be adopted back into Debian and that way also find its way onto Linux Mint. Meanwhile you might look at Flameshot as an alternative.

**Comment by InfoLibre** [comment]
I installed Shutter with PPA, it works. I tested all similar software but only Shutter is interesting. 

ksnip could be interesting too but you can't take a screenshot of a webpage. must be retested later. https://github.com/ksnip/ksnip. Versions Windows, macOS and Linux. Licence GNU GPL 2.

- Spectacle : https://github.com/KDE/spectacle/. No webpage screenshot, no drawing tools. Version Linux. Licence GNU GPL 2.
 - Flameshot : https://github.com/lupoDharkael/flameshot. Version Linux. Can only capture a zone.
 - ScreenCloud : https://github.com/olav-st/screencloud. Versions Windows, macOS and Linux (paquets AppImage et Snap uniquement). No webpage screenshot, no a lot of drawing tools. Licence GNU GPL 2.
 - ShareX : https://getsharex.com. Version Windows.
 - Greenshot : https://getgreenshot.org. Versions Windows and macOS.
 - smartision ScreenCopy (abandoned, version 2.3 du 25/09/2002) : http://smartision-sc.sourceforge.net. Version Windows.
 - Freeseer (abandoned, version 3.0.1 du 03/01/2014) : https://github.com/Freeseer/freeseer.
 - Clicktrace (abandoned, version 1.2 du 20/03/2014) : https://sourceforge.net/projects/clicktrace/. Versions Windows, macOS and Linux.
 - Lightscreen (abandoned, version 2.4 du 18/12/2016) : https://lightscreen.com.ar. Version Windows.
