### ISSUE TITLE
Feature request : adding Lutris in Linux Mint repository

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#356]
Lutris is available only by PPA : https://lutris.net
Could you add it in the LM repository ?
Lutris is better than Playonlinux.

**Comment by xenopeek** [comment]
It's in the next Debian release and in the next Ubuntu release so it will that way through those become available on future Linux Mint releases as well. Meanwhile as you say there is a PPA and Software Sources on Linux Mint makes it easy to add and managed PPAs.

**Comment by InfoLibre** [comment]
Good new, thank you.
