### ISSUE TITLE
Feature request : adding DVDStyler in Linux Mint repository

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#357]
[DVDStyler](https://www.dvdstyler.org) is available only by PPA : https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/dvdstyler
Could you add it in the LM repository ?

**Comment by InfoLibre** [comment]
DVDStyler is the only working DVD authoring software.

 - DevedeNG (could be retested but seems as good as DVDStyler) : https://gitlab.com/rastersoft/devedeng. Version Linux. Licence GNU GPL 3.

 - AVStoDVD : https://sourceforge.net/projects/avstodvd/. Version Windows. Licence **CC BY-NC**.
 - Polidori (abandoned, version 0.1-3 of 18/10/2004) : https://sourceforge.net/projects/polidori/.
 - ManDVD (abandoned, version 2.1.3 of 02/08/2006) : https://sourceforge.net/projects/csgib/.
 - DVDAuthor Wizard (abandoned, version 1.4.6 of 29/05/2007) : https://sourceforge.net/projects/dvdauthorwizard/.
 - DVD Flick (abandoned, version 1.3.0.7 du 26/06/2009) : https://sourceforge.net/projects/dvdflick/.
 - KMediaFactory (abandoned, version 0.8.1 of 01/08/2011) : https://code.google.com/archive/p/kmediafactory/.
 - 'Q' DVD Author (abandoned, version 2.3.1 of 05/04/2013) : https://sourceforge.net/projects/qdvdauthor/.
 - 2ManDVD (abandoned, version 1.8.5 of 30/07/2013) : http://2mandvd.tuxfamily.org/website/.
 - Mistelix (abandoned, version 0.33-3 of 18/10/2013) : https://launchpad.net/ubuntu/+source/mistelix.
 - tovid (abandoned, version 0.35.2 of 22/06/2015) : https://github.com/tovid-suite/tovid.
 - DVD Flick v2 (abandoned, version 1.3.1.0 of 25/10/2015) : https://sourceforge.net/projects/dvdflick-v2/.
 - Bombono DVD (abandoned, version 1.2.4 of 26/04/2016) : https://github.com/bombono-dvd/bombono-dvd.
 - Open DVD Producer (abandoned, version 16.11 of 16/11/2016) : https://github.com/jonata/opendvdproducer.

**Comment by InfoLibre** [comment]
https://bugs.launchpad.net/ubuntu/+source/dvdstyler/+bug/1933114

**Comment by InfoLibre** [comment]
I posted a Debian RFP: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1019978

**Comment by InfoLibre** [comment]
The debian RFP: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=635516

**Comment by tkbj** [comment]
QDVDAuthor is also a working DVD Software: https://sourceforge.net/projects/qdvd

**Comment by InfoLibre** [comment]
QDVDAuthor is available only for Linux.
