### ISSUE TITLE
Black screen at system startup

### ISSUE THREAD

**Issue by noisywiz** [linuxmint/linuxmint#364]
Perhaps the question does not apply to the distro, but I just don't know where to send it and what data to collect.

On all kernels above 5.0.0-32 I have a problem. The system starts, but the screen does not display anything.

```
Laptop: Lenovo Ideapad s540
Linux Mint 20.1 Cinnamon
Linux Kernel: 5.0.0-32-generic
Proccessor: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx × 4
```

**Comment by xenopeek** [comment]
Please make a New Topic on the support forums here: https://forums.linuxmint.com/viewforum.php?f=46. Requires registering an account. The support forums are there to help with troubleshooting issues. If you find a bug in a component maintained or developed by Linux Mint you can report it here. See also our troubleshooting guide: https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/

**Comment by noloader** [comment]
Ubuntu Issue 1870971, [(X)ubuntu 20.04 boots to black screen on Lenovo Ideapad L340-17API when in battery mode](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1870971).

I found it was easiest to work-around by installing the 5.8 kernel. I hope to go back to the 5.4 kernel when it gets fixed. The 5.4 kernel is a LTS kernel, while the 5.8 kernel is not.
