### ISSUE TITLE
Mint 19 Cinnamon (Bluetooth manager): Pairing with bluetooth keyboard Logitech K380 fails

### ISSUE THREAD

**Issue by jeroenst** [linuxmint/linuxmint#37]
When pairing a logitech k380 keyboard with Linux Mint 19 Cinnamon I get the message "Please enter the following PIN on "Keyboard K380". Then press "Return" on the keyboard."

When entering the PIN nothing happens. Also pressing the cancel button doesn't work.

**Comment by jeroenst** [comment]
After a reboot and trying again, it works. This has to be investigated further.

**Comment by xenopeek** [comment]
Looking on the forums I see a few mentions of bluetooth keyboard issues for Linux Mint 19 but those all appear to be unrelated to your issue. If you're able to complete troubleshooting for this (optionally by taking help from the forums) and can determine the cause to be in a component maintained by Linux Mint, this issue can be reopened.

**Comment by scarcher2** [comment]
I'm seeing this as well in Ubuntu 19.04 + Cinnamon. I'll be glad to provide logs / troubleshoot the issue.
