### ISSUE TITLE
Feature Request: add Ubuntu's low-latency kernel to the linux kernel selection tool

### ISSUE THREAD

**Issue by rschr** [linuxmint/linuxmint#370]
Which is the default kernel for Ubuntu's 'Ubuntu Studio' flavour. I guess it could help make Linux Mint a more attractive choice for a digital audio workstation.

**Comment by xenopeek** [comment]
This is already implemented. It's an advanced feature for experienced users. First quit Update Manager then run the following command to enable the feature (or install and use Dconf Editor to change this setting):

`gsettings set com.linuxmint.updates allow-kernel-type-selection "true"`

Next time you start Update Manager and go to the View > Linux Kernels dialog you will see a Kernel flavour selector in the bottom left of the dialog. You can select lowlatency here and then install a lowlatency kernel.

(I've tested the above command on Linux Mint 20.1. Prior versions of Linux Mint may not yet have support for this feature or may require a different setting to be changed.)
