### ISSUE TITLE
Linux Mint 20.1 download page has http links rather than https in the mirror site section

### ISSUE THREAD

**Issue by theduffman100** [linuxmint/linuxmint#378]
Linux Mint 20.1 ISO download pages (https://www.linuxmint.com/edition.php?id=284, https://www.linuxmint.com/edition.php?id=285 and https://www.linuxmint.com/edition.php?id=286) download mirror list section links to mirror sites using the http protocol rather than https, resulting in a failure to download.
To download the ISO image, one can copy the link location, replace the protocol with https and open it. However it would be easier if all the links were using https.
Example:
view-source:https://www.linuxmint.com/edition.php?id=285
```

<TD><img src="img/flags/3.gif" class="icon" alt="Canada" /></TD>
<TD>Canada</TD>
<TD><a href="http://muug.ca/mirror/linuxmint/iso/stable/20.1/linuxmint-20.1-mate-64bit.iso">Manitoba Unix User Group</a></TD>
</TR>

```

**Comment by qdinar** [comment]
failure? i tried http://muug.ca/mirror/linuxmint/iso/stable/20.1/ and it works.

**Comment by theduffman100** [comment]
Checked today and the links in the page are now https as they should. Thanks!
@qdinar downloading from unsecure URLs might have been blocked by common browsers. In any case, using plain http is riskier security-wise
