### ISSUE TITLE
Printer Epson XP-332

### ISSUE THREAD

**Issue by rsbo264** [linuxmint/linuxmint#381]
Hello,
I've an issue with my printer, I'm using Linux Mint ver 20.1.
I've an Epson expression home XP-332, currently Epson doesn't provide anymore the officials driver, I tried asking Linux to identify it and find a driver, CUPS was able to identify the printer and selecting a driver , this one "Local Raw Printer (grayscale, 2-sided printing)", but doesn't work with printer.
Instead Scanner is working properly.
So, Windows 10 and Mac OSX Catalina that I've available in other 2 machine are able to find drivers and print, I'm wondering if using the version mentioned of Linux Mint is possible to find a solution.

**Comment by xenopeek** [comment]
There's a Linux driver available from Epson. Search for xp-332 and OS set to Linux on https://download.ebz.epson.net/dsc/search/01/search/searchModule. Select the generic printer driver, on the next page click accept and then download the file ending with "amd64.deb". After downloading it double-click it in your file manager to start the installer and install it. If you need further help with this make a new topic (requires registering an account) in the Printers & Scanners support forum: https://forums.linuxmint.com/viewforum.php?f=51
