### ISSUE TITLE
LMDE 4 held back nvidia packages by default

### ISSUE THREAD

**Issue by ghost** [linuxmint/linuxmint#393]
On LMDE 4 you can choose to boot the installer with nvidia drivers, which pre-installs drivers for you once you install the system. Which is useful, and used to generally work fine, but I've reinstalled LMDE today with nvidia, and when upgrading packages, there are 4 nvidia packages that don't get upgraded, and one that claims to be held back. So what used to work fine, doesn't work fine anymore with the way Debian packages the drivers.

It's not a super huge deal, you can fix quite easily by `sudo apt purge nvidia.` and then reinstalling nvidia-driver. This reinstalls all of the necessary packages correctly without resulting in any weird dependency problems. But this solution isn't necessarily obvious to the average user, and it's probably best practice to ensure that the install disk installs things properly in the first place, anyway.

I'm just using my old LMDE 4 boot usb though, I guess it's possible this might have gotten corrected in an iso update since then, but it's not very clear on the download page whether the iso has even ever been updated and replaced past its initial release. I couldn't find mention of this particular issue anywhere though, so I'm not sure anyone else has stumbled upon it to report it in the first place.

**Comment by clefebvre** [comment]
Confirmed but doesn't affect upgrade and LMDE 4 is soon reaching EOL.
