### ISSUE TITLE
ubuntu-system-adjustments: Dangling link

### ISSUE THREAD

**Issue by ooglyhLL** [linuxmint/linuxmint#398]
The package installs `/usr/lib/python3/dist-packages/oneconf/distributor/LinuxMint.py` as a symlink to `Ubuntu.py` in the same directory. The latter however doesn't exist, leading to error in software relying on the functionality. OTOH, I was unable to find a Ubuntu package that installs the link target. An obsolete package perhaps?

**Comment by clefebvre** [comment]
Links removed, thanks.
