### ISSUE TITLE
xfce4-panel in uma breaks orage

### ISSUE THREAD

**Issue by sh-dvl** [linuxmint/linuxmint#407]
tried to update to uma, system wants to update xfce4-panel from 4.14.3 to 4.16.2, but this fails, because it breaks installed orage 4.12.1

please build a new package of orage which depends on new xfce4-panel, soon, because any further updates hang and must be executed pkg by pkg by hand (until another one fail due to needed updates).

and no, no remove of orage: it's really needed and part of normal distribution...

**Comment by sh-dvl** [comment]
additionally no context-menu works with old xfce4-panel and partially updated system...

it seems a bit unusable for normal users...

**Comment by xenopeek** [comment]
It's not possible to use Orage on Linux Mint 20.2. Linux Mint 20.2 uses Xfce 4.16 and that version of Xfce dropped support for GTK2 panel plugins. Orage hasn't had an active developer for years and its panel plugin is still GTK2. Xfce has archived Orage and it's no longer part of active Xfce.

If you want to upgrade to Linux Mint 20.2 you'll have to remove Orage.
