### ISSUE TITLE
Toolbar disappears (xfce)

### ISSUE THREAD

**Issue by Shiftupthecore** [linuxmint/linuxmint#408]
_Description:_
After removing standard Firefox icon from the Mint menu toolbar the whole toolbar disappears.

_Environment:_
Linux Mint xfce v.20.2

_Steps to reproduce:_
Right-click on the Firefox icon in the toolbar and choose: Remove.

_Expected result:_
Only Firefox icon removed.

_Actual result:_
Mint menu toolbar disappears, but can be resolved with a reboot.

**Comment by xenopeek** [comment]
I tested it and can confirm the same happens with xfce4-panel 4.16.2 on Xubuntu 21.04. So this is not a bug specific to Linux Mint but upstream in xfce4-panel.

I had already looked at open issues but I see now there is a closed fix that looks to be for this: https://gitlab.xfce.org/xfce/xfce4-panel/-/merge_requests/46. That's, _I think_, included with xfce-panel 4.16.3 https://gitlab.xfce.org/xfce/xfce4-panel/-/tags/xfce4-panel-4.16.3.

For now you'll have to depend on a workaround. I see you can just restart the panel after it crashes by pressing Alt+F2 to bring up the run dialog and type command `xfce4-panel`. That immediately restores it without need to reboot or log out.

**Comment by Shiftupthecore** [comment]
Dear Vincent,

Thank you very much for your quick response and notification for a workaround!

Yours sincerly,



2021-08-09 8:11 GMT+02:00, Vincent Vermeulen ***@***.***>:
