### ISSUE TITLE
MESA 21.0.3 package completely brokes Linux Mint in VirtualBox

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#409]
As this package completely brokes Linux Mint in VirtualBox, could you please add it in Synaptic and MintUpdate black list, in a new update ?
https://github.com/linuxmint/linuxmint/issues/406

**Comment by InfoLibre** [comment]
A lot of people ar eimpacted : https://forums.linuxmint.com/viewtopic.php?f=231&t=354405&sid=a48925f457499416c5590f7b6e63ab60&start=20

**Comment by AndyFx12** [comment]
Seems to be Cinnamon-related. 3D-hardware-acceleration of Virtualbox breaks whole Desktop (white icons, white background). Mate works fine, though. And real hardware works fine, too.

**Comment by clefebvre** [comment]
Upstream at https://gitlab.freedesktop.org/mesa/mesa/-/issues/5192.
It looks like the new version of Vbox fixes it also.
