### ISSUE TITLE
Mint 19 Cinnamon: Unable do a print screen when a dropdown list is open (occures in display settings and in gimp)

### ISSUE THREAD

**Issue by jeroenst** [linuxmint/linuxmint#41]
When a dropdown list is open it's not possible to do a printscreen. The printscreen dialog doesn't appear. I found this to be happening in display settings when changing resolution.

**Comment by smurphos** [comment]
This is a limitation of the x-server. The workaround is to to take a screenshot via the Screenshot GUI app (from the menu) with a delay to allow you to 'set-up' your screenshot.
