### ISSUE TITLE
Idea or request : missing ec_sys module in Linux Mint Debian Edition based on 4.19.0-17 kernel

### ISSUE THREAD

**Issue by ArnouldN** [linuxmint/linuxmint#412]
I recently got a HP DV6 laptop. There is a package named nbfc-linux (notebookfancontrol-linux) that can control its cooling fan by writing directly to the microcontroler's register of the ACPI system (Advanced Control and Power Interface). However this package requires an obscure kernel module named ec_sys that is not present in LMDE /lib/modules/ directory. It is there in my main system Lubuntu 20.04 LTE though, that I want to drop in favor of LMDE in the near future. 

So idea/request : please include this ec_sys module next time the kernel is upgraded, which, AFAIU, can happen even with LMDE. Thank you in advance.

**Comment by clefebvre** [comment]
upstream at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=980555.

**Comment by ArnouldN** [comment]
On Wed, 22 Sep 2021 04:49:54 -0700
Clement Lefebvre ***@***.***> wrote:

> Closed #412.
> 

Apparemement je peux répondre à ce mail.

NBFC - notebookfancontrol - et nbfc-linux fonctionnent très bien, mais
ont besoin du module ec_sys et qui appelle un module, ou un
include.h développé par intel, si je ne me trompe.

Pour faire fonctionner sous LMDE je me suis coltiné 2 jours
d'apprentissage pour compiler les modules "off tree" : ma première
réaction avait été de compiler sur mon système principal lubuntu que je
vais bientôt passer sous LMDE puis copier le fichier sur le portable.
Que nenni !!! Ce serait bien trop simple !

J'utilise LMDE car j'ai ras le bol de changer de kernel et autres
toutes les semaines. Heureusemement, car je ne me vois pas compiler
ec_sys à chaque fois que ubuntu change de noyau même avec un script... 

Et une petite remarque : je me suis décidé de passer à LMDE car Ubuntu a
laissé tomber les systèmes 32 bits, alors qu'il y a encore tant
d'ordinateurs 32 bits qui fonctionnent. Merci de continuer à les
supporter !

Arnould, Rueil-Malmaison, 58 ans, j'ai commencé avec le... Sinclair QL
(comme Linus lui-même !)
