### ISSUE TITLE
Install multimedia codecs tries to install libavcodec-extra58 in Linux Mint 19.3 Xfce

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/linuxmint#415]
On a freshly installed (and updated) Linux Mint 19.3 Xfce, or even a live session, the codec installation fails because **libavcodec-extra58** doesn't exist in the Bionic repository, but only in newer Ubuntu releases. **libavcodec-extra57** should be installed in 19.x.

Please fix **mint-meta-codecs** for 19.x.

P.S. This issue was first [reported in the forums](https://forums.linuxmint.com/viewtopic.php?t=348016).

P.S.2 If you don't use the Update Manager after rebooting into a fresh install, the older version of mint-meta-codecs will download the correct packages, including **libavcodec-extra57**.

**Comment by clefebvre** [comment]
Thanks @kneekoo, fixed in mintreport 1.2.1.1.
