### ISSUE TITLE
Keyboard does not work on coldboot

### ISSUE THREAD

**Issue by IGrayfoxI** [linuxmint/linuxmint#416]
I am currently having an issue on my new Asus UM425UAZ laptop where the keyboard does not work on a cold boot, but will after doing a reboot.

The keyboard works in the UEFI, on the Grub Menu and drops on booting into Cinnamon

I have done a reinstall, installed kernel 5.11.0-27 as well as upgraded to the 5.11.0-34 kernel.

The issue also exists in the Live Environment of Mint 20.2

I also cold booted into the following Live Environments
LMDE4
But was greeted to a black screen, but entering the tty1 worked and the keyboard worked.
But without going into Cinnamon it is hard to say when the issue shows itself

Ubuntu 20.04 LTS
No Keyboard working,

Fedora 34
Keyboard works fine

**inxi -Fxxxrz** output
```
System:
  Kernel: 5.11.0-27-generic x86_64 bits: 64 compiler: N/A 
  Desktop: Cinnamon 5.0.5 wm: muffin 5.0.1 dm: LightDM 1.30.0 
  Distro: Linux Mint 20.2 Uma base: Ubuntu 20.04 focal 
Machine:
  Type: Laptop System: ASUSTeK product: ZenBook UX425UAZ_UM425UAZ v: 1.0 
  serial: <filter> 
  Mobo: ASUSTeK model: UX425UAZ v: 1.0 serial: <filter> 
  UEFI: American Megatrends LLC. v: UX425UAZ.301 date: 06/10/2021 
Battery:
  ID-1: BATT charge: 64.3 Wh condition: 64.3/63.1 Wh (102%) volts: 12.0/12.0 
  model: ASUSTeK UX425 type: Li-ion serial: <filter> status: Discharging 
  cycles: 2 
CPU:
  Topology: 8-Core model: AMD Ryzen 7 5700U with Radeon Graphics bits: 64 
  type: MT MCP arch: Zen rev: 1 L2 cache: 4096 KiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm 
  bogomips: 57491 
  Speed: 1305 MHz min/max: 1400/1800 MHz boost: enabled Core speeds (MHz): 
  1: 1397 2: 1397 3: 1397 4: 1397 5: 1397 6: 1397 7: 1397 8: 1397 9: 1397 
  10: 1397 11: 1397 12: 1399 13: 1397 14: 1395 15: 1397 16: 1397 
Graphics:
  Device-1: AMD vendor: ASUSTeK driver: amdgpu v: kernel bus ID: 04:00.0 
  chip ID: 1002:164c 
  Display: x11 server: X.Org 1.20.11 driver: amdgpu,ati 
  unloaded: fbdev,modesetting,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: AMD RENOIR (DRM 3.40.0 5.11.0-27-generic LLVM 12.0.0) 
  v: 4.6 Mesa 21.0.3 direct render: Yes 
Audio:
  Device-1: AMD vendor: ASUSTeK driver: snd_hda_intel v: kernel 
  bus ID: 04:00.1 chip ID: 1002:1637 
  Device-2: AMD Raven/Raven2/FireFlight/Renoir Audio Processor 
  vendor: ASUSTeK driver: snd_rn_pci_acp3x v: kernel bus ID: 04:00.5 
  chip ID: 1022:15e2 
  Device-3: AMD Family 17h HD Audio vendor: ASUSTeK driver: snd_hda_intel 
  v: kernel bus ID: 04:00.6 chip ID: 1022:15e3 
  Sound Server: ALSA v: k5.11.0-27-generic 
Network:
  Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel bus ID: 01:00.0 
  chip ID: 8086:2723 
  IF: wlp1s0 state: up mac: <filter> 
Drives:
  Local Storage: total: 476.94 GiB used: 75.43 GiB (15.8%) 
  ID-1: /dev/nvme0n1 vendor: Western Digital 
  model: PC SN530 SDBPTPZ-512G-1002 size: 476.94 GiB speed: 31.6 Gb/s 
  lanes: 4 serial: <filter> rev: 21106000 scheme: GPT 
Partition:
  ID-1: / size: 374.48 GiB used: 75.40 GiB (20.1%) fs: ext4 
  dev: /dev/nvme0n1p2 
Sensors:
  System Temperatures: cpu: 45.6 C mobo: N/A gpu: amdgpu temp: 38 C 
  Fan Speeds (RPM): N/A 
Repos:
  No active apt repos in: /etc/apt/sources.list 
  Active apt repos in: /etc/apt/sources.list.d/ia32-libs-raring.list 
  1: deb http://old-releases.ubuntu.com/ubuntu/ raring main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
  1: deb https://mirror.aarnet.edu.au/pub/linuxmint-packages uma main upstream import backport
  2: deb http://mirror.realcompute.io/ubuntu focal main restricted universe multiverse
  3: deb http://mirror.realcompute.io/ubuntu focal-updates main restricted universe multiverse
  4: deb http://mirror.realcompute.io/ubuntu focal-backports main restricted universe multiverse
  5: deb http://security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
  6: deb http://archive.canonical.com/ubuntu/ focal partner
Info:
  Processes: 359 Uptime: N/A Memory: 15.09 GiB used: 1.34 GiB (8.9%) 
  Init: systemd v: 245 runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 Shell: bash 
  v: 5.0.17 running in: gnome-terminal inxi: 3.0.38
```

**Cold Boot dmesg --level=alert,crit,err**
```
[    0.287720] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.GPP1.WLAN], AE_NOT_FOUND (20201113/dswload2-162)
[    0.287727] ACPI Error: AE_NOT_FOUND, During name lookup/catalog (20201113/psobject-220)
[    1.094630] i8042: Can't read CTR while initializing i8042
[    3.950633] amdgpu 0000:04:00.0: amdgpu: Unsupported power profile mode 0 on RENOIR
[    5.053506] acp_pdm_mach acp_pdm_mach.0: snd_soc_register_card(acp) failed: -517
[    5.557286] CIFS: VFS: Error connecting to socket. Aborting operation.
[    5.558559] CIFS: VFS: cifs_mount failed w/return code = -101
[   66.671880] ucsi_acpi USBC000:00: PPM init failed (-110)
```

**Warm boot dmesg --level=alert,crit,err**
```
[    0.280805] ACPI BIOS Error (bug): Could not resolve symbol [\_SB.PCI0.GPP1.WLAN], AE_NOT_FOUND (20201113/dswload2-162)
[    0.280812] ACPI Error: AE_NOT_FOUND, During name lookup/catalog (20201113/psobject-220)
[    3.257975] amdgpu 0000:04:00.0: amdgpu: Unsupported power profile mode 0 on RENOIR
[    4.800993] acp_pdm_mach acp_pdm_mach.0: snd_soc_register_card(acp) failed: -517
[    4.801090] acp_pdm_mach acp_pdm_mach.0: snd_soc_register_card(acp) failed: -517
[    5.026470] CIFS: VFS: Error connecting to socket. Abotrting operation.
[    5.027373] CIFS: VFS: cifs_mount failed w/return code = -101
[   64.901008] ucsi_acpi USBC000:00: PPM init failed (-110)
```

Forums Thread on the issue
https://forums.linuxmint.com/viewtopic.php?p=2062440#p2062440

While the current work around is "Reboot it" this is not the most ideal situation

Any suggestions will be appreciated

Thanks

**Comment by Raptus1** [comment]
Using Asus Zenbook UM325U model (OP has 14" model, this is 13" model) gives the same issue and ACPI BIOS error (bug) as OP.
Tested on Linux Mint, Ubuntu 20.04 and 21.04, same error on all.

Using acpi=off in grub boot command gives back the keyboard so I can decrypt LUKS, but this disables the touchpad and probably other things as well.

Tested with kernel 5.13 with same result.

**Comment by IGrayfoxI** [comment]
@Raptus1 can you live boot Fedora 34 to see if keyboard works on coldboot.
Keyboard did not work on coldboot into live on Ubuntu based distros, debian would not load in at all.

**Comment by Raptus1** [comment]
Sure, I'll post a new comment when I have tested it :)

**Comment by Raptus1** [comment]
So I tested it and there is no difference there.

Keyboard and touchpad worked on first boot and on reboot after running update, like on the other distros, but as soon as I put it in suspend (overnight) and started it up again, the touchpad stopped working and when I cold-booted the keyboard were not available from LUKS on, exactly like on the other distros.

I think I will be returning this computer as I got it last week for my wife. Will wait for some maturity before I get it. Hopefully it will also be available locally with zen3 (5800u) instead of just zen2+ (5700u).

**Comment by IGrayfoxI** [comment]
> 
> 
> So I tested it and there is no difference there.
> 
> Keyboard and touchpad worked on first boot and on reboot after running update, like on the other distros, but as soon as I put it in suspend (overnight) and started it up again, the touchpad stopped working and when I cold-booted the keyboard were not available from LUKS on, exactly like on the other distros.
> 
> But if you want me to test something else before I return it tomorrow night, please let me know :)

Sorry for delayed response, head to fix a car issue.

It is odd that it didn't work for you on Fedora 34.
I doubt their versions would be difference between the flavors of Fedora 34, but the ISO i am booting into is workstation edition and uses the Gnome 4 DE

**Comment by Raptus1** [comment]
#ssc-9142988177642072726 #response_container_BBPPID{font-family: initial;font-size: initial;color: initial;} Just to clarify:It did work initially; Installed it with encryption, booted it up, installed updates, rebooted, installed some more updates, rebooted again had it on for a while and everything seemed to work fine. Then I suspended it and the next morning when I woke the computer up, the touchpad did not work for some reason.I cold booted the machine and then the keyboard was not working again.I had this experience in the other distros as well.But I asked around and a colleague of mine sent me this: https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.15-x86-DriversSeems like the asus ACPI-part is relevant for the Zenbook and things might work better as of Kernel-version 5.15. :)                                                                                                                                            Best regards!              Original Message       Show Details                                                                                                                                                                         From: ***@***.***: 10 September 2021 23:43To: ***@***.*** to: ***@***.***: ***@***.***; ***@***.***: Re: [linuxmint/linuxmint] Keyboard does not work on coldboot (#416)  

So I tested it and there is no difference there.
Keyboard and touchpad worked on first boot and on reboot after running update, like on the other distros, but as soon as I put it in suspend (overnight) and started it up again, the touchpad stopped working and when I cold-booted the keyboard were not available from LUKS on, exactly like on the other distros.
But if you want me to test something else before I return it tomorrow night, please let me know :)

Sorry for delayed response, head to fix a car issue.
It is odd that it didn't work for you on Fedora 34.
I doubt their versions would be difference between the flavors of Fedora 34, but the ISO i am booting into is workstation edition and uses the Gnome 4 DE

**Comment by IGrayfoxI** [comment]
I used a live image, not going to install Fedora.
Finally got my install the way I like it.

Sadly I cant put my laptop int suspend/sleep mode.

On Kernel 5.11.0-27 It just coldbooted in,
On Kernel 5.11.0-34 it just wakes to a black screen.
But this issue is less of an annoyance

**Comment by IGrayfoxI** [comment]
Issue fixed.
Adding "i8042.reset=1" to the kernel boot options gets the keyboard to work on cold boots.
