### ISSUE TITLE
Could I add cat language?

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/linuxmint#419]
I would like to add a hidden joke language called Cat. It would be accessed by entering the konami code (↑↑↓↓←→←→ba) in the language settings.

When you do the code, it will get added as an option.

**Comment by Secret-chest** [comment]
To clarify: The cat language would only be shown if it was selected or the konami code was entered since the last opening of the language settings.

**Comment by xenopeek** [comment]
You could program that for your own use if you want. It will not be included with Linux Mint.

Language settings is written in Python and Gtk, that's the easy part. You'll also need to do all the plumbing to add the language locale and translation files to the OS for your made up language. If you want to tinker with this, have fun!
