### ISSUE TITLE
Mint 19 Cinnamon: Drop down boxes have a lot of empty space

### ISSUE THREAD

**Issue by jeroenst** [linuxmint/linuxmint#42]
When I open the display resolution dropdown in the display settings almost half top part of dropdown is white space.

**Comment by jeroenst** [comment]
Also happens in gimp when selecting file type when exporting image

**Comment by jeroenst** [comment]
![dropdown empty space](https://user-images.githubusercontent.com/2833940/46497109-ed8d5400-c819-11e8-9431-a0ec008ac65d.png)

**Comment by xenopeek** [comment]
The popup height is set to the required height to show all resolution options. Its contents is scrolled such that the active resolution is shown center on the "Resolution" line, which causes part of the resolutions in the list to be scrolled out above or below the popup window and leave that blank space. When you scroll the resolution list it pops into place and fills the entire popup window. If you can think of an improvement for this you're welcome to suggest it on cinnamon-control-center.
