### ISSUE TITLE
website - http://segfault.linuxmint.com not reachable 

### ISSUE THREAD

**Issue by orcus-de** [linuxmint/linuxmint#429]
https://segfault.linuxmint.com/2013/05/oem-isos-explained/  (and  https://segfault.linuxmint.com) ends up at sucuri crying about host not being reachable

(living in germany, another user from the us faced the same result)

could it be that the according urls got dropped entirely due to the redesign of the website?

**Comment by xenopeek** [comment]
All development news is on https://blog.linuxmint.com/ from mid 2017. The segfault website hasn't been used for that since.

The Wayback Machine has the page cached if you want to read the news from 2013: https://web.archive.org/web/20201021131159/https://segfault.linuxmint.com/2013/05/oem-isos-explained/

**Comment by orcus-de** [comment]
It's not that I'm missing "another resource people wont find normally", but I prefered the more detailed description there, what OEM means == I used to share the page at IRC to have some official reference coming from clem, which I changed since the page is gone, to point people at:
 [(https://linuxmint-installation-guide.readthedocs.io/en/latest/oem.html)].

As I rechecked the differences again - both descriptions are lacking an explicit hint about what would happen to the OEM-user and its data on using the "Prepare for shipping to end user" option, like:

IMPORTANT: If you installed using the OEM-option by mistake: Backup personal/important data first and run the 'Prepare for shipping' (desktop-icon). This will offer an option on next reboot to create a new/real user account: **the user OEM and his DATA will get DELETED at this point!**

And yes - there still show up regular users at IRC every now and then having used the oem setup by mistake ...

cheers orcus
