### ISSUE TITLE
Boot screen (Grub2) theme for Linux Mint: Sunshine-LinuxMint. One size fits all.

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/linuxmint#43]
It would be great to include this Grub theme in all Linux Mint distributions.
- SVG sources and everything included.
- Multi-resolutions design: from 640x480 to 1024x768 and higher (read README file...)
- Automatic Installer now included (2018-08-02)
- MIT License: no restrictions.
- Optional matching login background also included.

![preview_800x600](https://i.imgur.com/NwWgeHQ.png)

DOWNLOAD, DESCRIPTION, and INSTALLATION instructions now on Gnome-Look:
[Sunshine-LinuxMint](https://www.gnome-look.org/p/1247545/)

**Comment by xenopeek** [comment]
Many thanks for contributing to Linux Mint. Your contribution/suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by SebastJava** [comment]
Original post edited: improved presentation text.
