### ISSUE TITLE
Canonical "DRM"(?) HTTP request?

### ISSUE THREAD

**Issue by mariomadproductions** [linuxmint/linuxmint#431]
![Screenshot from 2021-11-03 10-43-28](https://user-images.githubusercontent.com/9919020/140047104-a88950f1-c74d-4337-b5da-146af4d107ea.png)

/usr/lib/ubuntu-advantage/timer.py
It tries to send a request to contracts.canonical.com

Said python file imports the module "uaclient".

```
user@pc:/usr/lib/python3/dist-packages/uaclient$ grep -riF 'canonical.com'
serviceclient.py:            '{"https://contracts.canonical.com/v1/resources": \
Binary file __pycache__/defaults.cpython-38.pyc matches
Binary file __pycache__/cli.cpython-38.pyc matches
Binary file __pycache__/serviceclient.cpython-38.pyc matches
defaults.py:BASE_CONTRACT_URL = "https://contracts.canonical.com"
clouds/gcp.py:    "default/identity?audience=contracts.canonical.com&"
Binary file clouds/__pycache__/gcp.cpython-38.pyc matches
cli.py:UA_AUTH_TOKEN_URL = "https://auth.contracts.canonical.com"
```
Maybe unwanted/unfamiliar URLs should be automatically searched for in ubuntu packages?

**Comment by xenopeek** [comment]
The files you mention come from the ubuntu-advantage-tools package. That is to interface with [Ubuntu Advantage](https://ubuntu.com/advantage) service. It was erroneously present on a past release of Linux Mint. On new installs of current 20.2 version it should not have been installed by default.

You can remove it through Synaptic Package Manager or with command:
```apt purge ubuntu-advantage-tools```
