### ISSUE TITLE
Display Recycle bin by default

### ISSUE THREAD

**Issue by ociteau** [linuxmint/linuxmint#434]
Hi,

I have chosen Linux Mint because it is closed to MS Windows and easy for a beginner. I tried all 4 versions of Mint.
Recycle bin should be displayed by default, since it is aimed at beginners

**Comment by Secret-chest** [comment]
Just because it is aimed at beginners, dosen't mean it should be added. But it should be easier to empty your trash, so yeah

**Comment by ociteau** [comment]
It seems that this feature has been refused
