### ISSUE TITLE
Firefox 94.0+linuxmint1+uma hangs

### ISSUE THREAD

**Issue by tk7r** [linuxmint/linuxmint#436]
After updating Firefox from latest 93 linuxmint release to 94.0+linuxmint1+uma i discover random hangs of firefox. A link or a new website cannot be started while the UI still is responding. Only a restart of firefox fixes the problem. While searching a solution i came to bugreports on bugzilla.mozilla.org, debian, opensuse - all describing the same problem and a possible solution.

https://bugzilla.mozilla.org/show_bug.cgi?id=1740260
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=998108
https://bugzilla.opensuse.org/show_bug.cgi?id=1192067

Could you please fix the linux mint provided firefox builds?

**Comment by mtwebster** [comment]
There's been a firefox update (94.0.2) - it should make its way to the update manager soon, I believe it should address this issue. 

https://www.mozilla.org/en-US/firefox/94.0.2/releasenotes/
