### ISSUE TITLE
Problem connecting to Wifi Enterprise networks (old but persistent bug)

### ISSUE THREAD

**Issue by leandromartinez98** [linuxmint/linuxmint#44]
When trying to connect to some wifi networks which have enterprise security configurations, the network manager fails. 

When one tries to connect, instead of opening the network configuration dialogue (where one can chose the type of connection, security, etc), the general "Network" menu opens.

There is no error message on dmesg ou syslog. 

There is a workaround which works for some networks, which is to connect to them using the "connect to hidden network" dialogue. 

The bug is present in Linux mint 18.3 and 19, at least, and can be reproduced using a fresh installation from a pendrive. 

The same bug is not present in Ubuntu.

The bug was reported recently here:

https://forums.linuxmint.com/viewtopic.php?p=1497180&sid=7baa05004951824207f1b4c742677118#p1497180

And in 2015 here:

https://forums.linuxmint.com/viewtopic.php?p=1497180&sid=7baa05004951824207f1b4c742677118#p1497180

**Comment by xenopeek** [comment]
On the most recent topic about this there is a [comment](https://forums.linuxmint.com/viewtopic.php?f=90&t=269792#p1475415) detailing how to connect to enterprise networks. Linux Mint 18.3 and 19 use NetworkManager from their respective Ubuntu package bases (16.04 or 18.04). Not having access to an enterprise network limits what else I can look into to confirm and find responsible component. I suggest taking more help from the forum as there are many more people active on the forum.
