### ISSUE TITLE
Wifi driver gets disabled after sleep!

### ISSUE THREAD

**Issue by viveksreedharan88** [linuxmint/linuxmint#441]
When you put the computer into sleep and after it wakes up,the wifi applet gets disabled. We r unable to connect to wifi. The only solution as of now is to reboot the system. Yet this is a bug which must be fixed on priority.

**Comment by xenopeek** [comment]
It's not uncommon for sleep to cause problems with wireless devices (or other devices), that sleep powers them off and resuming from sleep does not power them back on. Thus requiring a reboot to power them back on. If the wireless device does not wake up from sleep, the applet has no device to show either. It's unlikely a problem with the applet but instead a power management issue. There may be a BIOS option for how deep the sleep is or else it may require configuring some kernel parameters or some specific to our hardware command to run after resume from sleep to power device back on. For help with troubleshooting this I suggest asking in the Networking section on the support forums https://forums.linuxmint.com/viewforum.php?f=52.
