### ISSUE TITLE
Feature request: use PCMemTest instead of Memtest86+

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#446]
https://github.com/martinwhitaker/pcmemtest

**Comment by xenopeek** [comment]
Moved here as the beta is for bug squashing only.

**Comment by InfoLibre** [comment]
Thank you.

**Comment by InfoLibre** [comment]
I tested this ISO https://www.techguysg.com/posts/memorytest/, it works:

![Capture d’écran du 2022-02-16 17-52-14](https://user-images.githubusercontent.com/3955499/154315936-32f861ea-4d3e-4b1d-8479-acbee5d98d4c.png)

**Comment by InfoLibre** [comment]
A new version of Memtest86+ is published : https://www.memtest.org
The project is continued by new people.
Will you add it to Linux Mint 21 ?

**Comment by xenopeek** [comment]
https://packages.ubuntu.com/jammy/memtest86+ shows that is what is already in the package base repository.

**Comment by InfoLibre** [comment]
My request wasn't about base repository but about GRUB menu on Linux Mint live ISO :
![menu GRUB - Start Linux Mint](https://user-images.githubusercontent.com/3955499/170439236-a31587dd-a825-40cb-9926-c30185a264c9.png)

**Comment by InfoLibre** [comment]
It could be interesting to update Memtest86+ in GRUB menu with version 6, even it's a beta version, we could test it.
