### ISSUE TITLE
Europe/Dublin locale is being recognised by Wine as W. Central Africa

### ISSUE THREAD

**Issue by BaconCatBug** [linuxmint/linuxmint#449]
Steps to Reproduce:
Set Locale to Europe/Dublin
Run Wine Registry
HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\TimeZoneInformation says "W. Central Africa Time". This is incorrect.
Set Locale to Europe/London
Run Wine Registry
HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\TimeZoneInformation says "GMT Standard Time", as expected.

The folks at wine insist this is not a bug with Wine, so reporting it here.

**Comment by xenopeek** [comment]
Where you write "locale" you mean timezone. Locale is about language and related data formats, not about which timezone to use for the clock. mintlocale doesn't play a role in timezone.

I can reproduce this on Linux Mint but also on Ubuntu 22.04 LTS (daily build ISO) and on Fedora 35. On Fedora 35 I installed Wine from WineHQ's own repository https://wiki.winehq.org/Fedora. I reproduced the issue with Wine stable 5.0, Wine development 6.0 and also Wine staging 7.0-rc3. I checked with `timedatectl` what the timezone on the system was before running `wine regedit` to check the registry key you mentioned.

As it is trivial to reproduce the issue on other OSes it's clearly not a Linux Mint specific issue. I couldn't find your bug report on Wine https://bugs.winehq.org so if you hadn't already I suggest filing a bug there about Europe/Dublin timezone being recognized by Wine incorrectly.
