### ISSUE TITLE
Linux Mint 19 latest kernel version still has Ubuntu "branding"

### ISSUE THREAD

**Issue by K5CPU** [linuxmint/linuxmint#45]
uname reports that the kernel version is as follows with the latest update:

$ uname -v
#31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018

Full text from uname -a:

$ uname -a
Linux redbud 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by smurphos** [comment]
The kernels come directly from the Ubuntu repos so I don't think this is any surprise.
