### ISSUE TITLE
Firefox 95.0.1+linuxmint1.1+una Help>About... still displays old version after update

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/linuxmint#451]
`Linux Mint Cinnamon 20.2`

Everything works fine. Preferred search engines are kept, okay. The only problem is... version number does not match:

**mintUpdate > View > History:**
2021-12-21 13:56:51 firefox-locale-fr 95.0.1+linuxmint1.1+una

**Terminal:**
```
firefox --version
Mozilla Firefox 95.0.1
```

**Firefox > Help > About Firefox:**

![Firefox-help-about](https://user-images.githubusercontent.com/31940713/148589701-f8e95620-cc4b-4831-868f-5aca2fc751e7.png)

**Comment by xenopeek** [comment]
I assume specifically you mean the "mint - 1.0" in the screenshot, that you expected "mint 1.1" because the package version is +linuxmint1.1?

The current version is +linuxmint3 and that displays "mint-001 - 1.0". One might expect a 3 in there somewhere but I don't know if that is or should be related.

**Comment by SebastJava** [comment]
> I assume specifically you mean the "mint - 1.0" in the screenshot, that you expected "mint 1.1" because the package version is +linuxmint1.1?

@xenopeek Yes, exactly. On **Linux Mint Cinnamon 20.2,** with the Update Manager saying "Your system is up-to-date", the package version is 95.0.1+linuxmint1.1+una, according to mintUpdate > View > History. But the Firefox > Help > About Firefox does not display the real, current version. Just a small visual bug, I guess.

> The current version is +linuxmint3 and that displays "mint-001 - 1.0". One might expect a 3 in there somewhere but I don't know if that is or should be related.

Yes, this is the same kind of bug. This 95.0.1+linuxmint3 is the current Firefox version on Mint 20.3. And, of course, the Firefox > Help > About Firefox should show the same version number.

That is unless I did not understand something...

**Comment by SebastJava** [comment]
The wrong number is now circled in the screenshot above.

**Comment by SebastJava** [comment]
**Another possibility ?**
You could also just avoid this issue now and in the future. Look at Chromium: no Mint version number or name there, thus avoiding any errors. :)

![image](https://user-images.githubusercontent.com/31940713/148622635-3d7d94c5-d011-459c-a214-6c11be75207b.png)

**Comment by clefebvre** [comment]
There's no correlation between these numbers.
