### ISSUE TITLE
No pdf Thumbs in LM 20.3

### ISSUE THREAD

**Issue by messouh** [linuxmint/linuxmint#452]
The PDF thumbnails was working in LM Cinnamon 20.2. But after update to 20.3 it stop working and general pdf icon are displayed instead.

**Comment by clefebvre** [comment]
is xreader installed?

**Comment by messouh** [comment]
Yes, I even try : 
apt install --reinstall xreader xreader-common
but with no sucess.

Even with : NEMO_DEBUG=thumbnails nemo --debug
no notification from (xreader-thumbnailer) appears when duplicate a dpf or doing a refresh of the folder.

I also, note that thumbnails works for images and videos. If I return to 20.2 with timeshift, it works.
I have also tested the fresh 20.3 version (live usb) and PDF thumbnails works fine.

**Comment by mtwebster** [comment]
Does deleting your existing thumbnail cache help?
```
rm -rf ~/.cache/thumbnails
```

**Comment by messouh** [comment]
unfortunately no

**Comment by clefebvre** [comment]
what does this command say?

`search for pdf in /usr/share/thumbnailers`

**Comment by clefebvre** [comment]
You can also try to invoke the thumbnailer directly:

`xreader-thumbnailer my.pdf my.png`

to see if my.png looks fine.

**Comment by messouh** [comment]
First `xreader-thumbnailer my.pdf my.png` works fine.

The result of the command : `search for pdf in /usr/share/thumbnailers` is 

/usr/share/thumbnailers/atril.thumbnailer:4:MimeType=application/pdf;application/x-bzpdf;application/x-gzpdf;application/x-xzpdf;application/postscript;application/x-bzpostscript;application/x-gzpostscript;image/x-eps;image/x-bzeps;image/x-gzeps;application/x-dvi;application/x-bzdvi;application/x-gzdvi;image/vnd.djvu;image/vnd.djvu+multipage;image/tiff;application/x-cbr;application/x-cbz;application/x-cb7;application/x-cbt;application/vnd.comicbook+zip;application/vnd-comicbook.rar;image/*;application/oxps;application/vnd.ms-xpsdocument;
/usr/share/thumbnailers/evince.thumbnailer:4:MimeType=application/pdf;application/x-bzpdf;application/x-gzpdf;application/x-xzpdf;application/x-ext-pdf;application/postscript;application/x-bzpostscript;application/x-gzpostscript;image/x-eps;image/x-bzeps;image/x-gzeps;application/x-ext-ps;application/x-ext-eps;application/illustrator;application/x-dvi;application/x-bzdvi;application/x-gzdvi;application/x-ext-dvi;image/vnd.djvu+multipage;application/x-ext-djv;application/x-ext-djvu;image/tiff;application/x-cbr;application/x-cbz;application/x-cb7;application/x-cbt;application/x-ext-cbr;application/x-ext-cbz;application/x-ext-cb7;application/x-ext-cbt;application/vnd.comicbook+zip;application/vnd.comicbook-rar;application/oxps;application/vnd.ms-xpsdocument
/usr/share/thumbnailers/xreader.thumbnailer:4:MimeType=application/pdf;application/x-bzpdf;application/x-gzpdf;application/x-xzpdf;application/postscript;application/x-bzpostscript;application/x-gzpostscript;image/x-eps;image/x-bzeps;image/x-gzeps;application/x-dvi;application/x-bzdvi;application/x-gzdvi;image/vnd.djvu;image/vnd.djvu+multipage;image/tiff;application/x-cbr;application/x-cbz;application/x-cb7;application/x-cbt;application/vnd.comicbook+zip;application/vnd.comicbook-rar;application/oxps;application/vnd.ms-xpsdocument;application/epub+zip;

**Comment by clefebvre** [comment]
Ah maybe atril or evince is taking control here... can you remove these two readers to see if it helps? You might log out and log back in just in case also.

**Comment by messouh** [comment]
Thank you very much, very clever.
In fact, I first remove evince. But nothing solved.
Atril wasn't installed, but I found that the packages atril-common libatrildocument3 libatrilview3 are installed.
So, I removed them and wow the problem is solved.
I wonder why it take control in the 20.3 version but not in the 20.2 ! Anyway thanks :)
