### ISSUE TITLE
Website issue - linuxmint.ro is offline

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/linuxmint#453]
Linuxmint.ro, listed in the https://linuxmint.com/links.php page, stopped working. Could you remove, replace or tell the owners to do something about it?

**Comment by clefebvre** [comment]
It's been down for a while or only just now?

**Comment by Secret-chest** [comment]
> It's been down for a while or only just now?

@clefebvre 3 months

**Comment by clefebvre** [comment]
aha that's long enough. Thanks :)

**Comment by clefebvre** [comment]
Removed.
