### ISSUE TITLE
mirror.yandex.ru doesn't work via HTTPS: but works fine via HTTP:

### ISSUE THREAD

**Issue by anatoly-tiukov** [linuxmint/linuxmint#455]
**Describe the bug**
The package mint-mirrors.deb contains link to `https://mirror.yandex.ru` which doesn't work via this protocol but works fine via **http:**
So, manual replacement in `/usr/share/mint-mirrors/linuxmint.list` or `/etc/apt/sources.list.d/official-package-repositories.list` fixes the problem.

**Screenshots**
![Снимок экрана от 2022-01-10 06-20-47](https://user-images.githubusercontent.com/60889704/148716623-fd3cdc23-014a-439c-a2bb-5c0464b877b8.png)

**To Reproduce**
1. Run `mintsources`
2. Choose the "Yandex Team" mirror in Main (Una) list. _Country: Russia_
3. Update APT list

**Distribution:**
- [x] Linux Mint
- [ ] LMDE
- [ ] Other (please specify)

**Additional context**
Sorry if this is a wrong place for this bug but I couldn't find a more suitable repo for mint-mirrors.deb
Also, Ubuntu (focal) mirror list contains http: link to yandex :-)

**Comment by gmk57** [comment]
I've reported this to Yandex open-source team almost half a year ago, but apparently without success.

Investigated some obvious reasons, but without success:
1) certificate chain itself seems to be correct, it gets "A" grade at https://www.ssllabs.com/ssltest/analyze.html?d=mirror.yandex.ru&s=213.180.204.183
2) apt itself can work with https, for example https://mirror.corbina.net/ubuntu repository works fine.
 
The only possible cause I can think of is SHA1 signature on the root certificate.
![image](https://user-images.githubusercontent.com/22061463/150872923-54b31492-f33f-411d-81cf-68bb9c6cd664.png)

 
There is a similar issue with GnuTLS: https://bugs.launchpad.net/ubuntu/+source/gnutls28/+bug/1875920
Maybe apt is also affected by it?
![Screenshot from 2021-09-09 01-15-58b](https://user-images.githubusercontent.com/22061463/150873395-3d656746-9596-4ff2-bd14-4b2f3b43307a.png)

**Comment by clefebvre** [comment]
Fixed in Mint 21 and LMDE 5.
