### ISSUE TITLE
Cinnamon main menu width

### ISSUE THREAD

**Issue by Vest1am** [linuxmint/linuxmint#456]
Dear developers! Please enable fixed width for the main menu. It's just that in Russian, some word combinations are very long and the menu becomes very wide.

Yours faithfully Maltsev Denis.

**Comment by mtwebster** [comment]
Is this the stock menu? We already define a maximum width, I'm not sure what's going on here.

What is 'very wide'?  Can you provide a screenshot?

**Comment by Vest1am** [comment]
Here you can see that there is a limitation on the width, but because of the long name of the application it looks not very nice, so I ask you to make it possible to manually set the width of the main menu, if possible.
[screenshot](https://ibb.co/QfVcyMJ)
