### ISSUE TITLE
the notify-send program is being updated mint has a old version (0.7.6)

### ISSUE THREAD

**Issue by osmand** [linuxmint/linuxmint#46]
The program shows notifications in the upper right corner I think it is the same one used by many other programs.

It does not have certain features even if they are shown in the help like:

--expire-time=x milliseconds parameter is ignored.

on some webpages they say that html can be used in the message, this does not work on this version either

I dont know how to upgrade it ether, it synaptic says it has to uninstall cinnamon as well if I wanna remove this 

this page from 2010 talks about it http://www.webupd8.org/2010/05/finally-easy-way-to-customize-notify.html

I would like to be able to adjust the timeout and size of fonts.

thanks.

**Comment by xenopeek** [comment]
Which Linux Mint version are you using and what desktop environment? If you're unsure check System Info in your menu or run `inxi -S` on the terminal.

**Comment by xenopeek** [comment]
Cinnamon doesn't use notify-osd so the part on that page about changing fonts doesn't apply. Linux Mint 18.3 uses the Ubuntu 16.04 as a package and libnotify-bin version 0.7.6 is available from that, which provides notify-send. This version has support for timeout. I tested with `notify-send -t 2000 "test" "hello world"` and the notification bubble goes away after 2 seconds as expected.
