### ISSUE TITLE
UTF-8 characters not displaying

### ISSUE THREAD

**Issue by myfirstnameispaul** [linuxmint/linuxmint#461]
In 20.2 Cinnamon, I noticed first in Firefox that a UTF-8 character isn't displaying, then can see entire sets of characters in the Character Map do not display.

I checked the following:
```text
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Also, I can see all the language packs are 'Fully installed'.

Here is the initial character I could not see in FF, and can't see anywhere else in Mint:

https://unicode-table.com/en/1F817/

**Comment by xenopeek** [comment]
It means you don't currently have a font installed that has that Unicode character. Few fonts have all or even a majority of the Unicode characters. For this one you can install for example fonts-symbola (through Synaptic Package Manager in your menu, or with command `apt install fonts-symbola`).

I see the same on Linux Mint 20.3 Cinnamon. After installing fonts-symbola (and restarting the program you want to see the character in) the character is displayed as expected.

**Comment by myfirstnameispaul** [comment]
Thank you.

I installed `fonts-symbola` and didn't even have to restart and everything immediately works in running apps.
