### ISSUE TITLE
Keyboard shortcut does not trigger the command "xfce4-popup-windowmenu"

### ISSUE THREAD

**Issue by manojbaishya** [linuxmint/linuxmint#462]
As stated in the title, if a keyboard shortcut is assigned to the command: `xfce4-popup-windowmenu`, and the key combination is pressed, then the pop-up menu does not show. However, if I use the terminal or the appfinder to execute it, it works as expected. I had commented the same at https://gitlab.xfce.org/xfce/xfce4-panel/-/issues/22, but there has been no response. I am not familiar with C development, otherwise I would have contributed.

**Comment by user95f85f** [comment]
uh. I can't get xfce4-popup-windowmenu to do anything even in a terminal.
Sounds like you need the .... panel plugin on your panel first?

**Comment by manojbaishya** [comment]
Please refer to https://gitlab.xfce.org/xfce/xfce4-panel/-/merge_requests/68, https://gitlab.xfce.org/xfce/xfce4-panel/-/commit/b082990032326c792249d155bd1b2145b66b21a6 and https://gitlab.xfce.org/xfce/xfce4-panel/-/issues/22, the issue has been fixed.

**Comment by manojbaishya** [comment]
> uh. I can't get xfce4-popup-windowmenu to do anything even in a terminal. Sounds like you need the .... panel plugin on your panel first?

Yes. First we need to place the plugin on the panel and then execute the shell command.
