### ISSUE TITLE
Updating fails

### ISSUE THREAD

**Issue by hman2** [linuxmint/linuxmint#465]
Today, updating Mint (Tara) stopped working. There are two updates slated: firefox 96.0.1+linuxmint1-tricia -> 96.0.2-linuxmint1+tricia and policykit-1 0.105-20ubuntu0.18.04.5 -> 0.105-20ubuntu0.18.04.6.

First, I got a command line window containing a complaint that the backend process was already running (not true). After that, update doesn't do anything, and when I click Refresh, I get the notice that I have 1 defective packet. In order to show this I shall use the filter "defect". There is no "filter" function in the update tool, and no "defective"...

Inxi:
inxi -Fxxrzc0
System:    Host: FSC-neu Kernel: 5.4.0-96-generic x86_64 bits: 64 gcc: 7.5.0
           Desktop: Cinnamon 3.8.9 (Gtk 3.22.30-1ubuntu4) dm: lightdm
           Distro: Linux Mint 19 Tara
Machine:   Device: desktop System: FUJITSU product: ESPRIMO P910 serial: N/A
           Mobo: FUJITSU model: D3162-A1 v: S26361-D3162-A1 serial: N/A
           BIOS: FUJITSU // American Megatrends v: V4.6.5.3 R1.23.0 for D3162-A1x date: 12/01/2014
           Chassis: type: 6 v: C$PXW6 serial: N/A
CPU:       Quad core Intel Core i5-3470 (-MCP-)
           arch: Ivy Bridge rev.9 cache: 6144 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 25543
           clock speeds: min/max: 1600/3600 MHz 1: 3551 MHz 2: 3426 MHz
           3: 3411 MHz 4: 3525 MHz
Graphics:  Card: Intel Xeon E3-1200 v2/3rd Gen Core processor Graphics Controller
           bus-ID: 00:02.0 chip-ID: 8086:0152
           Display Server: x11 (X.Org 1.19.6 )
           drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1920x1200@59.95hz
           OpenGL: renderer: Mesa DRI Intel HD Graphics 2500 (IVB GT1)
           version: 4.2 Mesa 20.0.8 (compat-v: 3.0) Direct Render: Yes
Audio:     Card-1 Intel 7 Series/C216 Family High Def. Audio Controller
           driver: snd_hda_intel bus-ID: 00:1b.0 chip-ID: 8086:1e20
           Card-2 GN Netcom
           driver: USB Audio usb-ID: 003-002 chip-ID: 0b0e:0315
           Sound: Advanced Linux Sound Architecture v: k5.4.0-96-generic
Network:   Card: Intel 82579LM Gigabit Network Connection (Lewisville)
           driver: e1000e v: 3.2.6-k port: f080
           bus-ID: 00:19.0 chip-ID: 8086:1502
           IF: eth0 state: up speed: 100 Mbps duplex: full mac: <filter>
Drives:    HDD Total Size: 3160.6GB (66.3% used)
           ID-1: /dev/sda model: INTEL_SSDSC2BB16 size: 160.0GB
           serial: <filter>
           ID-2: /dev/sdb model: WDC_WD30EZRX size: 3000.6GB serial: <filter>
Partition: ID-1: / size: 29G used: 27G (96%) fs: ext4 dev: /dev/sda7
           ID-2: swap-1 size: 8.19GB used: 0.00GB (0%)
           fs: swap dev: /dev/sda8
RAID:      System: supported: N/A
           No RAID devices: /proc/mdstat, md_mod kernel module present
           Unused Devices: none
Sensors:   System Temperatures: cpu: 76.0C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Repos:     Active apt sources in file: /etc/apt/sources.list.d/official-package-repositories.list
           deb http://packages.linuxmint.com tara main upstream import backport
           deb http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse
           deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse
           deb http://archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse
           deb http://security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
           deb http://archive.canonical.com/ubuntu/ bionic partner
           Active apt sources in file: /etc/apt/sources.list.d/opera-stable.list
           deb https://deb.opera.com/opera-stable/ stable non-free #Opera Browser (final releases)
           Active apt sources in file: /etc/apt/sources.list.d/teamviewer.list
           deb https://linux.teamviewer.com/deb stable main
Info:      Processes: 247 Uptime: 3 days Memory: 4793.2/15887.3MB
           Init: systemd v: 237 runlevel: 5 Gcc sys: 7.5.0 alt: 4.8/5
           Client: Shell (bash 4.4.201 running in gnome-terminal-) inxi: 2.3.56

Selecting only Firefox for update yields a notice that gir1.2-polkit-1.0 would be installed, but clicking Ok leads to - nothing. Having only policykit selected yields to nothing at all...

Update protocol lists these updates performed today (!): libpolkit-backend-1-0, policykit-1, libpolkit.gobject-1-0, libpolkit-agent-1-0, Opera browser and Firefox...

Thanks
hman

**Comment by hman2** [comment]
I found that I could no longer start Synaptic, not even as another user. Also, those other users could no longer do sudo... This lead me to believe that Polkit might have been rendered dysfunctional, so I did 
sudo apt-get check
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Probieren Sie »apt --fix-broken install«, um dies zu korrigieren.
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 gir1.2-polkit-1.0 : Hängt ab von: libpolkit-agent-1-0 (= 0.105-20ubuntu0.18.04.5) aber 0.105-20ubuntu0.18.04.6 ist installiert
                     Hängt ab von: libpolkit-gobject-1-0 (= 0.105-20ubuntu0.18.04.5) aber 0.105-20ubuntu0.18.04.6 ist installiert
E: Unerfüllte Abhängigkeiten. Versuchen Sie »apt --fix-broken install« ohne Angabe eines Pakets (oder geben Sie eine Lösung an).

So there were unmet dependencies. As instructed I did

sudo apt --fix-broken install

which installed gir1.2-polkit-1.0. After that (and a Refresh) I could commence with the two slated updates... Looks like the "backend" that was allegedly running wasn't an updater, apt or Synaptic - but Polkit...

Now it seems as if the system would be running again...

**Comment by xenopeek** [comment]
Good that you solved it yourself. For troubleshooting such problems do use the [support forums](https://forums.linuxmint.com/). GitHub is for reporting bugs, not for getting help with troubleshooting. See our [troubleshooting guide](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/when.html).

**Comment by hman2** [comment]
Sorry, at first it did look like a bug. Detailed analysis showed the underlying culprit was a sudo command running (fstrim) in the background. I though that sudo would not occupy Polkit, or only for the very moment when then superuser password is entered/checked. But the error message isn't hepful at all, and users without knowledge of the command line would have no means to get out of this situation.

May I repeat
"I get the notice that I have 1 defective packet. In order to show this I shall use the filter "defect". There is no "filter" function in the update tool, and no "defective".." That could be considered a bug. There is no filter "defect", actually, no filter function exists at all. So this error message needs correction, IMHO.

Thanks
