### ISSUE TITLE
Where to report Thunderbird issues?

### ISSUE THREAD

**Issue by hman2** [linuxmint/linuxmint#466]
Sorry for asking it here. I didn't find anything on https://www.linuxmint.com/getinvolved.php that would point me there.

You have announced a partnership with Mozilla. To my knowledge, currently only Firefox falls under that, Thunderbird is not (yet) released unter that. Synaptic tells me my Thunderbird on my Mint 19.1 (Tara) is 1:91.5.0+build1-0ubuntu0.18.04.1, which would imply reporting it at Ubuntu. But if you are now in the process of adapting Thunderbird, you might want not integrate the (lesser) bug that is currently there.

It's not a big thing, no show stopper, merely a nuisance.

When you fetch new e-mail from a POP3 inbox, Thunderbird now only says that it contacts the server. You can wait endless, it wond't fetch a single mail, even if there is mail waiting on the server, you don't even get a message if there is no mail.

But if you click Fetch a second time, Thunderbird will download all e-mails (or present the mesage if no unfetched mail is waiting).

So not really a bug, and a workaround is there (click Fetch a second time), so in ITIL speak this would be a "known error".

Thanks

**Comment by xenopeek** [comment]
Correct; Thunderbird on Linux Mint currently comes from the Ubuntu package base repository and it is not packaged or maintained by Linux Mint. Clem has previously answered on the blog that this is something the developers may consider in the future but have not looked at yet: https://blog.linuxmint.com/?p=4244#comment-270545. Bugs would be fixed upstream at Thunderbird in that case.

If there is a bug in the Ubuntu maintained version you could report it to the Ubuntu maintainer, and check first whether somebody else has already reported similar: https://launchpad.net/ubuntu/+source/thunderbird/+bugs?orderby=-id&start=0. But as you say it's not really a bug it's perhaps better discussed with Thunderbird community https://www.thunderbird.net/en-US/get-involved/ and get confirmation from other users that they see the same as you describe and get clarity whether it is working as intended or not. I don't know, I don't use Thunderbird.

For help with troubleshooting this (getting confirmation from other users, figuring out if it is as intended) you can also use the Linux Mint [support forums](https://forums.linuxmint.com/). That is a good first stop. If you search for Thunderbird you'll find several members have reported some issue with the new Thunderbird version though at first glance I don't see one the same as you describe.  See also our [troubleshooting guide](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) for the why/when/what/where/how of reporting bugs.
