### ISSUE TITLE
Add python3 to repository

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/linuxmint#467]
`python3` on ubuntu LTS is really outdated. The latest on `una` is `3.8.10`, but Python upstream is at 3.10. Could you distribute `python3` in the repository?

**Comment by xenopeek** [comment]
python3.9 is available from the package base repository. If you need python3.10 (or python3.11) you can add the PPA ppa:deadsnakes through Software Sources and afterwards you can install those. See: https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa?field.series_filter=focal

And please—while it's fine to install multiple Python versions alongside each other—don't replace your default Python versions (that is, leave the file /usr/bin/python3 alone). OS components have a hard dependency on the default Python version being what it is. New Python versions—refer to the release notes—often have changes that break older code. You can use version numbers in the hashbang line (e.g., #!/usr/bin/python3.10) of your own programs to specify which Python version to use. Better yet, use virtualenv for development. This lets you set up a Python environment isolated from your OS's.

**Comment by Secret-chest** [comment]
> python3.9 is available from the package base repository. If you need python3.10 (or python3.11) you can add the PPA ppa:deadsnakes through Software Sources and afterwards you can install those. See: [launchpad.net/~deadsnakes/+archive/ubuntu/ppa?field.series_filter=focal](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa?field.series_filter=focal)
> 
> And please—while it's fine to install multiple Python versions alongside each other—don't replace your default Python versions (that is, leave the file /usr/bin/python3 alone). OS components have a hard dependency on the default Python version being what it is. New Python versions—refer to the release notes—often have changes that break older code. You can use version numbers in the hashbang line (e.g., #!/usr/bin/python3.10) of your own programs to specify which Python version to use. Better yet, use virtualenv for development. This lets you set up a Python environment isolated from your OS's.

Thanks. I use virtualenv already.
