### ISSUE TITLE
mintsources: proxy settings are ignored

### ISSUE THREAD

**Issue by oz42** [linuxmint/linuxmint#469]
System: LMDE 4 (debbie)

root@lmde:~# env|grep -i oxy
https_proxy=http://185.46.212.92:80
HTTPS_PROXY=http://185.46.212.92:80
HTTP_PROXY=http://185.46.212.92:80
http_proxy=http://185.46.212.92:80

Configured that way because it is impossible to add a normal proxy address to the system the normal way: I can only choose "none" or "auto".

As proxy settings are ignored, /usr/bin/mintsources is unusable to update the system. No problems with apt or dselect.

I already had reported that a while ago for the "normal" Linux Mint, but I cannot find the bug here. Anyway, it is still not fixed, so LM is unusable in a corporate environment.

**Comment by xenopeek** [comment]
You had reported this previously on the mintsources project: https://github.com/linuxmint/mintsources/issues/206. Closing it here as duplicate.

It might be helpful if when the LMDE 5 beta is available, you could re-test on that to confirm whether it is reproducible. Expected this quarter. Announcement will be on https://blog.linuxmint.com/ when it is available.
