### ISSUE TITLE
Cursor freeze again on new kernel 4.15.0.29-31

### ISSUE THREAD

**Issue by beeshyams** [linuxmint/linuxmint#47]
Issue reported [earlier](https://github.com/linuxmint/linuxmint/issues/21) continues with the latest kernel 4.15.0.29-31  installed today. As mentioned earlier , all kernels to date (starting from Beta) have another problem - cursor freezes on suspend / hibernate. Back to stable 4.15.0-23

Please advise if you need any information to help trouble shoot along with steps (newbie here). System config (`inxi -Fxxrzc0` output in linked bug report )

**Comment by xenopeek** [comment]
This may be a regression issue specific to your hardware or it may be a more general regression issue. I suggest you ask for help with troubleshooting / finding workaround by posting a new topic on the [support forum](https://forums.linuxmint.com/).
