### ISSUE TITLE
Too errors when updating linux-firmware

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#473]
An update is failing today. linux-firmware 1.187.27 package doesn't install, there are a lot of dependencies errors about libglib2.0.-0:i386 and update stops because of too many errors.

![Capture d’écran du 2022-03-05 18-40-52](https://user-images.githubusercontent.com/3955499/156894527-3d4de31c-3edd-4473-841c-843bd43bdd20.png)

Linux Mint Cinnamon 20.3.

**Comment by xenopeek** [comment]
For help with troubleshooting problems you can use the support forums. I recommend opening a new topic, but there look to be several maybe related topics:
https://forums.linuxmint.com/viewtopic.php?f=47&t=369218
https://forums.linuxmint.com/viewtopic.php?f=90&t=369140
https://forums.linuxmint.com/viewtopic.php?f=47&t=368457

**Comment by InfoLibre** [comment]
Thank you. I typed sudo dpkg --configure libc6:i386 and it works now.
Wouldn't it possible to add this command in next automatic update for all normal users who don't even know what is a terminal?
