### ISSUE TITLE
Use LibreWolf instead of Firefox as Default Browser

### ISSUE THREAD

**Issue by Ryu945** [linuxmint/linuxmint#475]
Note:  I don't know if this is the correct Linux Mint Github for this conversation.

LibreWolf is a fork of Firefox.  Unlike most forks, it is kept up to date with security patches from Firefox.   It is essentially Firefox configured with best practices for security and privacy.   Base Firefox default configurations are horrible and people have to waste time configuring it or worse, don't bother to edit configuration at all.   In addition to editing the default settings with best practices, it removes all phone home coding built into the browser and analytics collection.   

As some of you are aware, Firefox now puts unique identifiers in the installer of Firefox.   It also removes pointless features that need to phone home like pocket.  It installs uBlock by default.   With all these background processes removed, a side by side comparison of LibreWolf vs Firefox has LIbreWolf using 30 MB less in RAM when doing the exact same activities.  I don't see any downside to using LibreWolf.  Only benefits.  Here is a link to their repository and website.

https://gitlab.com/librewolf-community

https://librewolf.net/

Maintenance can be easy as you wouldn't have to make a custom version.   Just deploy the base version of LibreWolf.   It has many packaging options.

**Comment by xenopeek** [comment]
Thanks for making a suggestion for Linux Mint! Your suggestion is clear. As per the [way of working](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html#why-are-ideas-and-feature-requests-closed) it is closed here.

FYI, Linux Mint entered a partnership with Mozilla early this year https://blog.linuxmint.com/?p=4244.
