### ISSUE TITLE
Mint 21: mirror issue

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/linuxmint#480]
Please replace `mint.mirrors.telekom.ro` in the recommended mirrors list with `mint.mirrors.orange.ro` as the company hosting the mirrors got renamed

**Comment by xenopeek** [comment]
Thanks for reporting! There are some other pending mirror changes, we'll add this one to the list and update the mirrors list this week.

I noted the ISO download mirror http://mint.mirrors.orange.ro/iso/ wasn't on the mirrors list yet so we'll add that one as well.
