### ISSUE TITLE
gvim "Gtk-CRITICAL" errors in shell after recent update

### ISSUE THREAD

**Issue by kruthers64** [linuxmint/linuxmint#485]
After a recent update I noticed that gvim is generating the following errors in the shell:
```
(gvim:48152): Gtk-CRITICAL **: 10:11:18.799: gtk_notebook_get_tab_label: assertion 'list != NULL' failed

(gvim:48152): Gtk-CRITICAL **: 10:11:18.799: gtk_notebook_get_tab_label: assertion 'list != NULL' failed
```

I reported it to the vim project but they suggested it might be a problem with linux mint having an incompatible version of GTK installed along with `vim-gtk3`.  My system is fully up to date and has `libgtk-3-0` version 3.24.20, but the vim project was not seeing the error and had libgtk-3 version 3.24.30, presumably on ubuntu.

You can see that issue report here if you want: https://github.com/vim/vim/issues/10271

Here's how to recreate the problem:
```
> sudo apt install vim-gtk3
> gvim --clean -p *.py     # or something matching several files
# now close gvim and you'll see that error for every file
```
This is mostly a nuisance but it would be nice to reduce clutter in the shell.

Some info about my system:
```
DISTRIB_DESCRIPTION="Linux Mint 20.3 Una"
Linux hostname 5.13.0-40-generic #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
system is fully up to date

**Comment by mtwebster** [comment]
Looks like it was fixed here:
https://gitlab.gnome.org/GNOME/gtk/-/commit/b1d5de78e1f73f26f741d6c6043a644889c3008f

That was in 3.24.**19** but it's not in 3.24.20, or 3.24.30. It's also not patched in 3.24.33 shipped in Ubuntu 22.04. It *is* patched in gtk's main branch.

I really couldn't tell you what the deal is here. Regardless, we don't usually touch major toolkits like this that we inhereit from Ubuntu, so unless they fix it for 20.04, Mint 20 won't be fixed either.

I tried gvim in Ubuntu 22.04 and there are no more warnings (despite the patch not being applied). So, Mint 21 will fix it, but until then it's harmless except for the spam.,
