### ISSUE TITLE
Improve LUKS prompt at boot

### ISSUE THREAD

**Issue by canepan** [linuxmint/linuxmint#489]
Hi, currently when I boot my encrypted installation of LMDE5, I see a Linux Mint prompt, with no indication the request is for my encrypted disk password (rather than the one for my login user).
I think changing the icon to something hinting to an encrypted disk would help the user experience.
After a chat on IRC with orcus, I agree having a message (which would require localization) is too much effort for this simple change, but something like [these](https://duckduckgo.com/?t=ffab&q=encrypted+disk+icon&iax=images&ia=images) could help

**Comment by monsta** [comment]
I recall there should be a message there if you have `plymouth-label` package installed...

**Comment by canepan** [comment]
Good news, then: do I need to regenerate initrds after installing it?

**Comment by monsta** [comment]
I think it should work right after installing it.

**Comment by canepan** [comment]
No changes in the boot prompt

**Comment by monsta** [comment]
Ok, I experimented with it myself, it turned out that you need to update initramfs after all.
```
$ sudo update-initramfs -t -u -k all
```
And actually, `plymouth-label` is already installed by default. I recall it wasn't installed in LMDE 5 beta though - did you originally install the beta?

**Comment by canepan** [comment]
No: I installed LMDE4 and used the upgrade tool to go to LMDE5.
I am updating the initramfs now: I'll report back after the reboot

**Comment by canepan** [comment]
That was it: after rebuilding, there is a prompt under the icon.
I think that works, and since it should be installed by default, the issue is resolved in LMDE5.

Thank you!

**Comment by monsta** [comment]
No problem :slightly_smiling_face: 

It could be that `plymouth-label` wasn't installed in LMDE 4 indeed... I looked at mintupgrade - it should've installed it in the process (https://github.com/linuxmint/mintupgrade/commit/9fafe7ee03c879f04138e4f68ea492ad2d4cc709), but maybe something went wrong.
