### ISSUE TITLE
Mint 19 won't install under VirtualBox

### ISSUE THREAD

**Issue by windyweather** [linuxmint/linuxmint#49]
what linux distro you are running (plus version number if applicable) **LM 19 x64**
    the version of Cinnamon you are running (output of cinnamon --version from the terminal, or git/nightlies) **unknown - system won't run far enough for that. Whatever LM 19 was shipping with as of 27 July 2018**
    what theme/applets you were using (if relevant) **Unknown**
    how exactly we can reproduce the error
**On Win 10 using VirtualBox 5.2.12, create virtual machine with 4GB RAM, 40GB virtual HD, 128MB Graphics memory, 3D enabled., Paravirtualization enabled, on Ryzen 1800x system with 32GB Ram.

Using LM 19 x64 Live DVD  installed in virtual optical drive, boot system.** 

    what you expected to happen
**Install should work properly in a Virtual BOX VM. I'm using LM 18.3 and have used LM this way for many years and releases.**
    what actually happened
**System appears to be booting. Specter warning appears, Count down appears and counts down. Then
screen goes to SNOW. Waving mouse over the screen causes the SNOW to change, so system is apparently working, but GRAPHICS are completely messed up.**

    whether the problem happens consistently or intermittently
**CONSISTENT. No way to use the system at this point.**

[LM 19 Ryzen.zip](https://github.com/linuxmint/linuxmint/files/2238345/LM.19.Ryzen.zip)
![crys_00357](https://user-images.githubusercontent.com/4505159/43361113-8f8e3b18-927b-11e8-8337-d3b06eba0f6e.png)

Thanks a ton, I hope to be using LM 19 soon with my VMs.

**Comment by mtwebster** [comment]
Switch to a tty and back (hold down your vbox host key, then F2, then switch back the same way F7)

This is a known glitch with the live cd in virtualbox.  That should fix the graphics.

**Comment by xenopeek** [comment]
This is a known issue with the Cinnamon 19v2 ISO. Alternative workaround is to once you get the glitched screen (after you hear the login sound) to select Input > Keyboard > Insert Ctrl-Alt-Backspace in your VM. This takes you back to the login screen with the issue fixed. Login as user "mint" with blank password if on the LiveISO.
