### ISSUE TITLE
ubiquity: Installing onto a previously encrypted device makes encryption mandatory

### ISSUE THREAD

**Issue by DirkHaar** [linuxmint/linuxmint#5]
This is related package is ubiquity, but I don't find where to issue an issue there.
I installed 18.3 Cinnamon 64 overwriting an older version on a flash drive, without a repartition.
The "Who are you" dialogue then had "encrypt my personal data"  checked but greyed out so it was not possible to deselect it, as can be seen in the attached screenshot.
I may find it reasonable that "encryption" should be checked by default in such a case, but don't find any reason why I shouldn't be able to uncheck it when overwriting the whole drive.

![ubiquity_error_installation_who_are_you](https://user-images.githubusercontent.com/12502925/36401371-5fd985f6-15d7-11e8-9667-eb0e3f634a4e.png)

Edit:
"Meine persönliche Daten verschlüsseln"="encrypt my personal data"

**Comment by xenopeek** [comment]
If /home isn't being deleted during the install and a directory "dirk" already existed there with home directory encryption enabled, I'd assume Ubiquity is saying "you can't use the username dirk unless you know his password for home directory encryption".
