### ISSUE TITLE
Wrong french keyboard when installing Linux Mint MATE 19

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#50]
When I install Linux Mint MATE 19, the default keyboard proposed for "Français" is "Français - Français (variante obsolète)".
But it's not the good keyboard because with this keyboard, ² key and SHIFT+² keys write this :

![capture du 2018-07-29 17-29-08](https://user-images.githubusercontent.com/3955499/43367922-28956960-9355-11e8-83ed-f9461ba5d32a.png)

The default keyboard should be "Français - Français (azerty)" :

![good-keyboard](https://user-images.githubusercontent.com/3955499/84588729-350b1680-ae2a-11ea-834b-19aa92fe7eb0.png)

**Comment by Petrouchka** [comment]
I just tested lubuntu, no problem, the default keyboard is "Français - Français (variante)".
Strange that it is "Français - Français (variante obsolète)" in Linux Mint MATE.

**Comment by Petrouchka** [comment]
Where can I report this bug ? I understand nothing on this ugly page : https://help.ubuntu.com/community/ReportingBugs

**Comment by Petrouchka** [comment]
The answer from Canonical (jeff@canonical.com) :

**Comment by Petrouchka** [comment]
I made a bugreport ifor ubiquity package : https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1807344

**Comment by InfoLibre** [comment]
It will not be fixes as Ubiquity is now unmaintained, and replaced by Calamares starting with Ubuntu 24.04 LTS.
