### ISSUE TITLE
whatsapp-desktop unmaintained?

### ISSUE THREAD

**Issue by moh-eulith** [linuxmint/linuxmint#503]
Way back in 2019, the [original](https://github.com/Enrico204/Whatsapp-Desktop) coder for whatsapp-desktop abandoned the project. Linux mint started using a fork (which fork?), as per issue #104. The issue tracker is [listed](https://mint.pkgs.org/19.3/mint-import-amd64/whatsapp-desktop_0.6.1_amd64.deb.html) as https://github.com/linuxmint/linuxmint/issue.  

There is now a critical bug (first character repeating), which is being plastered all over the [reviews](https://community.linuxmint.com/software/view/whatsapp-desktop) for this package, with forum [complaints](https://forums.linuxmint.com/viewtopic.php?f=47&t=377966&p=2206666&hilit=whatsapp#p2206666), etc.

When was the last release (0.6 was in 2019, 3 years ago, so I assume 0.6.1 can't be that new)? Is this package maintained? Where is the code? Is this the correct issue tracker? If the code is on github, why is the code specific issue tracker not being used?

**Comment by Maksons** [comment]
Any news ??
Problem still exist.

**Comment by kkaasinen** [comment]
And now my whatsapp client shows only the empty screen with text "fully encrypted" and no messages can be seen... no help with uninstall - reinstall...

**Comment by clefebvre** [comment]
Confirmed, the repo version no longer works. I removed the package from the repositories.

I had a look in the software manager, there are 5 different whatsapp clients available via Flatpak.

Whatsie in particular seems to be fast and can be maximized properly.

**Comment by Secret-chest** [comment]
I use ZapZap.

**Comment by kkaasinen** [comment]
Whatsie is fast and easy to use. However - after week usage there is now some update problem: written messages don't leave and sync is somehow unreliable... edit: app remove and  reinstall seemed to help.
