### ISSUE TITLE
Do not use a Microsoft platform

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#507]
Why not use a Gitlab repository instead of Github?
https://framagit.org/public/projects
etc.

**Comment by Secret-chest** [comment]
GitHub is better for collaborative things

**Comment by Secret-chest** [comment]
Why nos self-host it?

**Comment by JosephMcc** [comment]
Github suits are purposes just fine for now.

**Comment by InfoLibre** [comment]
I wasn't talking about functionalities but about freedom.
https://www.androidkult.com/github-ferme-les-comptes-des-developpeurs-russes/
https://www.developpez.com/actu/330165/GitHub-restaure-le-compte-du-dev-qui-a-intentionnellement-corrompu-ses-bibliotheques-certains-developpeurs-estiment-que-la-suspension-etait-deraisonnable-puisqu-il-s-agissait-de-son-propre-code/

**Comment by InfoLibre** [comment]
Or Microsoft can modify Linux Mint source code as they want, you will not see it. They already did worse :
https://www.nouvelobs.com/rue89/rue89-economie/20110318.RUE1353/tunisie-microsoft-complice-de-la-censure-numerique-par-ben-ali.html
https://www.jeuneafrique.com/mag/398099/societe/tunisie-confession-dun-tortionnaire-regime-de-ben-ali/

**Comment by Secret-chest** [comment]
> Or Microsoft can modify Linux Mint source code as they want, you will not see it. They already did worse :
> https://www.nouvelobs.com/rue89/rue89-economie/20110318.RUE1353/tunisie-microsoft-complice-de-la-censure-numerique-par-ben-ali.html
> https://www.jeuneafrique.com/mag/398099/societe/tunisie-confession-dun-tortionnaire-regime-de-ben-ali/

WTF? Will the commit be hidden?

**Comment by InfoLibre** [comment]
https://www.lemondeinformatique.fr/actualites/lire-sous-pression-gitlab-recule-sur-la-suppression-des-depots-inactifs-87611.html
