### ISSUE TITLE
Upgrade to LM21 - Upgrade tool missing for LM 20.3

### ISSUE THREAD

**Issue by viveksreedharan88** [linuxmint/linuxmint#508]
Hi. As LM 21 is released, I see so many articles talking about upgrade tool to help on the upgrade to LM 21. Practically, I don't see it available on LM 20.3. Will it be rolled out via repository? Should we install it by ourselves? Do we have any timelines for the upgrade instructions?

**Comment by Jeremy7701** [comment]
See [https://blog.linuxmint.com/?p=4358](https://blog.linuxmint.com/?p=4358) - "Upgrade Instructions"

Probably a week or so?

**Comment by viveksreedharan88** [comment]
Blog just says shortly. Nobody knows how long is that "shortly" 🤣
