### ISSUE TITLE
In the prefered applications, the file manager is empty

### ISSUE THREAD

**Issue by Petrouchka** [linuxmint/linuxmint#52]
In Linux Mint MATE 19, in the preferred applications :

- The file manager is empty, we need to manually choose Caja :

![image](https://user-images.githubusercontent.com/3955499/43368059-360d42b4-9357-11e8-9510-0d70aa1dced9.png)

- Onboard must be manually selected and Orca doesn't appears :

![image](https://user-images.githubusercontent.com/3955499/43368060-38f3c282-9357-11e8-85f2-4f155f9e0196.png)

https://github.com/mate-desktop/caja/issues/580

**Comment by clefebvre** [comment]
Fixed.
