### ISSUE TITLE
Can't join a hidden file to a Thunderbird mail, CAJA doesn't show hidden files

### ISSUE THREAD

**Issue by Petrouchka** [linuxmint/linuxmint#53]
I'm writing a new mail and I want to join a hidden file (the file is beginning with a dot).

The CAJA window that opens shows only normal files, not hidden files that begin with a .
So, I can't join a hidden file to my mail.

The window should show all files, including hidden files.

Is it a GTK bug/Caja bug/MATE bug/Linux Mint bug ?

https://bugzilla.mozilla.org/show_bug.cgi?id=1151096
https://github.com/mate-desktop/caja/issues/399

**Comment by smurphos** [comment]
Ctrl-H. Not much point in a hidden file if it's visible by default eh?

**Comment by Petrouchka** [comment]
Impossible to join a hidden file :

![capture du 2018-07-29 18-19-39](https://user-images.githubusercontent.com/3955499/43368359-0f4a93c0-935c-11e8-8610-172e7664cd4a.png)

**Comment by smurphos** [comment]
Doesn't Ctrl-H toggle displaying hidden files on that dialogue? It should.

**Comment by Petrouchka** [comment]
No, it doesn't work.

**Comment by JosephMcc** [comment]
This isn't a Linux Mint issue. The file dialog is provided by gtk. Control + H should show hidden files. You should be able to show the text field to be able to type a a file name by using Ctrl + L. In any case, we can't do anything about this.

**Comment by Petrouchka** [comment]
Where could I report this bug ?

**Comment by JosephMcc** [comment]
First, double check that the methods listed above don't work. Either hotkey for showing the hidden files, or for showing the entry and typing the hidden files should work. If they don't, you likely need to report it against gtk.

**Comment by Petrouchka** [comment]
CTRL-H doesn't work and if I don't see the hidden files, I don't know their name and can't type it.
I will look at GTK.
