### ISSUE TITLE
Add Memtest86+ in Linux Mint GRUB menu

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#535]
Hello,

Memtest86+ final version is out: https://memtest.org
Could you add it in the GRUB next Linux Mint version?

**Comment by tethragon** [comment]
I agree! this could be a very useful addition!

**Comment by andreamtp** [comment]
Memtest86+ v.6.0 is now compatible with UEFI, so it could be nice - if possible - to upgrade the embedded release and to make it avail for uefi as well

**Comment by InfoLibre** [comment]
Adding Hardware Detection Tool in GRUB menu would be very useful too. With Hardware Detection Tool, you can test the material before installing Linux Mint. You can see if it's a 32 or 64 bit processor etc.
Hardware Detection Tool was removed because not maintained anymore. If someone could continue this project, it would be nice.
https://web.archive.org/web/20161116220610/http://hdt-project.org/raw-attachment/wiki/hdt-0.5.0/hdt-0.5.2.iso

**Comment by InfoLibre** [comment]
There's a project similar to Hardware Detection Tool: https://wiki.ubuntu.com/FirmwareTestSuite/FirmwareTestSuiteLive
If it is better than Hardware Detection Tool, could you add it to the live cd?
