### ISSUE TITLE
Impossible to associate applications with the opening of some of the media

### ISSUE THREAD

**Issue by Petrouchka** [linuxmint/linuxmint#54]
In CAJA in Linux Mint MATE 19, it's impossible to associate :

- Calibre -> e-book reader :
![image](https://user-images.githubusercontent.com/3955499/43368189-d10a959e-9359-11e8-9624-218cab70e4e1.png)

- Clementine -> audio CD :
![image](https://user-images.githubusercontent.com/3955499/43368194-ef765ae0-9359-11e8-993d-3cf7d8be449e.png)

- Clementine -> audio DVD :
![image](https://user-images.githubusercontent.com/3955499/43368198-fb5aaf14-9359-11e8-8d53-38e1c708d69b.png)

- Brasero -> blank CD :
![image](https://user-images.githubusercontent.com/3955499/43368208-067b0ad8-935a-11e8-9618-3af032dd3bed.png)

- Brasero -> blank Blu-Ray :
![image](https://user-images.githubusercontent.com/3955499/43368209-1579cf38-935a-11e8-9bf5-a8162a527e63.png)

- VLC -> HD DVD :
![image](https://user-images.githubusercontent.com/3955499/43368215-1df0052e-935a-11e8-8d18-5e18096b7a80.png)

- VLC -> Blu-Ray :
![image](https://user-images.githubusercontent.com/3955499/43368217-242e8852-935a-11e8-9c41-ed6b7c4e1221.png)

- VLC -> video HD DVD :
![image](https://user-images.githubusercontent.com/3955499/43368219-2b65716c-935a-11e8-8140-5ca1a0abe05e.png)

https://github.com/mate-desktop/caja/issues/581
https://github.com/mate-desktop/caja/issues/569
https://github.com/clementine-player/Clementine/issues/5417

**Comment by xenopeek** [comment]
I'm closing this issue as it is something Caja developers and assorted applications developers/maintainers would need to work on, which is also where you reported it on connected issues. Thanks for taking the time to do so.

I took a quick look at Linux Mint 19.3 MATE but I'm sorry to say the file management preferences dialog of Caja looks to not work any better than when you reported this. The Other Media selection box especially, it never finds any applications.

The Preferred Applications settings found in Control Center do work and there you can set Clementine or VLC as default music or video player and Calibre as default document reader. It's less granular though.
