### ISSUE TITLE
mesa 20.0.5 which is default for Linux Mint 21 (and 21.1 beta) causes artifacts in desktop for at least Radeon 5600XT gpus

### ISSUE THREAD

**Issue by tethragon** [linuxmint/linuxmint#540]
**Mesa 20.0.5** drivers cause strange artifacts (AMD Radeon 5600XT) for some apps like gimp or libreoffice, but NOT in others like firefox, chrome. Also these artifacts appear on the desktop icons as well. Please see attached screenshots

![uky18108cnp91](https://user-images.githubusercontent.com/39238674/205681912-b71f5c28-018b-4792-97a5-af8d59bb0987.jpg)

![upnav008cnp91](https://user-images.githubusercontent.com/39238674/205681943-121e3ee9-8478-4c7d-82f0-93df9c57b4cb.jpg)

Issue is resolved after upgrading mesa drivers (using oibaf ppa). I use now **mesa 23.0.0** and there are no artifacts. This ppa is a little "dangerous" to break the system, so maybe mint team should consider to use an updated mesa driver for the default installation.

see also: https://gitlab.freedesktop.org/mesa/mesa/-/issues/4811

**Comment by clefebvre** [comment]
Fixed in 22.2. Hopefully it will get backported to Ubuntu 22.04.
