### ISSUE TITLE
No suitable icon set in LibreOffice if Mint is switched into Dark Mode

### ISSUE THREAD

**Issue by Isolator70** [linuxmint/linuxmint#544]
A clean install of Linux Mint Cinnamon 21.1 has no icon set for LibreOffice "on board" which are suitable for Dark Mode.

If user switches system to dark mode via "Mint Welcome" or in the "Themes", he will notice a lot of invisible icons if he uses LibreOffice applications like Calc.

--> So Mint lacks a suitable Icon set for Dark Mode of LibreOffice.

![Bildschirmfoto vom 2023-01-01 17-32-11](https://user-images.githubusercontent.com/35434137/210181525-dcd38d15-fed9-45dd-a281-c0407c451d59.png)

Remark: I could not find a more specific location to addres this (old) issue - if it is misplaced here, please move it if possible, thanx.

**Comment by anaximeno** [comment]
Install the package **libreoffice-style-yaru** with:

```
apt install libreoffice-style-yaru
```
Then close and reopen LibreOffice and chose the new icon theme.

More icon themes can also be installed on the system, search for them using:

```
apt search libreoffice-style-*
```

**Comment by Isolator70** [comment]
> Install the package **libreoffice-style-yaru** with:
>
> ```
> apt search libreoffice-style-*
> ```

Hi anaximeno, thanks for your reply, but that's not the point here - there are some more Icon sets which more or less support Dark mode.

But look what Linux Mint wants to be (excerpt from linuxmint.com):

"What is Linux Mint?

Linux Mint is an operating system for desktop and laptop computers. **It is designed to work 'out of the box'** and comes fully equipped with the apps most people need."

So in my opinion - as the Welcome screen directly offers the Dark Mode to the user, Linux Mint should really be ready for that and bring a suitable icon set along as standard ;-)

**Comment by clefebvre** [comment]
Continued at https://github.com/linuxmint/mint21.2-beta/issues/30.
