### ISSUE TITLE
Blue Yeti Snowball USB microphone is not recognized 

### ISSUE THREAD

**Issue by wujastyk** [linuxmint/linuxmint#55]
The USB microphone is seen (red light on mic) but the USB connection is not recognized properly and the microphone does not show up in Sound settings or in Pulseaudio pavucontrol. 

Same result on two Thinkpad T500s and a T560, all running Linux 4.15.0-29-generic amd64 and the new Cinnamon 19, updated today.

Dominik

**Comment by xenopeek** [comment]
For help with troubleshooting this please use the forums. See also our [troubleshooting guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/). If during troubleshooting the responsible component is found to be one maintained by Linux Mint this issue can be reopend with those details.

**Comment by wujastyk** [comment]
I did read through the Troubleshooting pages before posting here, and I couldn't identify where this issue should be reported.  That's why I posted here.  I'm an end-user, and this seems to be a problem that could be caused by any number of different parts of the system  (alsa, pulse, usb, kernel).  I don't know how to narrow it down to a particular component.  Sorry!
