### ISSUE TITLE
My Code Doesn't Just Loop Forever, it Crashes Linux Mint

### ISSUE THREAD

**Issue by smileynet000** [linuxmint/linuxmint#551]
Don't know where the issue is, don't know which component it is, but I believe in this case, it shouldn't freeze the system enough to not be able to use it, and lock it up. I'm working on troubleshooting, to make sure it isn't what I'm asking the computer to do, and it probably is, and can probably be fixed by making my code correct. But an infinte loop, is expected, not a system wide crash. The program shouldn't be able to do damage like that. I understand that my code has trouble, but it's hard to fix, when I need to keep restarting the system. Not good for the computer, either. I ask that you fix, whatever the reason is, while I fix my error too, trying to get around the crash, and certainly, trying to make it do as I really intended.

Here is the raw code:

---
VERSION TVOID 1
EXTMODE TVOID 1

ALOAD TNUMBER 1
VSTORE TVOID 0V

WHILEBB TVOID 0V

VLOAD TNUMBER 0
ATOC TVOID 0V
ALOAD TNUMBER 4
SWITCH TVOID 0V
EQU TVOID 0V

IF TVOID 0V
IFBEGIN TVOID 0V

BREAK TVOID 0V

IFEND TVOID 0V
ENDIF TVOID 0V
EIF TVOID 0V

VLOAD TNUMBER 0
PRINTLN TVOID 0V

VLOAD TNUMBER 0
INC TVOID 0V
VSTORE TNUMBER 0 ; ++i

WHILEBBE TVOID 0V
LOOP TVOID 0V

VLOAD TNUMBER 0
ATOC TVOID 0V
ALOAD TNUMBER 10
SWITCH TVOID 0V
VSTORE TNUMBER 0
LSS TVOID 0V   ; i < 10

ELOOP TVOID 0V
WHILEBBB TVOID 0V

QUIT TVOID 0

END TVOID 0V
---

This is MY language, my development version not yet on github. As soon as you tell me you want to work on it, I'll be happy to give up the code of the interpreter, by posting on github. It's when this code is executed on my interpreter, that it doesn't work, and crashes the computer. It's supposed to print:

---
1
2
3
---

Even IF, it's really my problem, and the code shouldn't be able to be executed in this pattern, I ask that you still fix it so it doesn't crash the system, even if you need to prevent it from running this specific code, in this specific pattern, and throw an error instead. I do ask though that while doing that, you do NOT block code that's OK to be executed. That way, the problem is easier for me to troubleshoot. I'm using a version down from the latest of Linux Mint, upgraded once, from some version I forgot. It was an inline upgrade, or so. Please help, if you can, and I'll keep trying to make my code more correct, in a way that finds it's way around the issue somehow. Thanks!

**Comment by smileynet000** [comment]
Appearently, the reason my program didn't work, is because I had the wrong syntax of my whileb loop (essentially a do...while loop). I have fixed it, and fixed the bug, but I still don't think it should have crashed the whole OS, when it was a problem. So while I'm not saying things have to be perfect, you might want to consider it, or not, maybe. Just didn't want to ignore it entirely, in this case.

**Comment by smileynet000** [comment]
The correct code is:
---
VERSION TVOID 1
EXTMODE TVOID 1


ALOAD TNUMBER 1
VSTORE TVOID 0V

WHILEBBB TVOID 0V

VLOAD TNUMBER 0
ATOC TVOID 0V
ALOAD TNUMBER 4
SWITCH TVOID 0V
EQU TVOID 0V

IF TVOID 0V
IFBEGIN TVOID 0V

BREAK TVOID 0V

IFEND TVOID 0V
ENDIF TVOID 0V
EIF TVOID 0V


VLOAD TNUMBER 0
PRINTLN TVOID 0V

VLOAD TNUMBER 0
INC TVOID 0V
VSTORE TNUMBER 0 ; ++i

WHILEBBE TVOID 0V
LOOP TVOID 0V

VLOAD TNUMBER 0
ATOC TVOID 0V
ALOAD TNUMBER 10
SWITCH TVOID 0V
VSTORE TNUMBER 0
LSS TVOID 0V   ; i < 10

ELOOP TVOID 0V
WHILEBB TVOID 0V

QUIT TVOID 0


END TVOID 0V
---

You should fix it, so that there's not that vunerability. In the meantime, while that's being fixed somehow, whatever causes the bug, I'll try and figure out how to disallow this code to run. I bet most won't do it on purpose, but some people may commonly make this mistake, so it's therefore, something that while you try to guard against it, so should I for now. If I need help figuring out how to disallow it, I'll check back here. When I do figure out how to disallow it, I'll check back too, if I can. Thanks!

**Comment by drewwalton19216801** [comment]
I am very confused.

**Comment by smileynet000** [comment]
This is app specific, but i feel whyever it crashes system, it shouldnt. If needed, i would suggest that if problems cant be solved another way, app specific code should be added.

Remember c++ do...while loop? Thats basically what the code is suppossed to do. However, the programmer (me) got the syntax wrong. It basically is like putting an open brace at the end, where the while keyword goes. My code, executes anyway, and it crashes the system by freeze. You cant just kill the app. It wont let you control it.

I should disallow that to run too. Its nonsense. But i dont know how yet. I just thought an app crash, with nice message, you cant do...would be nice, rather than no useable system after this.

**Comment by smileynet000** [comment]
I have updated versions, but the bug is there still...

**Comment by Jeremy7701** [comment]
Suggest you run it in a small VM, so that if you run a broken version which crashes, you can just restart the VM.

**Comment by smileynet000** [comment]
If thats the fix you want ok. Just didnt want you to not know. When there,
i will work on it from my side. Its just difficult. Maybe if i make a
higher layer pass through PNFASM? Cant wait for others to use this program!

**Comment by mtwebster** [comment]
Unless there is some specific issue in Linux Mint and you can provide concrete information on it, this is just nonsense and has no reason to be here.
