### ISSUE TITLE
VLC do not run anymore

### ISSUE THREAD

**Issue by ttsoares** [linuxmint/linuxmint#553]
# apt install vlc

The following additional packages will be installed:
  libvlc-bin libvlc5 libvlccore9 libvncclient1 vlc-bin vlc-data vlc-l10n vlc-plugin-access-extra
  vlc-plugin-base vlc-plugin-notify vlc-plugin-qt vlc-plugin-samba vlc-plugin-skins2 vlc-plugin-video-output
  vlc-plugin-video-splitter vlc-plugin-visualization

$ vlc
VLC media player 3.0.16 Vetinari (revision 3.0.13-8-g41878ff4f2)
[000055fd2656b640] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[000055fd26650bd0] skins2 interface error: cannot instantiate dialogs provider
[000055fd26600c30] main playlist: playlist is empty
[000055fd26650bd0] [cli] lua interface: Listening on host "*console".
VLC media player 3.0.16 Vetinari
Command Line Interface initialized. Type `help' for help.
> 

Also the Kmag app do not run anymore presenting the same error.

**Comment by Jeremy7701** [comment]
VLC is a GUI program, not a CLI program.
Try running it from the menu

**Comment by ttsoares** [comment]
I only tested via CLI after it stops working from the menu.

The menu uses: /usr/bin/vlc --started-from-file %U
   that still not run it

First time _ever_  in all distros I used that vlc stop working...

**Comment by Jeremy7701** [comment]
Works for me.
I tried opening it in nemo against a mp4 film and it played.

**Comment by ttsoares** [comment]
How about you try to run kmag?
Anyhow, here is a fully updated 21.1 and I do not mess up with the PPAs.
The issue seem to be related with the KDE environment.

**Comment by mtwebster** [comment]
Maybe https://askubuntu.com/questions/1033472/vlc-media-player-not-working-no-interface?

**Comment by ttsoares** [comment]
Yes. Did all that some days ago... the result still is:

$ vlc -v
VLC media player 3.0.16 Vetinari (revision 3.0.13-8-g41878ff4f2)
[00005576f971e640] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[00005576f9802a20] main interface warning: cannot load module `/usr/lib/x86_64-linux-gnu/vlc/plugins/gui/libqt_plugin.so' (/usr/local/lib/libQt5Gui.so.5: undefined symbol: z_adler32, version Qt_5)
[00007f3188030b60] main generic warning: cannot load module `/usr/lib/x86_64-linux-gnu/vlc/plugins/gui/libqt_plugin.so' (/usr/local/lib/libQt5Gui.so.5: undefined symbol: z_adler32, version Qt_5)
[00005576f9802a20] skins2 interface error: cannot instantiate dialogs provider
[00005576f97b3ce0] main playlist: playlist is empty
[00005576f9802a20] [cli] lua interface: Listening on host "*console".
VLC media player 3.0.16 Vetinari
Command Line Interface initialized. Type `help' for help.
> quit
Shutting down.

And:
dpkg -S libQt5Svg.so.5
zoom: /opt/zoom/libQt5Svg.so.5
libqt5svg5:amd64: /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5.15
zoom: /opt/zoom/libQt5Svg.so.5.12
libqt5svg5:amd64: /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5.15.3
zoom: /opt/zoom/libQt5Svg.so.5.12.10
libqt5svg5:amd64: /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5

**Comment by ttsoares** [comment]
It could be because that QT library is coming from the Zoon app and not from the Mint libraries environment ?

I have here:
/opt/calibre/lib/libQt5Svg.so.5
/opt/zoom/libQt5Svg.so.5
/usr/local/lib/libQt5Svg.so.5
/usr/lib/x86_64-linux-gnu/libQt5Svg.so.5

But:
dpkg --list libqt5svg5

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name             Version      Architecture Description
+++-================-============-============-=================================
ii  libqt5svg5:amd64 5.15.3-1     amd64        Qt 5 SVG module

**Comment by mtwebster** [comment]
That *definitely* could be it - QT libraries of a given version need to be use with companion libraries they were built against.  An undefined symbol is a clear indicator (I would have mentioned sooner if I'd known this).

**Comment by ttsoares** [comment]
Any suggestion about how to run Zoon and VLC in the same system ?

**Comment by mtwebster** [comment]
`/usr/local/lib/libQt5Svg.so.5` - this is the one that's maybe causing issues. The others (calibre and zoom) are in paths that shouldn't interfere.

Try renaming that one - things in /usr/local can 'mask' identically named files in /usr

**Comment by mtwebster** [comment]
You may need to run `sudo ldconfig` also

**Comment by ttsoares** [comment]
SOLVED:
I just removed all the lib* files in /usr/local/lib as those files do not belong to any package.
If some app complains about it I will deal with that.

Now VLC is running fine again.

Thank you mtwebster 8-)

**Comment by ttsoares** [comment]
SOLVED.

**Comment by mtwebster** [comment]
Ah cool.

Files like that usually only end up in /usr/local when you build things yourself - by default, the installation prefix is /usr/local for build systems (meson and autotools at least) - you usually want to run with some sort of `--prefix=/usr` option to keep that from happening.

In *most* distributions, files installed by your package manager (like apt) are installed in /usr.  'They' say not to install there when you build something locally, but I usually do, because it avoids situations like this one - I know there's only one available copy of file xxx. Reinstalling the package version will typically clean it all up for you anyhow. Also, in Cinnamon, and most gnome-based environments, things are expected to be under /usr, never under /usr/local. /opt is a better place to put things if you need to supply your own library files, etc...
