### ISSUE TITLE
Kernel 5.19 incompatible with nVidia video drivers

### ISSUE THREAD

**Issue by bshanteau** [linuxmint/linuxmint#555]
Linux Mint 21.1 Cinnamon and XFCE, current stable releases, nVidia video cards (620, 710 & 1650)

Kernel 5.19 appeared today (Jan 16, 2023) in Update Manager->View->Linux Kernels

After installation and reboot, got black screen with flashing cursor.

Rebooted with 5.15 kernel and used Driver Manager to remove nVidia driver & install Nouveau driver. After rebooting with 5.19 kernel display was OK.

Conclusion is that kernel 5.19 is incompatible with nVidia video drivers.

**Comment by clefebvre** [comment]
This is usually the case with new kernel. It takes Ubuntu a bit of time to update proprietary drivers to support the new series.
