### ISSUE TITLE
Kernel 4.15.0.29.31 breaks resume on Mint 19

### ISSUE THREAD

**Issue by luk-f-a** [linuxmint/linuxmint#56]
**Issue**: after updating to kernel 4.15.0.29.31 resume from suspend stops working properly. Concretely, the system suspends correctly, but upon resume the user has been logged on (not just screen locked). All applications have been closed and running "last" on the command line shows the user has just logged in. Also, the "welcome to mint" screen is shown. Running "uptime" command does not show the system as having been shut down (it shows uptime over 1 day), so all signs point to suspend + log out.

**Troubleshooting**: using timeshift I rolled back all updates for the last week. Problem disappeared. Then, I applied all updates except kernel update. Problem still gone. My conclusion is that kernel 4.15.0.29.31 update creates the problem (at least in Mint, I cannot say it's definitely an upstream problem).

**Expected behaviour**: find all applications still open after resume.

**System**: Mint 19 64-bits, cinnamon 3.8.8, kernel 4.15.0-20-generic. 1 week fresh install.

**Comment by xenopeek** [comment]
For help with suspend issue please use the forum. Such issues and regressions are generally specific to hardware used + kernel version.

**Comment by luk-f-a** [comment]
for anyone that arrived here looking for a solution, I've found more details here:
https://unix.stackexchange.com/questions/440540/read-error-on-swap-device
https://bbs.archlinux.org/viewtopic.php?id=235027

It's reported to be a problem with kernel 4.15 (and only fixed in 4.17).
