### ISSUE TITLE
Banned on the IRC

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/linuxmint#561]
I'm banned on the IRC please unban me thanks (karl)

**Comment by Xmetalfanx** [comment]
wrong place for this.   Ban was for flooding the IRC rooms AND ban evading

**Comment by carlosmintfan** [comment]
ban evading, why not? You please do not hate me

**Comment by carlosmintfan** [comment]
Hehehe same as rqcras

**Comment by carlosmintfan** [comment]
themachine djph xmetal hehehe

**Comment by carlosmintfan** [comment]
Wrong place? Unban me

**Comment by carlosmintfan** [comment]
Should I join discord?
How can I lock this conversation?

**Comment by carlosmintfan** [comment]
Can only mint do that?

**Comment by carlosmintfan** [comment]
@Xmetalfanx I pasted links after the code!

**Comment by carlosmintfan** [comment]
@clefebvre Should I show the history? Can't take a bit of a nuisance? hehe

**Comment by carlosmintfan** [comment]
@Xmetalfanx unban me and then I'll close this

**Comment by carlosmintfan** [comment]
@Xmetalfanx Maybe check your gh repos? I opened an unban issue there too! And - you banned my IP or what? Why can't I evade now like before?

**Comment by carlosmintfan** [comment]
https://github.com/Xmetalfanx/website/issues just check if you don't what it
