### ISSUE TITLE
Can I join chat rooms/mailing lists? :)

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/linuxmint#563]
Dear Clem,

on projects.linuxmint.com you talk about the #linuxmint-dev IRC channel, but that channel doesn't exist anymore or was made private. Is there any mailing list/IRC channel/Slack where you developers talk with each other that I can join?

Regards,

“carlosmintfan”

**Comment by mtwebster** [comment]
After today? Not likely.
