### ISSUE TITLE
Minimum brightness capped at 3%

### ISSUE THREAD

**Issue by Rudxain** [linuxmint/linuxmint#565]
After I upgraded to LM 21, the brightness no longer resets to a hard-coded value. Now the OS actually remembers the last value. But the problem is, when I set it to 0%, then reboot, it sets itself to 3%. Is this an intentional "safety" feature? (to prevent the display from being too dark to see)

Device: Dell Inspiron 15R 5521

**Comment by kilanmundera** [comment]
Did you find out how to apply this setting ?

**Comment by Rudxain** [comment]
@kujac
> Did you find out how to apply this setting ?

I've only ever used the brightness slider and the keyboard hotkeys. However, there's a hardware-specific alternative: `/sys/class/backlight/intel_backlight/brightness`
