### ISSUE TITLE
LibreOffice is the default for 'documents' but dotx files open in Calibre (though I have not reproduced the problem on a fresh install of Mint)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/linuxmint#567]
Mint 21.1. Cinnamon.
Calibre 5.0.1.
LibreOffice 7.5.0.3 (installed via .debs).

My 'document' open-with preference is set to LibreOffice Writer. And I tried the 'reset to default' option. Yet, docx files open in Calibre.

Cf. #523.

**Comment by LinuxOnTheDesktop** [comment]
I seem to have found the following solution.

1) Use Mint's Settings -> Preferred Applications to change the 'Office' -> 'Word' setting to something other than LibreOffice Writer.

2) Change that same setting back to Writer.

If that method fails, one might try removing

`application/vnd.openxmlformats-officedocument.wordprocessingml.document;application/vnd.ms-word.document.macroenabled.12;`

from /usr/share/applications/libreoffice7.5-writer.desktop. (Adjust for one's version of Writer.)

Is this a Mint bug? Or should I file a report against Calibre ([here](https://bugs.launchpad.net/calibre))?

**Comment by Jeremy7701** [comment]
When you decided to install:
LibreOffice 7.5.0.3 (installed via .debs).

Where did you get the deb packages from?
I'm guessing it wasn't a version released by Mint?

**Comment by LinuxOnTheDesktop** [comment]
I got the LibreOffice packages from [here](https://www.libreoffice.org/download/download-libreoffice/?type=deb-x86_64&version=7.4.5&lang=en-US) (and specifically I used the 'fresh' version). I try to use the latest version of LibreOffice because I need the best possible compatibility between Impress and PowerPoint.

**Comment by Jeremy7701** [comment]
Loading upstream packages has its risks.
I'd suggest testing in a VM before going live.

**Comment by LinuxOnTheDesktop** [comment]
> Loading upstream packages has its risks.

But is the use of upstream packages to be blamed for the present problem? Perhaps what ought to be changed is something in Mint or perhaps something in Calibre.

> I'd suggest testing in a VM before going live.

What I do is: use PowerPoint, on Windows, to create slides; check that, when running Impress on Mint, the slides display as intended (and sometimes at this stage I had to alter the slides); give the presentation, using Impress on Mint.

**Comment by LinuxOnTheDesktop** [comment]
I can no longer reproduce the problem (on Mint 21.1 Cinnamon).
