### ISSUE TITLE
pulse audio bug

### ISSUE THREAD

**Issue by Cyrus666** [linuxmint/linuxmint#57]
Hi there,
every time I use USB soundcard on mint 18.3, on the next boot there is no sound output devices available.
The only solution is to leave the soundcard in the USB port, or to delete /home/.config/pulse and then restart

**Comment by xenopeek** [comment]
For help with troubleshooting please use the Linux Mint forums. See also our [troubleshooting guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/). If during troubleshooting the responsible component is found to be one maintained by Linux Mint this issue can be reopend with further details.
