### ISSUE TITLE
Monitor doesn't rotate before login.

### ISSUE THREAD

**Issue by umikali222** [linuxmint/linuxmint#575]
I'm on Linux Mint 21.1, and I have 1 display. I made the only monitor, a vertical monitor. When I turn on my PC, the LM logo and the login screen are displayed as if the monitor was set to rotation landscape. I don't really blame the LM logo on any one of you, because I think it's just an overlay for systemd, but the login screen should be fixed.

**Comment by theksp** [comment]
Linux Mint uses lightdm as a default display manager.
here is a solution 
https://askubuntu.com/questions/408302/rotated-monitor-login-screen-needs-rotation

Also another solution
https://unix.stackexchange.com/questions/419755/how-to-detect-built-in-laptop-display

Try and experiment with **arandr**
you can install it in linux to get a GUI for editing.
