### ISSUE TITLE
Firefox forced restart

### ISSUE THREAD

**Issue by jmssil** [linuxmint/linuxmint#577]
In Linux Mint, when either the Update Manager updates Firefox or Firefox updates itself, a restart of Firefox is forced upon the user, leading to loss of data and all inconvenience related to tabs crashing.

Firefox support claims this is not how Firefox is developed, that it is configured to force a restart by Linux Mint. Can this be fixed? It's the only apps that forces a restart.

**Comment by Jeremy7701** [comment]
Why should Firefox update itself?
If I need to update Firefox, via the update manager, I shut Firefox down first, losing no data.
I would do this even if claims are made that it is unnecessary.
A browser has a lot of connections to data, caches and miscellaneous software.

**Comment by mtwebster** [comment]
You should get a prompt in firefox, in a new tab, telling you to restart the browser:
![restart](https://user-images.githubusercontent.com/262776/235330545-3db0ddb2-6fed-4a5e-8542-e3a60cdbd7d9.png)

I test these new versions before we release them, I've never *not* gotten this prompt. You can still go back to other tabs and work or save things or whatever after this pops up, though I'm not sure I'd rely on it to remain stable indefinitely - you should restart as soon as you can probably.

We don't modify anything in Firefox, we only package it, the same version you can download directly from them.

**Comment by jmssil** [comment]
OK, so it's an upstream behavior. Yes, I get the message in a new tab, but it's still disrupting. Nowadays browsing consists in having lots of tabs, temporary tabs, etc.

**Comment by johnsa777** [comment]
This is not a closed issue! These forced restarts are very disruptive. I've been in calls that now are interrupted because I can't do anything. Website data is lost on restart!

**Comment by jmssil** [comment]
I stopped using Firefox due to this issue. I haven't used it for several months now. I'm now using Google Chrome, which does not show the same behavior. I am also now experimenting Ubuntu Cinnamon instead of Linux Mint to see what are the main differences.

**Comment by Jeremy7701** [comment]
Updates to a browser are never desperately urgent.
If it's such a massive task to restart a browser, apply your firefox updates next time you restart your GUI.
A delay of a few hours isn't going to matter.
Note that, as a default, your system checks for program updates every 2 hours.

**Comment by mtwebster** [comment]
It's a closed issue for us, since _we have no control over this behavior_. Just don't update, put it off until it's less disruptive.

If auto updates are enabled, add firefox to your 'blocked packages' list, then switch to the Automation tab, and export that list. You can then remove it from the blocked packages tab, and firefox will show up in the updates list, but won't be automatically updated.

https://support.mozilla.org/en-US/kb/file-bug-report-or-feature-request-mozilla

**Comment by jmssil** [comment]
You seem to suggest that the way to fix one issue that occurs with just one program between thousands is to modify system behavior which has been working without any issues for maybe ten years. I disagree. I think the correct way is to fix the misbehaving app. Of course if, for simply stubbornness or resentment, users are saying that the behavior of that app is OK, then it's more likely that the developers will say people are not complaining.

You also seem to suggested that Linux Mint does not change the source code of any package that is included in the distro. It's certainly not the case.

If you'd say that you don't care for the users and are not going to make any effort to fix this specific issue because you don't feel like it, then that would be logical, although a bit too autistic. OCD or selfish. But don't try to convince people that this is an adequate behavior.

It's a shame that regular developers despise user's feedback. Most users just take advantage of FOSS and don't give anything back. If you stop to think, most users that do provide feedback are contributing and in some cases also developing in a FOSS philosophy.

But your egos are stronger than reason and you preferer to make it a "problem between chair and screen" instead of contributing upstream to fix an issue which is relevant.

And, spare the speech that we only use it if we want... that's not a very intelligent reasoning. And of course I can use what I want, that's why after providing feedback and trying to make software better I had to give up and use alternatives.

**Comment by JosephMcc** [comment]
@jmssil Don't you think that's a bit dramatic? All @mtwebster said was that Mint doesn't actually control it. He also laid out a way for users to work around it if they are bothered by it. Your attitude doesn't fit anything that was said here.

**Comment by jmssil** [comment]
Dramatic or not, I think my points make sense. My attitude comes from considerable experience of reporting issues and having developers always considering them an attack instead of a contribution.

If Firefox had a bug that removed all user files would Mint package it without applying a patch? Would not Mint developers report that to Mozilla?

My reaction, although harsh, is solid. But I'm open to be convinced otherwise. I apologize for the drama but it's exhausting.

**Comment by Jeremy7701** [comment]
@jmssil - I found your contribution to be rude and insulting to the developers.

**Comment by jmssil** [comment]
@Jeremy7701, I'd be interested to know which sentences are rude and insulting, because all I can see are logical arguments which have been completely ignored, focusing on the "drama" aspects. Feel free to reach me directly, because I take matters seriously. When I say that I am capable of being convinced otherwise I'm not being hypocritical. My conclusions are taken from observation of people behavior in software development and I've obviously made many mistakes myself during all these years.

**Comment by mtwebster** [comment]
We no longer modify Firefox. It's important to users _and Mozilla_ that they get the same experience whether installing via APT or downloading from their website while using Mint.

> If Firefox had a bug that removed all user files would Mint package it without applying a patch? Would not Mint developers report that to Mozilla?

**We're not discussing a bug here.** This is the intended behavior of Firefox. Your arguments should be made to Mozilla, via the link I provided above.
