### ISSUE TITLE
A new Local Community has appeared...

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/linuxmint#579]
It seems someone made a Romanian website and forum for Linux Mint (<https://linux-mint.ro>). Could you add it to the website @clefebvre ?

**Comment by clefebvre** [comment]
No, it's taken our website and made a copy of it. That's not OK. We can promote local communities, not websites which make it look like they're Linux Mint.

**Comment by Secret-chest** [comment]
> No, it's taken our website and made a copy of it. That's not OK. We can promote local communities, not websites which make it look like they're Linux Mint.

Can you somehow email the author?
