### ISSUE TITLE
Flatseal is now using libadwaita!

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/linuxmint#580]
It's an essential tool! Can we fork it?

WHAT IS THIS ABOMINATION???
![image](https://user-images.githubusercontent.com/74449186/236297471-47be8fec-641b-4674-b0a4-db6e222fdf5d.png)

<details><summary>the meaning of life</summary>
<p>
gnome is the worst
</p>
</details>

**Comment by mtwebster** [comment]
'It's ugly' is not really a good reason to fork this. It's a configuration tool for flatpaks only, and one that most people won't ever need, even those that do run flatpaks.

**Comment by Secret-chest** [comment]
Can't we make it an XApp or something? I find it very bad with libadwaita. And flatpak is getting more popular, like it or not.

**Comment by Secret-chest** [comment]
Alternaively, we can make our own.
