### ISSUE TITLE
Adding Hardware Detection Tool in GRUB menu

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#594]
Adding Hardware Detection Tool in GRUB menu would be very useful. With Hardware Detection Tool, you can test the material before installing Linux Mint. You can see if it's a 32 or 64 bit processor etc.
Hardware Detection Tool was removed because not maintained anymore. If someone could continue this project, it would be nice.
https://github.com/abandonware/abandonware.github.io/issues/7

There's a project similar to Hardware Detection Tool: https://wiki.ubuntu.com/FirmwareTestSuite/FirmwareTestSuiteLive

**Comment by InfoLibre** [comment]
Hardware Detection Tool is again in GRUB menu of Linux Mint Cinnamon 21.3, thank you.

**Comment by elevatorguy** [comment]
Saw this today not knowing how it all works; guessing yall packaged a standalone efi file.
