### ISSUE TITLE
Removable USB storage devices doesn't appear anymore when installing LM Cinnamon in VirtualBox

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#595]
I'm installing Linux Mint Cinnamon 21.2 in a new VirtualBox VM, using an ISO live installation image mounted in the virtual CD-ROM. As I want to take screenshots and save them on a USB key during the installation, I mount my USB key on the VM. VirtualBox says it's mounted but in fact, the USB key isn't mounted in Linux Mint, it doesn't appear on the desktop nor in Nemo:

![Capture d’écran du 2023-07-14 12-16-08](https://github.com/linuxmint/linuxmint/assets/3955499/39c6f3d4-d416-4bd3-b614-76464c5d3252)

I tried with several USB keys, same problem. It's a regression since LM 21.2.

VirtualBox version 6.1.38_Ubuntu r153438 installed in Linux Mint Cinnamon 21.1.

**Comment by Jeremy7701** [comment]
Since the VM has no OS until you have finished installing Mint, how can you mount a USB to anything?
You could use a windowed VM and take your screenshots in the host machine, though.

**Comment by InfoLibre** [comment]
The VM has an OS, it's a live installation ISO. So, I first start Linux Mint in the VM, from the live ISO. Then I mount the USB key before beginning the installation.

**Comment by InfoLibre** [comment]
It works now, I don't know if the LM updates in the VM solved it or if it was a VirtualBox problem.
