### ISSUE TITLE
Mpv installed with flatpak not opening any videos in linux mint

### ISSUE THREAD

**Issue by amix3** [linuxmint/linuxmint#596]
The expected behavior is that when I install mpv in linux mint using flatpak, mpv opens videos.

The actual behavior is that when you install mpv using flatpak on any linux mint device mpv doesn't open any videos and it gives no useful log or errors on why it's not opening the video. this only happens in linux mint.

This is a reproducible issue that happens on linux mint 21.1 and 21.2 and can be tested by installing the flatpak version of mpv and opening any videos with it.

Also i noticed that when I run mpv flatpak as sudo it can open videos but not when I run it as a user  so i guess this can be a permission issue or something like that.
(sudo -i && flatpak run io.mpv.Mpv video.mp4)

**Comment by amix3** [comment]
I just noticed something ,
When i run the video with --no-audio flag it runs fine.
So I think the problem could be related to audio servers on linux mint.

**Comment by amix3** [comment]
As I found a workaround/fix for this, I'm gonna close this issue.
The fix is to pass the flag --ao=pulse to mpv so it would use pulse audio instead of pipewire.

**Comment by Jeremy7701** [comment]
What's wrong with using the non-flatpak version?

**Comment by amix3** [comment]
Well, first of all it's a little bit old.
And I get frame drops while watching videos with the deb version. So i usually use the flatpak version.
