### ISSUE TITLE
Able to login without password

### ISSUE THREAD

**Issue by nthpyrodev** [linuxmint/linuxmint#598]
Using Mint 20.3 Cinnamon.

I got into my Linux account without the password.
How it happened, (probably not possible to reproduce?):
1. Power on laptop.
2. Selected second account.
3. Don't input anything in the box, click the arrow and log in.
4. Attempt to open an application, a box appears saying "Login keyring did not get unlocked at login". Attempting to input the correct password does not work.
5. Clicking cancel will close and then reopen the box. After 3-7 clicks (varies each time) on the cancel button, the popup will not reopen and you can now open and use applications.

**Comment by theksp** [comment]
Did you change your password after installation ?

I think your original password during the installation is the keyring!
Try to enter that password.
