### ISSUE TITLE
impossible to install shim-signed in 18.3

### ISSUE THREAD

**Issue by matejcik** [linuxmint/linuxmint#6]
Couldn't find a better place to report, so hopefully this is the right place.

So.

Sylvia repo has `shim-signed` at version `1.32~16.04.1+0.9+1474479173.6c180c6-1ubuntu1+linuxmint1`.
This depends on `shim (= 0.9+1474479173.6c180c6-1ubuntu1)`.
But that doesn't exist anywhere. It might have existed in xenial-updates at some point maybe? But then an update to `shim` was released and it broke.
Now my options are either to downgrade to xenial version `1.12+0.8-0ubuntu2` which pulls shim 0.8, or upgrade to xenial-updates, but that requires the full updated grub2 stack, which is pain to install btw. (and renames the boot entry to "Ubuntu")

I'm not sure, but it seems to me that without `shim-signed` I won't be able to use SecureBoot, so I'm reluctant to risk it.

**Comment by xenopeek** [comment]
I hope you were able to resolve this on your own. That package is included on the ISO. As per `apt policy shim` run from the live session:
```
shim:
  Installed: (none)
  Candidate: 13-0ubuntu2
  Version table:
     13-0ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
     0.9+1474479173.6c180c6-1ubuntu1 500
        500 cdrom://Linux Mint 18.3 _Sylvia_ - Release amd64 20171213 xenial/main amd64 Packages
     0.8-0ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages
```
I don't have a secure boot installation here with this release. Closing this for now. If anybody has the same issue and can reproduce it this issue can be reopened.

**Comment by olisteadman** [comment]
Here's me starting boot-repair on Live instance of Mint 18.3:
[output1.txt](https://github.com/linuxmint/linuxmint/files/2668017/output1.txt)

Here's me following the boot-repair instructions and encountering the shim-signed error described above by @matejcik:
[output2.txt](https://github.com/linuxmint/linuxmint/files/2668020/output2.txt)

I can confirm the same error still showed even when trying again after each of the following recommended solutions found elsewhere online:
sudo apt-get autoremove 
sudo apt-get -f install 
sudo apt install synaptic
sudo apt-get download dpkg
sudo apt-get update && sudo apt-get upgrade
[sudo apt purge shim; sudo apt update; sudo apt install shim](https://askubuntu.com/questions/1083902/grub2-common-breaks-shim-13-but-0-91474479173-6c180c6-1ubuntu1-is-instal)
sudo apt purge shim; sudo apt update; sudo apt install shim-signed 
[sudo rm /var/cache/debconf/*.dat](https://askubuntu.com/questions/971240/dpkg-error-processing-package-shim-signed)

Can we reopen the issue @xenopeek?

**Comment by matejcik** [comment]
> I hope you were able to resolve this on your own. That package is included on the ISO. As per `apt policy shim` run from the live session:

try `apt policy shim-signed` maybe?

**Comment by olisteadman** [comment]
@matejcik I'm not sure what I'm looking for with the output - here it is, can you help guide me?

ubuntu@ubuntu:~$ apt policy shim-signed
shim-signed:
  Installed: 1.37~18.04.3+15+1533136590.3beb971-0ubuntu1
  Candidate: 1.37~18.04.3+15+1533136590.3beb971-0ubuntu1
  Version table:
 *** 1.37~18.04.3+15+1533136590.3beb971-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1.34.9.2+13-0ubuntu2 500
        500 cdrom://Ubuntu 18.04.1 LTS _Bionic Beaver_ - Release amd64 (20180725) bionic/main amd64 Packages
     1.34.9+13-0ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages

**Comment by matejcik** [comment]
Ah, I think I see.

Here's the key output from your install logs:
```
The following packages have unmet dependencies:
 shim-signed : Depends: shim (= 0.9+1474479173.6c180c6-1ubuntu1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
My original problem is that the particular version `0.9+1474479173.6c180c6-1ubuntu1` could not be found anywhere.
(i have since upgraded to Mint 19 which doesn't have this problem anymore)
Per @xenopeek's comment, it's the version from Mint 18.3 ISO.

So maybe it's on the ISO but not in the online repos? Which would make sense - it's an unmodified Ubuntu version so presumably Mint archives won't have it, but perhaps Ubuntu updated their version and no longer have it either?

A second question is how I managed to lose the version from the ISO in the first place. But I still think that this is a bug - there's a requirement on a particular version that can't be found anywhere but the ISO.

**Comment by olisteadman** [comment]
In the end I just cut out shim-signed from the list of items to be installed, and then everything resolved. boot-repair was able to run through to completion, and I was able to restart into a stable installation. Tried it again straight after, and the same method got the same end result. Maybe we don’t need shim-signed after all?

**Comment by olisteadman** [comment]
In the end I just **cut out shim-signed from the list** of items to be installed, and then everything resolved. 

`boot-repair` was able to run through to completion, and I was able to restart into a stable installation. 

I tried it again straight after, and the same method got the same end result.

Maybe we don’t need shim-signed after all?

**Comment by gilbertohasnofb** [comment]
> In the end I just cut out shim-signed from the list of items to be installed, and then everything resolved.

After fighting with this issue for hours I came along your comment and it's all resolved in a matter of minutes now. Thanks for sharing your solution, I really appreciate it!
