### ISSUE TITLE
Major resolve problems since upgrade to Mint 19

### ISSUE THREAD

**Issue by Bert-de-Jong** [linuxmint/linuxmint#60]
After upgrading to Mint 19, I'm experiencing major (domain) resolve problems.
Roughly 50% of all resolve requests fail, regardless the program/tool.

Some examples:
- `ping google.com` will say "Network is unreachable",
- loading a site in Firefox will say "Unable to connect",
- Evolution will give error messages (about being unable to: load IMAP folders, send emails, etc).

I hope this is the correct place to report this problem.
If you need any information, such as the contents of files, let me know and I'll provide it.

**Comment by Bert-de-Jong** [comment]
Based on what it says [here](https://superuser.com/questions/1153203/ubuntu-17-04-systemd-resolved-dns-lookups-randomly-fail) and [here](https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1682499/), I've already tried uncommenting "DNSSEC=no" in /etc/systemd/resolved.conf and then rebooting, but this doesn't fix the problem.

**Comment by xenopeek** [comment]
For help with troubleshooting please post a new topic on the [support forum](https://forums.linuxmint.com/).

**Comment by Bert-de-Jong** [comment]
In case someone finds this thread and would like to read the forum thread, it's here:
https://forums.linuxmint.com/viewtopic.php?f=150&p=1515887
