### ISSUE TITLE
Mint 19 Cinnamon: Higher battery consumption compared to LM 18.3

### ISSUE THREAD

**Issue by caolislay** [linuxmint/linuxmint#61]
Since I switched from LM18 to LM19 on my laptop, I have noticed a considerable drop of battery performance. Fully charged, I could run my laptop for ~ 3 hours under Linux Mint 18.3. Ever since I did a clean install of LM 19, that duration has dropped to ~ 1.25 hours.

TLP is installed and active with its defaults. As far as I can remember, that was what I did for LM18.

_System = ASUSTeK Computer Inc. 1.0 K53SV
BIOS = K53SV.324
Release = Linux Mint 19 Tara
Kernel = 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64__

Three days ago, I did a clean install of LM 18.3 Cinnamon. Battery lasts ~ 3 hours again, running on a kernel 4.10.x. I updated to 4.15 after two days to check whether that made any difference. It didn't. Laptop runs for 3 hours even on latest kernel.

_System = ASUSTeK Computer Inc. 1.0 K53SV
BIOS = K53SV.324
Release = Linux Mint 18.3 Sylvia
Kernel = 4.15.0-30-generic #32~16.04.1-Ubuntu SMP Thu Jul 26 20:25:39 UTC 2018 x86_64_

Apparently the higher battery usage comes from the changes within the code of LM 19.

**Comment by xenopeek** [comment]
This issue isn't in a state where a developer could do work on it, if the responsible component would be one maintained by Linux Mint. I suggest you ask for help with troubleshooting by posting a new topic on the [support forum](https://forums.linuxmint.com/).

**Comment by caolislay** [comment]
Before I registered this problem, I posted it in the forum. At the time I recorded it as a bug, no-one had replied: https://forums.linuxmint.com/viewtopic.php?f=18&t=274708

Apparently, this has changed in the meantime when I look at the replies now.

I am sorry if the problem is "not in a  state where a developer could do work on it", but I am simply an enduser. I can only state there is a change in the battery consumption, but when it comes to troubleshooting, I need some help. That was the reason I opened this ticket.

In both cases, LM 18 and LM 19 where installed plain vanilla plus Nvidia graphics driver. Whereas the CPU fan in LM 19 never reduced its RPMs, LM 18 reduces it more or less instantly. That, in my opinion is a potential reason for the higher battery consumption.

Possible other reasons for different behaviour:
Cinnamon 3.8 (improved snappiness, Vsync, screen tearing)

I appreciate any advice on how to troubleshoot and how to narrow down possible reasons

**Comment by xenopeek** [comment]
The best place to get help with troubleshooting an issue, so that you can bring it to a point where a developer (Linux Mint or upstream responsible component) could work on it, is the forums. There are many more knowledgeable people active on the forums than there are Linux Mint developers. See our [troubleshooting guide](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) for more info. 

If you don't get a response to your topic on the forums you can edit it (try clarifying the request for help, and info, etc.) and/or use the bump topic option to bring it to renewed attention.
