### ISSUE TITLE
Chromium packages - remove dependency on "pulseaudio" package

### ISSUE THREAD

**Issue by phd** [linuxmint/linuxmint#627]
Chromium packages for Mint ~~Victoria~~ Virginia depend on the "pulseaudio" package.
However they work perfectly fine* with pipewire ("pipewire" and "pipewire-pulse" packages from later versions of Ubuntu, instead of "pulseaudio").

*) when installed with<br>`dpkg --ignore-depends=pulseaudio ...`

Is it possible to relax this dependency on "pulseaudio" in Chromium packages to allow users to replace pulseaudio and experiment with pipewire?

Seems like the dependency should say "**libpulse0**" instead of "pulseaudio".
This is what the package actually depends on, and this way it works fine with both pulseaudio and pipewire.

**Comment by phd** [comment]
Bump. It's a trivial fix.

**Comment by phd** [comment]
> the dependency should say "**libpulse0**" instead of "pulseaudio".

Debian does it in this exact way:
https://packages.debian.org/trixie/chromium

**Comment by mtwebster** [comment]
Done, should be reflected in the next major release (121.0, near end of January).
