### ISSUE TITLE
[BUG] polkit configuration issues for remote users

### ISSUE THREAD

**Issue by Lanchon** [linuxmint/linuxmint#629]
polkit allows users to be treated differently when they are accessing remotely versus locally.

when this is done (if ever), this should be the exception rather than the rule, and should be well justified on a case-by-case basis.

for example, it could be argued that a remote user should not be able shutdown a system, as they might be unable to turn it back on remotely. for me this is bullocks, when the same user can `sudo rm -rf /*`. in this particular case, the DE could help an forgetful user by issuing a big red warning about being remote when trying to change the power state of the system, but in my view it should certainly not forbid it. but yes, it could be up for discussion.

however it seems that in mint denying remote access is the norm rather than the exception, and this a bug.

as a remote user, you can run synaptic (after authenticating as an administrator), because it inherits the polkit config from ubuntu in `/usr/share/polkit-1/actions/com.ubuntu.pkexec.synaptic.policy`, which makes total sense:
```
    <defaults>
      <allow_any>auth_admin</allow_any>
      <allow_inactive>auth_admin</allow_inactive>
      <allow_active>auth_admin</allow_active>
    </defaults>
```

you can also fully manage all config of apt remotely as shown in `/usr/share/polkit-1/actions/org.debian.apt.policy`. however, for some reason, you cannot launch mint's simplified UI for it because `/usr/share/polkit-1/actions/com.linuxmint.mintsources.policy` has this in it:
```
    <defaults>
      <allow_any>no</allow_any>
      <allow_inactive>no</allow_inactive>
      <allow_active>auth_admin_keep</allow_active>
    </defaults>
```

what is the rationale for this, when the user can change the same files via the apt commands or directly using sudo?

you also cannot launch nemo as root remotely, but at the same time you can sudo and mod all your files anyway; why?

in fact it seems mint just copied a template from freedesktop.org and used it without much thinking, given that all actions defined by mint block remote users AFAICT.

again, blocking remote users should be a well justified exception, not the rule. (btw, cinnamon is affected in much the same way.)

i argue that all mint and cinnamon polkit files should be set to have equal values for <allow_any>, <allow_inactive>, and <allow_active>, unless proven beyond doubt that that would be a mistake.

FYI, some cases where remote access might/should be blocked:
- mintstick? possibly not: i think xrdp allows remote usb devices.
- Modify the lit LED for a Wacom tablet
- Modify the OLED image for a Wacom tablet
- Modify the laptop brightness

in all, i think different treatment of remote users is a big polkit blunder, and on each and every system i remotely administer i would like to have that function disabled with a source patch.

**Comment by eiver** [comment]
I agree. I do not see how refusing access for remote (admin) users improves security. It only ruins user experience.

- I cannot reboot via GUI, but i can "sudo reboot"
- I cannot shutdown via GUI, but i can "sudo shutdown -P now"
- I cannot change mint sources, but can "sudo mintsources" or change files directly
- I cannot update to a newer version of Mint, but can "sudo mintupdate"

I suggest to change these policies to "auth_admin_keep", so that we also reduce the amount of password prompts.

P.S. The OP mentioned xrdp, but the issue is for any remote access (I use x2go and have the same issues).

**Comment by Lanchon** [comment]
auth_admin_keep can potentially be unsafe providing for privilege escalation. but given that X's security is totally broken, the idea is defensible (but there is wayland).

**Comment by eiver** [comment]
Regarding auth_admin vs auth_admin_keep - as always it is a tradeoff of convenience vs security. To solve this bug auth_admin  is good enough. 

A separate discussion is: what would a malicious actor need to do to abuse auth_admin_keep. If they already managed to trick the user to run some unprivileged code - could that code display a fake admin password prompt and trick the user to give out their root password? In that case, forcing the user to reenter the password will not give any security benefits.

Anyway lets cut the discussion here, as it might quickly grow to something not relevant to the bug - we can continue it elsewhere, but its a good idea to keep it in mind.

**Comment by mtwebster** [comment]
Okay I screwed up the issue link on these commits, so here they are:

https://github.com/linuxmint/mintsources/commit/d18f87d9bf17d003654a6c39659879d3de9fa3aa
https://github.com/linuxmint/mintdrivers/commit/3879e02f6cee73a5e4f153703ba9b4457aa1eea0
https://github.com/linuxmint/lightdm-settings/commit/5eac66abbf4acbbd0c65b6afc4fc438348fdf040
https://github.com/linuxmint/mintcommon/commit/a3b038e566d4e7912c845a128ec0b9f45944be23
https://github.com/linuxmint/mintlocale/commit/8492a2f381d9a74129ffb372653cee6e3adcd210
https://github.com/linuxmint/nemo/commit/990cdd01a9eec437278c389de2c64ef5c830583c
https://github.com/linuxmint/nemo/commit/9ad05aae47a822f8fc643d42d9ca82eecfbd4e72 (follow-up)

We discussed auth_admin vs auth_admin_keep and went with the less restrictive option - nemo already had it, and is by far the most dangerous of the above tools, so this may as well be convenient.

Please let me know if I missed anything. I skipped mintupdate for now, as one is for upgrades and the other for automation.

**Comment by Lanchon** [comment]
> Okay I screwed up the issue link on these commits, so here they are:
> 
> [linuxmint/mintsources@d18f87d](https://github.com/linuxmint/mintsources/commit/d18f87d9bf17d003654a6c39659879d3de9fa3aa) [linuxmint/mintdrivers@3879e02](https://github.com/linuxmint/mintdrivers/commit/3879e02f6cee73a5e4f153703ba9b4457aa1eea0) [linuxmint/lightdm-settings@5eac66a](https://github.com/linuxmint/lightdm-settings/commit/5eac66abbf4acbbd0c65b6afc4fc438348fdf040) [linuxmint/mintcommon@a3b038e](https://github.com/linuxmint/mintcommon/commit/a3b038e566d4e7912c845a128ec0b9f45944be23) [linuxmint/mintlocale@8492a2f](https://github.com/linuxmint/mintlocale/commit/8492a2f381d9a74129ffb372653cee6e3adcd210) [linuxmint/nemo@990cdd0](https://github.com/linuxmint/nemo/commit/990cdd01a9eec437278c389de2c64ef5c830583c) [linuxmint/nemo@9ad05aa](https://github.com/linuxmint/nemo/commit/9ad05aae47a822f8fc643d42d9ca82eecfbd4e72) (follow-up)
> 
> We discussed auth_admin vs auth_admin_keep and went with the less restrictive option - nemo already had it, and is by far the most dangerous of the above tools, so this may as well be convenient.
> 
> Please let me know if I missed anything. I skipped mintupdate for now, as one is for upgrades and the other for automation.

thank you so much for fixing this!!

> A separate discussion is: what would a malicious actor need to do to abuse auth_admin_keep. If they already managed to trick the user to run some unprivileged code - could that code display a fake admin password prompt and trick the user to give out their root password? In that case, forcing the user to reenter the password will not give any security benefits.

this is currently a non-issue:
- x11 security is broken, so any user process can sniff the keystrokes sent to any window. this includes the gnome polkit password popup window and all terminal windows. so whenever you type your password in the GUI, you are in effect broadcasting it to your whole userland. it's just a question of etiquette that running apps choose not to sniff it. this is pretty bad; like really bad. (i could be wrong, but i think that access even flows to containerized apps, such as flatpaks, which exacerbates the risk.) this is one important reason why most desktops are switching to wayland, even though mint is lagging in this regard. i think mint moved from we dont care about wayland to we will have to migrate sooner or later, which is a good thing, but i might need to leave my favorite DE behind due to security concerns.
- but auth_admin vs auth_admin_keep still need to be weighted on their relative merits because mint will eventually move to wayland (or die trying), so security will be there eventually.
- but even on wayland, you can simply pop up a fake polkit password popup lookalike to harvest passwords. at that point maybe some tamper-proof options for auth without password will be implemented. for example, a tamper-proof system window with a simple "allow access" button. yes you could fake it, but you wouldn't harvest a password.
- but the problem remains for situations where passwords are really required. even on wayland you could fake the login or unlock screens and harvest passwords. ultimately solving all these password entry scenarios involve the system asking the user to type a tamper-proof, system-intercepted key combo before ever asking for or allowing typing of passwords. and requires the user knowing that a password prompt without the previous system-intercepted key combo is a phishing attempt by an app. if you are old enough, you might remember the "Press CTRL-ALT-DEL to login" prompt from Windows NT 4. yes, they did got some things right way before us... but then they eliminated (by default) the feature they had gotten right on Windows XP (NT 5) because it was "unpopular"... WTF!
- you could also show a system secret on the login screen, a photo, some text, whatever, hoping users will refrain from typing their passwords if they don't see the secret, but then other unprivileged local users -if they exist- will see it, so this is not safe in a multiuser environment.

**Comment by eiver** [comment]
I am unfortunately old enough :P. The magic system intercepted key combo of ctrl+alt+delete is still present even in windows 10 or 11 and can even be enforced by system policies - a typical scenario on a work laptop. This kind of thing would be useful on Linux too, though it doesn't solve all problems... better to avoid running malicious code on the machine :P
