### ISSUE TITLE
gnome-font-viewer is missing from 21.3

### ISSUE THREAD

**Issue by ENRORMA** [linuxmint/linuxmint#634]
in previos versions of mint gnome-font-viewer was installed so you could double click a font to install it
in 21.3 its not installed by default but its in the repositories and work without problems, even on wayland

**Comment by clefebvre** [comment]
It was removed on purpose for many reasons:

- It's been buggy for the last 6 years. It would hang/crash when started. The install button doesn't work reliably. We've been patching it for years. We even shipped with a really old version to workaround this for as far as I remember.
- It's designed for GNOME-only and it moved to libAdwaita, so it will create additional theming/integration issues going forward.
- It's a niche tool which only a few people use, so it's OK not to seek a replacement and to just remove it.
