### ISSUE TITLE
LM 21.3 and LMDE 6 live ISO loopback.cfg fails to boot

### ISSUE THREAD

**Issue by Gaudeamos** [linuxmint/linuxmint#635]
This issue applies to live disc ISOs "linuxmint-21.3-*-64bit" and "lmde-6-cinnamon-??bit" (all editions).

**Steps to reproduce failure:**

1. The ISO's /boot/grub/loopback.cfg is invoked: [I don't know why this snippet does not honor linebreaks; seems to be OK in the snippet at end]
`
fn_loopback {
  set iso_path="${1}"
  export iso_path
  search --set=root --file ${iso_path}
  loopback iso_dev "${iso_path}"
  set root=(iso_dev)
  configfile /boot/grub/loopback.cfg
  loopback --delete iso_dev
}
`
2. The ISO's boot menu is displayed as expected, and the default (1st) menu entry is selected. 
3. The LM boot splash animation appears (as expected) and remains indefinitely; starting to wonder after a minute or so.
4. When the splash is dismissed by pressing ESC, the following error message indefinitely prints to the screen:
     `/init: line 49: can't open /dev/sr0: No medium found`

**Expected behaviour:**
Well, you know... the live OS should be good-to-go after a minute or so.
LM version 21.2 ISOs boot in this way as expected.

**Cause and solution of this issue:**
The boot parameter `iso-scan/filename=$iso_path` is not fed to the kernel on the `linux /casper/vmlnuz ...` line of /boot/grub/grub.cfg, which is sourced in loopback.cfg.

The GRML folks handle this situation elegantly: 
http://git.grml.org/?p=grml-live.git;a=blobdiff;f=templates/boot/grub/grub.cfg;h=31545bd0042dd1e62ed9f83ae81b85565881969b;hp=7e115d6044f0ff86e1944f3bf8121289ef67955b;hb=641c1ace68b52313653478ba4699ca46a1e84184;hpb=2fb103a7c7d8cc2aed11c42e1d29c273c7848049
```
(file grub.cfg)

if [ ${iso_path} ]; then
  set loopback="iso-scan/filename=${iso_path}"    # "findiso=..." for LMDE
fi

menuentry "<menu item caption>" {
    set gfxpayload=keep
    linux	/casper/vmlinuz ... "${loopback}" quiet splash  --
    initrd	/casper/initrd.lz
}
menuentry ...

```
The LMDE 6 ISOs have the same issue.

ref: https://www.supergrubdisk.org/wiki/Loopback.cfg

**Comment by clefebvre** [comment]
Hi @Gaudeamos,

Are you able to test if we produce new ISOs?

I can't find documentation on `findiso` vs `iso-scan/filename`. Can't we use `findiso` both for Mint and LMDE isos?

**Comment by clefebvre** [comment]
OK, it looks like iso-scan/filename is read by casper, whereas findiso is part of live-boot.

**Comment by clefebvre** [comment]
This is fixed in the upcoming 21.3 EDGE ISO.

**Comment by Gaudeamos** [comment]
> This is fixed ...

Awesome!
I have another issue that relates to LMDE live ISOs only. Where should I report that?

**Comment by Gaudeamos** [comment]
> Are you able to test if we produce new ISOs?

Of course. Alternatively/additionally I could provide *.cfg code to you for testing new ISOs.

**Comment by JonnyTech** [comment]
> This is fixed in the upcoming 21.3 EDGE ISO.

> I have another issue that relates to LMDE live ISOs

Me too with the LMDE6 ISO (see https://github.com/Mexit/MultiOS-USB/issues/25).

@clefebvre are there any plans to fix the LMDE6 ISO as you have done with the standard Mint Ones?

**Comment by clefebvre** [comment]
Fixed in the upcoming LMDE 7 ISO.

**Comment by Jeremy7701** [comment]
Does this mean that a current LMDE6 ISO which has been copied to USB will fail to boot?
