### ISSUE TITLE
MINT 19 libreoffice feature not working

### ISSUE THREAD

**Issue by ferslash** [linuxmint/linuxmint#65]
on linuxmint 19 cinamond

using the installed libreoffice 6, the feature "freeze cells" is not working

when you set it, and save the file, it is later "forgot" when you close the file

the feature is in this path: View - Freeze Cells - Freeze Rows and Columns

(it was working fine on linuxmint 18.3 cinamond)

**Comment by xenopeek** [comment]
Can't reproduce. Opened LibreOffice Calc (version 6.0.3.2 as currently available on Linux Mint 19), inserted some nonsense data in a couple of rows and columns, set View -> Freeze Cells -> Freeze Rows and Columns on cell B2, saved and closed the file and after reopening the freeze cells feature is still in place. For help with troubleshooting I suggest you post a new topic on the [support forum](https://forums.linuxmint.com/).
