### ISSUE TITLE
Unable to boot after a kernel update when using ZFS

### ISSUE THREAD

**Issue by sohmc** [linuxmint/linuxmint#653]
### Distribution

Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

NVIDIA 4060 TI

### Frequency

Always

### Bug description

I am new to Linux Mint and ZFS, having used Ubuntu Desktop prior to now.  I've successfully installed LM and enabled the advanced option to use ZFS as my filesystem during the installation process.

Initial boot works as expected, with the ability to install updates after booting.  After a few days, I noticed that I couldn't boot into LM.  I tried using the Live USB and running BootRepair without success.

I proceeded to reinstall the entire OS only to have this happen again.  I reinstalled LM again and again a forth time.  A few days ago, I saw that the system update had a kernel update.  I suspected that the kernel update might be the culprit and proceeded to take a snapshot just in case.

Sure enough, after the kernel update, I wasn't able to boot.  The grub menu loads as expected.  The error I get:

```
error: file `/BOOT/ubuntu_XXXXXX@/vmlinuz-6.5.0.25-generic' not found.
error: you need to load the kernel first.
```

I suspect that the kernel update does *something* to the grub config where it can no longer access the ZFS mount.  grub is outside of my area of expertise so I'm not exactly sure what I'm looking for.

I am able to boot using [ZFSBootMenu](https://docs.zfsbootmenu.org/en/v2.3.x/) (after copying the appropriate files to rpool), but I don't think ZFSBootMenu supports Secure Booting as I can't get Nvidia drivers to load.

This has happened so consistently that someone else must have experienced this.   So far, I haven't found anyone else experiencing the same issues after a kernel update.

I am planning on doing another full reinstall, but this time I will make a backup of the boot partition so I can do a diff of the grub.cfg.  But before I do that, I wanted to report this as a bug in case others are experiencing the issue.  I've found that restoring bpool to an earlier snapshot does not change things, which leads me to suspect that it's the grub.cfg on the boot partition that is at fault.

### Steps to reproduce

1. Install Linux Mint enabling ZFS under "Advanced Options"
2. Reboot to the installed OS
3. Wait for Software Update provide a kernel update and install it.
4. Reboot again

### Expected behavior

I expect Software Update to properly configure grub with the latest kernel.

**Comment by leigh123linux** [comment]
This isn't the right place for your issue.

https://github.com/linuxmint/linuxmint/issues

**Comment by clefebvre** [comment]
Can you reproduce the issue with Ubuntu 22.04?

To be honest, the only reason ZFS is present in Mint 21.x is because it was inherited by Ubuntu. Very few people use this option, it's not really tested on our side. In fact, we're thinking of removing it in Mint 22.

**Comment by sohmc** [comment]
I have not tried to reproduce the issue in Ubuntu 22.04 but it's not a bad idea.  To be clear, I've never run ZFS on Ubuntu; only ext4.

It will be a few days.  Just got a family emergency so had to leave suddenly.

I'd love for you all to continue to support ZFS, but I can understand it can be hard to support if it's not widely used.

**Comment by clefebvre** [comment]
Removed in Mint 22.

**Comment by sohmc** [comment]
Sorry for the delay.  I've been dealing with a family emergency.

I have not yet installed Ubuntu 22.04 but plan to tomorrow.

Looking through the dmesg logs, it looks like the initial Linux Mint MOK keys are being deleted.  I haven't confirmed this yet.  I'll first install ubuntu, attempt a kernel update, then report back.

Then I'll reinstall Linux Mint, copy the MOK keys, and attempt a kernel update.

EDIT: My browser just refreshed and saw that the issue was closed.  It sounds like my setup isn't supported.  I hope ZFS can be added back in the future.

**Comment by getcom** [comment]
Removing ZFS in Mint 22 is a bad idea. I`m using a ZFS mirrored pool for /home. mdadm is not really an alternative if you are aware of the ZFS advantages. The next step is also to use ZFS for /rpool.
If ZFS will be removed, Mint will be out of scope for my requirements.

**Comment by dmk42** [comment]
I am also very disappointed to see ZFS removed from Linux Mint 22.  I use it as my root filesystem.

LMDE has a superior installer that lets me mount any kind of filesystem I want on /target and install the system there.  I use that to install LMDE on ZFS.  Unfortunately, it is too old for a couple of my machines.  I would really like to see the same capability in the Linux Mint installer, or better yet, see the LMDE installer ported over.

**Comment by JakeSays** [comment]
I'd like to add my disappointment to ZFS being removed. Now I am stuck on 21.3

**Comment by dmk42** [comment]
> LMDE has a superior installer that lets me mount any kind of filesystem I want on /target and install the system there. I use that to install LMDE on ZFS. Unfortunately, it is too old for a couple of my machines. I would really like to see the same capability in the Linux Mint installer, or better yet, see the LMDE installer ported over.

I am pleased and grateful that the LMDE installer is now going to be ported to Linux Mint 23.  That will give expert Mint users the ability to use  a ZFS root with or without distro support.

[Edited to add a link to the relevant Linux Mint blog entry]
[https://blog.linuxmint.com/?p=5019](url)
