### ISSUE TITLE
LMDE 6 update-grub os-prober disabled by default, unlike LM 20.3

### ISSUE THREAD

**Issue by noreasternhumidity** [linuxmint/linuxmint#655]
LMDE 6 update-grub os-prober disabled by default, unlike LM 20.3

This looks like an exception in LMDE functionality in the attempt to mirror the functionality of Linux Mint 21.3.  The LMDE update-grub os-prober function is disabled.  Debian Bookworm and Ubuntu 22.04 both currently have the update-grub os-prober function disabled as well.  So it looks as if LM 21.3 was patched to allow it, yet LMDE wasn't yet.  There is a work-around to be found on the Internet, but it is up to the user to discover it.
Conditions tested under legacy BIOS mode.

**Comment by Jeremy7701** [comment]
If /etc/grub.d/30_os-prober has the exec permission removed it won't be run - something you need to specifically do yourself.
By default it has exec permission enabled, causing it to be run.

**Comment by noreasternhumidity** [comment]
Thanks for looking into it...  /etc/grub.d/30_os-prober on mine has exec enabled and doesn't run under update-grub.  I can run it independently though.  Also it won't run under
sudo dpkg-reconfigure grub-pc 
which is how I first discovered it.  After that I followed that condition to update-grub.  os-prober by itself with elevated privileges doesn't seem to do anything, but no error either.

**Comment by noreasternhumidity** [comment]
I just checked on a fresh install and it runs under update-grub.  So there must have been something that was changed on my install.  Not being something I would have any interest in fiddling around with, it might be regression from old code from an installed utility package or something along those lines.

Since that isn't caused by the base install, it's probably not worth looking into.
