### ISSUE TITLE
[Q] mint system monitor fork?

### ISSUE THREAD

**Issue by Lanchon** [linuxmint/linuxmint#669]
hi,

i´ve read somewhere that mint was forking system monitor from the GTK 3 version.

i'd like to contribute, but i can't find the repo. is this fake news?

thanks

**Comment by fredcw** [comment]
Yes, on the Linux Mint blog, April. No repo announced yet AFAIK.

**Comment by clefebvre** [comment]
It would be an Xapp project. Discussions would happen on the Xapp matrix channel at https://matrix.to/#/#xapp:matrix.org.

**Comment by Lanchon** [comment]
thank you!
