### ISSUE TITLE
A swapfile should not be created when installing to a btrfs partition

### ISSUE THREAD

**Issue by jondo** [linuxmint/linuxmint#67]
I have installed LM 19 on a btrfs partition (for use in Timeshift). This has created a 1,2G `/swapfile`.

However, btrfs [does not support a swap file](https://superuser.com/questions/539287/swapon-failed-invalid-argument-on-a-linux-system-with-btrfs-filesystem):

> $ sudo swapon /swapfile
swapon: /swapfile: swapon failed: Invalid argument

(So I'm going to delete it.)

**Comment by xenopeek** [comment]
Btrfs supports swap files from kernel 5.0 onwards but with some restrictions and requirements. See https://btrfs.wiki.kernel.org/index.php/FAQ#Does_btrfs_support_swap_files.3F. Basically it requires the swapfile to be created on a separate subvolume with nodatacow mount option set or, I think also possible, the +C attribute to be set before the swapfile is created.

I created a subvolume and mounted it with nodatacow option. Copied the swapfile to the mount directory and updated the swapfile's location in fstab. swapon -a then enables the swap, which is confirmed with free -m.

That should all be old hat for Btrfs users but nice to confirm from kernel 5.0 onwards swap files on Btrfs can be made to work.

Linux Mint 19.3 installer doesn't handle that for the user doing manual partitioning.

**Comment by SimonIremonger** [comment]
> That should all be old hat for Btrfs users but nice to confirm from kernel 5.0 onwards swap files on Btrfs can be made to work.
> Linux Mint 19.3 installer doesn't handle that for the user doing manual partitioning.

Are we able to confirm mint 20 does this correctly now, even in the case of manual-partitioning?  Does this need review/check for mint 20.1 installer?

**Comment by xenopeek** [comment]
https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1818811 has a modified script for partman-swap to fix this, but it's not implemented upstream. As of right now also the development version for Ubuntu 21.10 still has this issue. This needs to be reported upstream (in partman-swap).
