### ISSUE TITLE
GLOBAL SOLUTION for the use of Proprietary Media Codecs

### ISSUE THREAD

**Issue by ghost** [linuxmint/linuxmint#670]
The use of proprietary media codecs is a problem that has not yet been completely solved in the GNU/Linux world. This document proposes a two-part SOLUTION. It is the synthesis of a collective reflection carried out on the French site MINIMACHINES.NET, founded and animated by Pierre Lecourt.

_**The first part is immediately applicable, since it simply consists in understanding how and why the use of these proprietary codecs is authorized for PCs with a valid Microsoft Windows license.**_ These PCs make up the vast majority of the installed base.
The second part is a blueprint for adapting the same principles to other, minority PCs.

**PROPRIETARY CODECS**

Proprietary "codecs" generally refer to a library or driver that implements a video (e.g. h.264) or audio (e.g. aac) compression algorithm. These algorithms exist for encoding or decoding the proprietary format concerned. By "proprietary" we mean the rights holders who authorize the use of their algorithms in return for a small royalty. These royalties are payable per "unit", which is the equipment on which the aforementioned algorithms are present.
For the user (excluding the production of audio/video goods), who will generally use the "decoders" for these formats present on his device (the "unit"), this is transparent. Collection of the royalty and payment to the rights holders is handled by whoever installs the algorithm on the device. For example, Android and IOS smartphones, Windows laptops, portable music players, etc. all include a small contribution to the copyright owners in their selling price.

For Microsoft Windows, these algorithms are implemented in the "Windows Media Foundation" library, which supports both decoding and encoding of all these formats (notably h.264 and aac). Microsoft pays the copyright owners, and every holder of a valid Windows license on his or her PC (eg the "unit") is authorized to use the *algorithms*.

**ACTION PLAN, PART 1 / PC WITH WINDOWS LICENSE**

In one of his excellent articles, Pierre Lecourt (founder and moderator of the MiniMachines.net website) explained how to safeguard the Microsoft Windows license, which is (and I quote), [as a rule "tattooed" on the system BIOS]. Almost all PCs sold worldwide are supplied with "Windows pre-installed" and "activated" by this "watermarking" mechanism. This hard-coded inscription on your PC certifies that you have paid the Microsoft license fee and, what's important to us, the share destined for the rights holders of all proprietary algorithms. This proof is "hard-wired" to your PC, the "unit" of rights, in its intimate memory, its BIOS.

I hereby affirm, under the supervision of the relevant legal departments, that the installation and use of software for the playback or production of audio/video goods is legally compliant with the conditions of use and remuneration defined by the copyright owners.

Software publishers will be able to check the presence and validity of the Windows license for PCs of this type, even under Linux. After validation, they will be free to authorize the use of the *alogorithms* concerned, even if they are *implemented* by them in another software library independent of that of Windows.

**ACTION PLAN STEP 2 / PC WITHOUT WINDOWS LICENSE**

This will require a bit of work. I'm simply putting forward the idea.In this case, I'd recommend working out a mechanism with PC manufacturers:

- tattoo" PCs with a license that could be called "Linux Media Certified" or better.
- include in the sale price the share for the rights holders (30€ is Microsoft's usual share + the share for all rights holders, which is barely a handful of euros, let's say a pinch).
- ensure payment to copyright owners, as they already do with Microsoft Windows.

**CONCLUSION**

The first part is "easy" to set up, but not totally obvious because it requires a change of habits. No one should be ashamed of having missed this point, because the synthesis achieved here reconciles two worlds usually considered antinomic. The key point is that it is the PC owner who pays the royalties to the rights holders, not Microsoft, which merely collects them.

This proposal is now in the hands of the Mint team, whose excellent work I appreciate every day.

Thank you for your attention,
Sincerely

APPENDICES:

List of formats supported by the Windows Media Foundation:

https://web.archive.org/web/20221004163521/https://learn.microsoft.com/fr-fr/windows/win32/medfound/supported-media-formats-in-media-foundation

Collective reflection on the MINIMACHINES.NET website:

https://web.archive.org/web/20240514061820/https://www.minimachines.net/actu/davinci-resolve-19-prend-desormais-en-charge-les-circuits-graphiques-126589

Windows license recovery in the BIOS, article by Pierre Lecourt on MINIMACHINES.NET

https://web.archive.org/web/20240221213047/https://www.minimachines.net/actu/logiciels-espions-minipc-chinois-124777

**Comment by ghost** [comment]
_**Side note: The text has been extensively translated from French using the free version of DeepL:**_

https://www.deepl.com/translator

**Comment by leigh123linux** [comment]
Linuxmint doesn't provide any codecs.
All codecs come from the ubuntu repo so you will need to file this issue at their bug tracker.

**Comment by ghost** [comment]
@leigh123linux

**Short answer:** No, Sir, I won't.

**Why?**

- Because I don't use Ubuntu, Debian or whatever else I don't know. I've only been using Linux Mint.
- As a conscientious end-user, I've carefully read the Mint documentation before submitting this "issue":
https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html
It makes it clear that "my role is done" (citing).
- First and foremost, a very clever young American Woman told us one day "You can explain a thing to People. You can't understand it for them."

I'm looking to improve things, including my English, so please let me conclude by saying this in all kindness:

_I ain't gonna take this shirt no more! Voilà. Excuse my French._

Now that we've been equally rude to each other, maybe it's time to try to move on. Evil will never be far away to stop us. It's up to us to identify its Root. If we have to, we may have to sacrifice the whole plant, even if it means making an impossible task even harder. Let's just do our Best, if we think something Good can come out of it.

_Here's an old (hopefully) version of the Debian dependency tree:_

![Debian_family_tree_11-06_highlight](https://github.com/linuxmint/linuxmint/assets/169746044/0c0980fa-531c-4b7b-a686-fafad77b4a0a)

Best Regards.
