### ISSUE TITLE
[Suggestion] Replace neofetch by fastfetch in Linux mint 22

### ISSUE THREAD

**Issue by whoami1i1i1i** [linuxmint/linuxmint#682]
Neofetch has been deprecated and its repository archived a few months back.
A lot of people and distros are moving to actively maintained replacements like fastfetch because of that, and I think it would be a good idea for mint to include it by default instead of neofetch in the new 22 release.
Fastfetch is actively developed, has more features, and is much faster than neofetch.
For ubuntu-based distros it can be gotten through an official PPA found on the fastfetch GitHub page. For debian-based distros it's available in the debian repos from Debian 13 and up. Packaging it in both the mint and LMDE repos is also an option since the up-to-date deb for both ubuntu and debian based distros is available from the fastfetch GitHub page.

**Comment by Jeremy7701** [comment]
[https://itsfoss.com/neofetch-alternatives](https://itsfoss.com/neofetch-alternatives) has some other alternatives.

**Comment by whoami1i1i1i** [comment]
Moved to the mint 22 issue tracker.
