### ISSUE TITLE
Linux Mint 22 'Wilma' Beta iso - true or fake?

### ISSUE THREAD

**Issue by wizardfromoz57** [linuxmint/linuxmint#684]
Clem may be able to shed light, the beta is at [https://ftp.nluug.nl/os/Linux/distr/linuxmint/iso/testing/](url)

Reason I ask is that one of my members at linux.org has run an inxi on it and it shows based on Ubuntu 22.04 instead of Ubuntu 24.04

Cheers

Chris Turner
wizardfromoz

**Comment by clefebvre** [comment]
That's a bug in the BETA. But yeah, the BETA is out indeed.
