### ISSUE TITLE
Where is battery icon?

### ISSUE THREAD

**Issue by r3d9u11** [linuxmint/linuxmint#69]
#### Expected behaviour
battery icon should be displayed (also icons of Guake and CPU Mode is looking ugly, but with Linux Mint 18.3 they are looks nice)

#### Actual behaviour
battery icon is missed
![screenshot at 2018-08-28 14-24-12](https://user-images.githubusercontent.com/15020827/44720072-3a209980-aace-11e8-9362-d3ea0ee3fcc3.png)

#### MATE general version
1.18.0

#### Package version
1.18.0-1+sonya

#### Linux Distribution
Linux Mint 19 x64

**Comment by lukefromdc** [comment]
Is this an indicator issue? I heard but cannot confirm that Ubuntu patches mate-power-manager to remove the icon, then shows it as an indicator from another package. The comparable package in Debian Unstabl (which I run) would be ayatana-indicator-power. Do you have Ubuntu's power management indicator package installed? If not that may be your problem. If it is it could be misconfigured or have an issue of its own.

**Comment by r3d9u11** [comment]
well, I have another laplop with linux mint 19 and it haven't troubles with it. I think that something wrong with my current system and some packages can be wrong

**Comment by r3d9u11** [comment]
I should to reopen this issue. because clean Linux Mint 19 (.iso v2) haven't this trouble, but after system updated (was installed all available updates) the battery indicator was broken, again.

(HP Probook 450 G5)
