### ISSUE TITLE
XFCE 22 (Wilma) X-app icons (Updater and Network) too small

### ISSUE THREAD

**Issue by robert-lipman-user** [linuxmint/linuxmint#691]
The X-app icons (Updater and Network) are too small by default -- and there is no mechanism to increase the size of those icons to be the same size of the other icons in the same panel.

Kudos to the Linux Mint team -- great job!  I love you folks!

Bobby L.

**Comment by mtwebster** [comment]
Hi, if you right-click the xapp plugin to get its menu (we need to make this easier...the most reliable for me is rightclicking on either end of the plugin), there are options to adjust color and symbolic icons.

We did this to bring the xfce desktop more consistent with MATE and Cinnamon in panel appearances - we didn't think symbolic icons look very nice when they're the same, or nearly the same height as the panel.

**Comment by robert-lipman-user** [comment]
Dear MT, thanks for trying to help!

I have considerable experience with XFCE Mint -- having installed it in hundreds of computers.  Unfortunately, the strategy you have suggested is not changing the size of the icons.  Also, in the Panel Preferences app, the tool icon is grayed out (and does not function) with respect to X-app -- so that mechanism, which can often be used to change icon size for other applications, does not work for the X-app!

**Comment by robert-lipman-user** [comment]
Hi Michael, thanks for trying to help!

I have considerable experience with XFCE Mint -- having installed it in
hundreds of computers. Unfortunately, the strategy you have suggested is
not changing the size of the icons. Also, in the Panel Preferences app, the
tool icon is grayed out (and does not function) with respect to X-app -- so
that mechanism, which can often be used to change icon size for other
applications, does not work for the X-app! So kindly remove the "Closed"
designation as this issue has not yet been fixed.


All the best,

Bobby

**Comment by mtwebster** [comment]
This doesn't work?


https://github.com/user-attachments/assets/197f9e4f-0c70-42cb-ad6a-dee79f47870f

**Comment by mtwebster** [comment]
This doesn't work?

https://github.com/user-attachments/assets/45d06480-6144-4d4c-aa76-609749c2b564

**Comment by robert-lipman-user** [comment]
It is VERY difficult to access the tool within X-app that allows you to
change the icon size -- and when I can, the change has no effect on the
icon.

The best way to do it would be the tool (wrench) icon within the Panel
Preferences app -- but that is grayed out for the X-app.

As I have mentioned, I have installed Mint XFCE in hundreds of laptops (and
then donated them to good causes, such as Ronald McDonald Houses (kids with
cancer, etc.)) -- so if this is difficult for me, it may be very, very
difficult for someone with less XFCE Mint experience.

All the best,
Bobby

**Comment by KarmyDev** [comment]
Hello!
So I see this as closed, however first time upgrading to Mint 22 Xfce and seeing how changing **Fixed Icon Size** in Appearance tab from **Panel Preferences** takes no effect on **XApp Status Plugin** as well as **Status Tray Plugin** led me to thinking this was a bug.

I bet there are more people who are confused just as I am, 
I'd kindly ask to revert this "feature"?
Or make it easier to access that menu from withing **Panel Preferences > Items**, because as of now, it is impossible to even edit currently selected item (which is XApp Status Plugin)
![image](https://github.com/user-attachments/assets/dc8bba3f-0b75-4f9a-9bcf-c8b6598346a7)

**Comment by billyswong** [comment]
> We did this to bring the xfce desktop more consistent with MATE and Cinnamon in panel appearances - we didn't think symbolic icons look very nice when they're the same, or nearly the same height as the panel.

@mtwebster 
But the panel becomes NOT self-consistent. Icons inside the XApp Status Plugin look small while others still look big. Those outside can also be symbolic icons. Definitely some of them will be. Personally I would rather all icons being the same size, than only some symbolic icons being smaller but not all.

**Comment by yougotwill** [comment]
Until https://github.com/linuxmint/xfce4-xapp-status-plugin/commit/26df8f176a248d6226791768408b2e478083d14c comes to mint I've downgraded using the `xfce4-xapp-status-plugin_0.3.3+virginia_amd64.deb`. Not perfect but the icons are better spaced.
