### ISSUE TITLE
Mint 19 Cinnamon missing packages I had in 18.3

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/linuxmint#70]
Agave, gcolor2, libav-tools
There might be more but these are 3 that were in my standard install routines.

**Comment by clefebvre** [comment]
All these are upstream from us.

**Comment by ChooChooAl** [comment]
Not in Linux Mint 19 v2.   It is not in synaptic package manager when I look today.
I did find a Gcolor3 that works with one command line.  and I've discovered that Agave is not important, but libav-tools is still needed for things like avconv.
