### ISSUE TITLE
Feature request: fork GTK.FileChooser to restore previous functionality

### ISSUE THREAD

**Issue by GitHubIsToxic** [linuxmint/linuxmint#71]
Mint 13-17 had a highly usable file chooser (file open/save), dialog with several useful productivity features that Mint 19 currently lacks:

**Recent Places**
This is a category in the file chooser dialog sidebar that simply lists all parent folders of the files listed in "Recent Files". These shortcuts greatly streamlined repeated file operations in typical every day workflow. It worked really well, and even refreshed in real-time as other volumes got (un)mounted.
Unfortunately this fully functional and stable feature was removed by GTK developers without apparent discussion because a (single?) user was confused how it worked: https://bugzilla.gnome.org/show_bug.cgi?id=751653

**Paste file paths**
In previous versions it was possible to paste a file path into the directory path text box. Currently it is replaced by a breadcrumbs bar, and it is not possible to paste a path from clipboard.
There is however a secret undiscoverable shortcut: CTRL + L, but it doesn't provides path completion/suggestion, and reverts to breadcrumbs as soon as the control loses focus. It also doesn't initially show the current path, only the file file name part, requiring you to re-type the whole path even if you just wanted to change one character.
Judging from many bug reports and comments from other users, it is unclear if this is intended behaviour or a bug.

**Switch between breadcrumbs and text box path**
Previous versions included a button on the toolbar (next to "New Folder" button) to switch between breadcrumbs and plain text box path. This made it possible for users to find out that it was possible at all, to paste paths, and this setting was also remembered system wide.
It doesn't become clear from reading numerous related bugs if this setting was intentionally disabled, accidentally broken, erroneously marked fixed, or simply ignored. One comment suggested years ago that this setting is written properly, but not _read_ when the dialog re-appears each time. Apparently this was not further investigated by GTK developers; it is still broken today.

---

The file chooser dialog (appropriately named "common dialog" on Windows) is probably one of the most frequently used dialog in typical every day computer usage, for all users, developers, office and home users alike. I believe it deserves more attention to fix these widely reported issues.

Some of the repeated requests on the GNOME bug tracker to restore these functionalities or even re-open bugs have not seen responses over 12 years. I think it is safe to assume that GTK developers can or will not add these features back in the near future.

I hope the Linux Mint developers are in a better position than regular users (like me) to help motivate GTK developers to honestly investigate these issues, or if that doesn't work, fork the File Chooser and fix it for once and for all.

**Comment by JosephMcc** [comment]
Thanks for the request. I don't want to be rude but this is like the third place you've brought this issue up. There isn't much we are going to do here.

**Comment by GitHubIsToxic** [comment]
My apologies for being a nuisance. Part of the reason of me posting this was wanting to have these issues properly documented, as other bug reports and forum threads over the years have created a lot of confusion by  wrongly attributing these issues to Nemo, or Linux Mint in general. I hope this will help other users.

Thanks anyway.
