### ISSUE TITLE
Linux Mint 22: qt applications no longer use system theme

### ISSUE THREAD

**Issue by Captainpast** [linuxmint/linuxmint#718]
After the upgrade from Mint 21.3 to Mint 22 applications that use qt no longer use active gtk theme, **as in Mint 21.3**.

I've noticed, because I use a dark theme and the applications _VLC_, _Kdeconnect_, _Virtualbox_ and _Nextcloud-desktop_ not were in dark mode, and they're all seams to be qt apps.

In Mint 21.3 there was a UI-App to configure the qt5 theme, so it uses the gtk2 theme. (but, doesn't work on Mint 22  #704)

In Mint 22 there are packages installed the sounds like they're doing the same, but it is not:
- `qt5-gtk-platformtheme`
- `qt5-gtk2-platformtheme`
- `qt6-gtk-platformtheme`

**Comment by Captainpast** [comment]
Installing `qt5ct`  solved the problem for qt5 apps.
In `qt6ct` the option to set the qt6-theme to the GTK-theme is not available, so **qt6 still not uses the system theme**

**Comment by tpasztor** [comment]
Hello!

I recently ran into this aswell, and managed to solve it on my end. The steps I took were:

**QT5:**
```
sudo apt install qt5ct
export QT_QPA_PLATFORMTHEME=qt5ct
```
Now run `qt5ct`, set style to `gtk2`, set fonts if needed, and preferred icon theme. 
Log out, log back in, QT5 apps should look as intended.

_Note: qt5ct will refuse to start with a segmentation fault until you export QT_QPA_PLATFORMTHEME, but I found that after you run it once, it's not needed to put an export for QT_QPA_PLATFORMTHEME in `~/.profile`._

**QT6:**
```
sudo apt install qt6ct qmake6 qt6-base-dev qt6-base-private-dev libgtk2.0-dev

git clone https://github.com/trialuser02/qt6gtk2.git
cd qt6gtk2
qmake6
make
sudo make install
```
This installs:
`libqt6gtk2.so` into `/usr/lib/x86_64-linux-gnu/qt6/plugins/platformthemes`
`libqt6gtk2-style.so` into `/usr/lib/x86_64-linux-gnu/qt6/plugins/styles`

Run `qt6ct`, set style to `qt6gtk2`, set fonts if needed, and preferred icon theme and you should be good to go.

If you prefer, you can now remove the build dependencies:
```
sudo apt remove qmake6 qt6-base-dev qt6-base-private-dev libgtk2.0-dev
sudo apt autoremove
```

Tested with VLC for QT5 and QBittorrent for QT6, and I use Mint-L-Dark-Red themes with Mint-L-Orange icons:
![VirtualBox_Linux Mint Wilma_16_10_2024_09_25_59](https://github.com/user-attachments/assets/594b57c4-5459-41f3-8d01-5a6518511084)

**Comment by Hackaloken** [comment]
I ran into this issue as well upgrading from Mint 21.3 to 22 (and then 22.1). Sure, it's pretty easy for a user to fix this problem, but I'd still like to see something done on the Mint side. 

Mint made a change, and now theming for common applications doesn't work properly by default with a common user configuration (Cinnamon, Mint-Y, Dark mode). I guess it doesn't matter because, while they are popular apps, they don't ship with the default install? It seems like this would be an important issue for Mint, given the April 2024 blog post talking about certain applications not "feeling native".

**Comment by alexeymuranov** [comment]
I think this issue should stay open until properly resolved.

This is not just a cosmetic issue. I've just spent several hours trying to figure out why [qpdfview] renders PDF blurry and pixelated on Linux Mint 22.1 (see the screenshot), while it works fine on LMDE. By toggling check boxes here and there in qpdfview settings, I managed to solve the problem by checking "Use device pixel ratio" on the Graphics tab. It was hard to debug, and under LMDE such a workaround is not needed (yet).

![Image](https://github.com/user-attachments/assets/40084588-d222-48e1-99a0-ae8221b472ba)

[qpdfview]: https://launchpad.net/qpdfview

**Comment by alexeymuranov** [comment]
Possibly related:
 * https://github.com/linuxmint/cinnamon/issues/12853
 * https://github.com/linuxmint/cinnamon/issues/12842

**Comment by baaannnaaannn** [comment]
> Hello!
> 
> I recently ran into this aswell, and managed to solve it on my end. The steps I took were:
> 
> **QT5:**
> 
> ```
> sudo apt install qt5ct
> export QT_QPA_PLATFORMTHEME=qt5ct
> ```
> 
> Now run `qt5ct`, set style to `gtk2`, set fonts if needed, and preferred icon theme. Log out, log back in, QT5 apps should look as intended.
> 
> _Note: qt5ct will refuse to start with a segmentation fault until you export QT_QPA_PLATFORMTHEME, but I found that after you run it once, it's not needed to put an export for QT_QPA_PLATFORMTHEME in `~/.profile`._
> 
> **QT6:**
> 
> ```
> sudo apt install qt6ct qmake6 qt6-base-dev qt6-base-private-dev libgtk2.0-dev
> 
> git clone https://github.com/trialuser02/qt6gtk2.git
> cd qt6gtk2
> qmake6
> make
> sudo make install
> ```
> 
> This installs: `libqt6gtk2.so` into `/usr/lib/x86_64-linux-gnu/qt6/plugins/platformthemes` `libqt6gtk2-style.so` into `/usr/lib/x86_64-linux-gnu/qt6/plugins/styles`
> 
> Run `qt6ct`, set style to `qt6gtk2`, set fonts if needed, and preferred icon theme and you should be good to go.
> 
> If you prefer, you can now remove the build dependencies:
> 
> ```
> sudo apt remove qmake6 qt6-base-dev qt6-base-private-dev libgtk2.0-dev
> sudo apt autoremove
> ```
> 
> Tested with VLC for QT5 and QBittorrent for QT6, and I use Mint-L-Dark-Red themes with Mint-L-Orange icons: ![VirtualBox_Linux Mint Wilma_16_10_2024_09_25_59](https://github.com/user-attachments/assets/594b57c4-5459-41f3-8d01-5a6518511084)

this is pain

**Comment by baaannnaaannn** [comment]
> Hello!
> 
> I recently ran into this aswell, and managed to solve it on my end. The steps I took were:
> 
> **QT5:**
> 
> ```
> sudo apt install qt5ct
> export QT_QPA_PLATFORMTHEME=qt5ct
> ```
> 
> Now run `qt5ct`, set style to `gtk2`, set fonts if needed, and preferred icon theme. Log out, log back in, QT5 apps should look as intended.
> 
> _Note: qt5ct will refuse to start with a segmentation fault until you export QT_QPA_PLATFORMTHEME, but I found that after you run it once, it's not needed to put an export for QT_QPA_PLATFORMTHEME in `~/.profile`._
> 
> **QT6:**
> 
> ```
> sudo apt install qt6ct qmake6 qt6-base-dev qt6-base-private-dev libgtk2.0-dev
> 
> git clone https://github.com/trialuser02/qt6gtk2.git
> cd qt6gtk2
> qmake6
> make
> sudo make install
> ```
> 
> This installs: `libqt6gtk2.so` into `/usr/lib/x86_64-linux-gnu/qt6/plugins/platformthemes` `libqt6gtk2-style.so` into `/usr/lib/x86_64-linux-gnu/qt6/plugins/styles`
> 
> Run `qt6ct`, set style to `qt6gtk2`, set fonts if needed, and preferred icon theme and you should be good to go.
> 
> If you prefer, you can now remove the build dependencies:
> 
> ```
> sudo apt remove qmake6 qt6-base-dev qt6-base-private-dev libgtk2.0-dev
> sudo apt autoremove
> ```
> 
> Tested with VLC for QT5 and QBittorrent for QT6, and I use Mint-L-Dark-Red themes with Mint-L-Orange icons: ![VirtualBox_Linux Mint Wilma_16_10_2024_09_25_59](https://github.com/user-attachments/assets/594b57c4-5459-41f3-8d01-5a6518511084)

im running "QT_QPA_PLATFORMTHEME=qt6gtk2 gwienview" and still get this

![Image](https://github.com/user-attachments/assets/d2ac5411-2d38-42ba-9319-8ea23029c70a)

linux mint - user friendly and easy distro,nice

**Comment by anon-ra** [comment]
Thanks for this! However, just running this:

`sudo apt install qt5ct`

and then rebooting was all it took for me on LM 22.2

**Comment by smnthermes** [comment]
Cinnamon should have a Qt platform theme. QGtk3Style looks like Fusion with the GTK3 theme colors.
