### ISSUE TITLE
ftp.heanet.ie shutting down

### ISSUE THREAD

**Issue by l-c-t** [linuxmint/linuxmint#721]
Hi.

https://ftp.heanet.ie/ is shutting down. It is displaying this message:
`This service will be discontinued at the end of August 2024, please make alternative arrangements `

Also, its certificate has expired on 2024-09-21.

It seems to be the preferred/reference mirror for Linux Mint, as links to `sha256sums.txt{,.gpg}` in download pages are targeting it.

Another preferred mirror should probably be selected.

Thanks a lot for your help.

**Comment by clefebvre** [comment]
Fixed
