### ISSUE TITLE
caja: segfault 4 from usb drive unmount #1046

### ISSUE THREAD

**Issue by SteveBrulePhD** [linuxmint/linuxmint#73]
I have spent many days looking at this problem on and off with several distros. At first I thought it was an upstream problem with MATE's caja but after seeing for myself that Fedora's live does not have this issue (newer kernel and the same caja 1.20.2), I'm more inclined to think this is a downstream issue affecting Ubuntu, Linux Mint and Manjaro. You can view the upstream report here:

https://github.com/mate-desktop/caja/issues/1046

**Comment by xenopeek** [comment]
I tried reproducing this on Linux Mint 19 MATE with kernel 4.19.0-39 and Caja 1.20.2 with an USB thumb drive. I can only find options to eject or unmount it, not the 'safely remove drive' option mentioned in the linked issue. Let's keep it in the other issue until it's clear this is a Linux Mint issue.
