### ISSUE TITLE
Mint website: broken links on verification page

### ISSUE THREAD

**Issue by Salvatos** [linuxmint/linuxmint#74]
On the download integrity verification page ([https://linuxmint.com/verify.php](https://linuxmint.com/verify.php)), the SHA and GPG links are broken. Looks like the _https_ is automatically added in front of the _ftp_. Removing that leads to the expected file.

This is on Firefox 62, should it matter.

**Comment by xenopeek** [comment]
Appears to have been an issue at the HEAnet mirror. It works fine now.
