### ISSUE TITLE
PROPOSAL: Mint-Y-Logo... A new version of the Linux Mint logo. Totally redrawn. SVG file included.

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/linuxmint#78]
![lm-logo-y-01b singleline](https://user-images.githubusercontent.com/31940713/47532692-1041e400-d87f-11e8-8bf5-584b22e9a37a.png)

**This is not a new Linux Mint logo. It is just a new version.
Re-created. Made flat, simple, and symmetrical.**

It is not a new logo but... it is totally redrawn. It is now based on a single path with just the minimum required nodes. It is a very simple SVG file... but there are many hours of work into this.

This SVG file is available to you:
https://drive.google.com/file/d/17WpSxpDkuyzVzA68N8c-uRezlSUIMiCx/view?usp=sharing

**Screenshot of the underlying work:**
![lm-logo-y-01b singleline -contour](https://user-images.githubusercontent.com/31940713/47533128-8d218d80-d880-11e8-8632-f7c1b8552e78.png)

- New Grid alignments: equal spaces and equal widths
- New background: 50% circle, 50% square
- New colour: HSL = 96, 112, 128 (#48b865)
- Something is removed...
- ...And something is added

**Your logo is important. It's our collective identity.
We moved to Mint-Y theme and icons, now this could be the next step ...**

**Comment by xenopeek** [comment]
Logo design has moved in another direction so I think I can close this one.
