### ISSUE TITLE
Wrong time displayed on KDE digital clock widget

### ISSUE THREAD

**Issue by awainer** [linuxmint/linuxmint#80]
Hi! 
Since today, when the clocks were moved forward 1 hour to go back from DST in Europe, my digital clock desktop widget is showing the wrong time.

This is right:
```
 $ timedatectl 
      Local time: Sun 2018-10-28 10:24:11 GMT
  Universal time: Sun 2018-10-28 10:24:11 UTC
        RTC time: Sun 2018-10-28 10:24:11
       Time zone: Europe/Dublin (GMT, +0000)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
```
The widget is showing at this time: 8:24 AM (this is wrong, it should be 10:24).
The 'Date & time' setup dialog shows the correct time.

**Comment by JosephMcc** [comment]
You are supplying us much useful information here about the Mint version, desktop environment, etc. KDE is also no longer an officially supported version of Mint. If you are having issues with something KDE related it should probably be reported upstream.

**Comment by awainer** [comment]
Hi Joseph, thanks for the quick reply!
> You are supplying us much useful information here about the Mint version, desktop environment, etc.
You're right, my bad. For the record, the relevant versions:
Linux mint 18.3 KDE edition.
KDE Plasma version: 5.8.9
KDE frameworks: 5.36.9
QT: 5.6.1

>KDE is also no longer an officially supported version of Mint. If you are having issues with something KDE related it should probably be reported upstream.

I wasn't aware of that. I'll take it there.
