### ISSUE TITLE
CPU Frequency Scaling Monitor underclocks Processor when laptop's running on battery, ignores user choice.

### ISSUE THREAD

**Issue by rdlf4** [linuxmint/linuxmint#82]
So I'd like to be able to use my laptop however I want while it's discharging. Problem is, my Acer Aspire 5 has two AMD GPUs: AMD R7 M440, which is my integrated gpu and RX540, the dedicated gpu.
When my laptop is plugged in, CPU frequency goes all the way up to 2.7Ghz and I'm able to play my Steam games, no problem.
But if it isn't plugged in, CPU frequency won't go beyond 1.8Ghz (ondemand or performance), no matter what I do. It still does let me offload games to my dGPU, but the performance is horrible.
I also noticed that, sys/devices/system/cpu/cpu0/cpufreq mentions ACPI is my governor driver.
Is there a way to change that to userspace? I want my laptop to have the same performance while discharging as it does when it's plugged into the outlet, it's my choice. How come Linux Mint gives me governors that does nothing and won't change the CPU frequency?

Now, I was told adding the acpi=off parameter can help. I doubt that, but I won't give it a try because I need ACPI. I was also told this could be a faulty kernel driver. Impossible, a google search shows this is a thing that's being cursing Linux Mint since 2013 (according to a few forum threads I read) and updating or even downgrading the kernel was never a solution.
I want to game on this laptop as it discharges, so how do I override/workaround ACPI and set CPU Frequency to the max?

Please let me know what kind of information you need to help me further.
I'll provide the files ASAP.Thank you.

**Comment by xenopeek** [comment]
Considering age of this issue closing it here. I think this would have been an issue with the kernel and not with any component developed by Linux Mint. For help with [troubleshooting](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) such issues it's better to first ask on the [support forums](https://forums.linuxmint.com/) to find solution or workaround.
