### ISSUE TITLE
[LMDE 3 Cindy x64] Timeshift filling up hard disk without warning

### ISSUE THREAD

**Issue by rshamsnejad** [linuxmint/linuxmint#84]
Hi,

I've encountered an issue with Timeshift. As explained in this forum post : [https://forums.linuxmint.com/viewtopic.php?f=247&t=281996&p=1555433](url) I have manually mounted a local partition outside the usual mount folders (such as /media), with automatic timeshift snapshots activated on boot.

What happened then is that timeshift included these extra folders in its snapshots, and it quickly filled up its partition up to the last byte. That was because I forgot to exclude these mount points from the snapshots.

It was a mistake on my side, but shouldn't Timeshift warn about disk usage with a popup or something when creating a snapshot ? Since it is usually configured at the first boot and then forgotten (until a restore is needed), this situation could repeat itself on many other use cases.

I am using LMDE 3 Cindy x64 on a fresh install (a few days ago).

Thanks for your time and effort
 
SuperBoby

**Comment by xenopeek** [comment]
Considering age of this issue and LMDE 3 having reached end of support, closing this here. If it's still applicable as a suggestion for current versions, it would be better to make this suggestion to the Timeshift developer.
