### ISSUE TITLE
Changing clock settings disables clock.

### ISSUE THREAD

**Issue by mygfya** [linuxmint/linuxmint#86]
On Linux Mint 19 Xfce I perform the following:

1) Right click on the current time.
2) Select 'Properties'
3) Adjust the time settings to my liking.
4) Click close.

After step #4 the clock disappears from where it is pinned. There is a small sliver of the time widget there. Right clicking on it reveals the configuration dialog again. If I change the settings then the time will reappear. Closing the dialog, however, will continue to clear out the settings every time.

**Comment by 69Rixter** [comment]
I'm also having this issue. Only difference(if it means anything) is that I'm running "live".

_**Rick**_

**Comment by xenopeek** [comment]
This isn't reproducible on Linux Mint 19.3 Xfce so I'm closing it as it appears fixed.

1. Right-click clock on the panel > Properties
2. Set Timezone to something other (start typing name of a continent to get suggestions), changed Layout, Tooltip format and toggled all options
3. After closing the clock remains on the panel

Tried several times in various combinations, issue doesn't occur.
