### ISSUE TITLE
ntp (&ntpdate) vs timesyncd

### ISSUE THREAD

**Issue by alicektx** [linuxmint/linuxmint#89]
...thought i should brought this to attention here, as per forums' thread:
https://forums.linuxmint.com/viewtopic.php?f=47&t=283566

At least xenopeek seems to have recommended a full switch to timesyncd back in August 2016:
https://forums.linuxmint.com/viewtopic.php?p=1206454#p1206454

So maybe ntp / ntpdate should not be included by default in the future?
Or at least the ntp.service to not be enabled to avoid possible confusion?

**Comment by ckristi** [comment]
I believe this is already the case, as of 19.1, at least:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19.1 Tessa
Release:	19.1
Codename:	tessa

$ systemctl status systemd-timesyncd.service 
● systemd-timesyncd.service - Network Time Synchronization
   Loaded: loaded (/lib/systemd/system/systemd-timesyncd.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-01-12 18:54:02 CET; 4 days ago

$ dpkg -l | grep ntp ; echo ${PIPESTATUS[1]}
1

```
