### ISSUE TITLE
Hibernation not working on Linux Mint 19 series

### ISSUE THREAD

**Issue by basilky** [linuxmint/linuxmint#92]
Hibernation using swap file is not working under Linux Mint 19. I had been using Linux Mint 19 and upgraded to 19.1. Upgraded kernel from 4.15 to 4.18. Hibernation is not working in any cases. My laptop screen goes blank on resume after hibernate.

System details: [https://termbin.com/nqpw](https://termbin.com/nqpw)

I have already asked the same in the forum: [https://forums.linuxmint.com/viewtopic.php?f=46&t=283930](https://forums.linuxmint.com/viewtopic.php?f=46&t=283930)

**Comment by gm10** [comment]
Last I checked, hibernation wasn't even officially supported in LM19.x.

Maybe my guide gives you a pointer about something you have missed: https://forums.linuxmint.com/viewtopic.php?f=42&t=284100&p=1569661#p1569661 but otherwise it's some driver/firmware/BIOS/UEFI incompatibility. It's often possible to work around that but not always easy to diagnose. Good luck.

**Comment by basilky** [comment]
I have already gone through your guide and many other. I have reported a detailed issue on the forum also.
[https://forums.linuxmint.com/viewtopic.php?f=46&t=283930](url)
Sadly, this is caused by a regression in recent kernel versions and there is already an active bug report on launchpad.

[https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1743094](url)

It's more than a year now since the the bug was reported and no fix till now. Please report on the above launchpad bug if somebody also experience this bug.

**Comment by gm10** [comment]
> It's more than a year now since the the bug was reported and no fix till now. 
Ubuntu doesn't officially support hibernation, either, so they'll most likely not bother with that report.

Maybe this will help: https://forums.linuxmint.com/viewtopic.php?t=258577

**Comment by basilky** [comment]
> Maybe this will help: https://forums.linuxmint.com/viewtopic.php?t=258577

I have tried it, but the grub config make my touchpad not working.
