### ISSUE TITLE
Package mint-meta-xfce should have xfce4-terminal as a dependency

### ISSUE THREAD

**Issue by dashohoxha** [linuxmint/linuxmint#95]
xfce4-terminal is required for the Xfce desktop, but it is not a dependency of mint-meta-xfce which is supposed to install this desktop.

**Comment by xenopeek** [comment]
Thanks for the suggestion. For more information about our suggestions workflow see the [FAQ](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html).
