### ISSUE TITLE
Include all three desktops on a single iso

### ISSUE THREAD

**Issue by dashohoxha** [linuxmint/linuxmint#96]
After installing LinuxMint MATE, I also install the packages `mint-meta-xfce` and `mint-meta-cinnamon` (and also `mint-meta-codecs`), so that I have all the three desktops. I can select on login which desktop to use. This does not increase the size of the installation too much.

So, I wonder why not install all three of them by default? This would also reduce the number of distributed ISO-s from 6 to 2, and would make it easier for people to try all the desktops.

**Comment by xenopeek** [comment]
Thanks for contributing to Linux Mint. Your suggestion was reviewed. See [here](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html#why-are-ideas-and-feature-requests-closed) for our workflow on feature requests.
