### ISSUE TITLE
Install font Monaco

### ISSUE THREAD

**Issue by dashohoxha** [linuxmint/linuxmint#97]
I like Monaco as the default font for the terminal. Why not make a package for installing it by default?
https://forums.linuxmint.com/viewtopic.php?f=19&t=278440

**Comment by ijash** [comment]
nice. i would like this included for future updates. upvote

**Comment by smurphos** [comment]
Although various sites offer it without license it's actually a commercially licensed font, so couldn't be offered by Mint without Mint paying for the privilege.

**Comment by dashohoxha** [comment]
> it's actually a commercially licensed font, so couldn't be offered by Mint without Mint paying for the privilege

If it is so than maybe this request should be closed. Maybe I should not use it either.
