### ISSUE TITLE
community.linuxmint.com SSL certificate expired

### ISSUE THREAD

**Issue by iSWORD** [linuxmint/linuxmint#99]
Hi, I don't know where to report this but the SSL certificate for community.linuxmint.com is expired.

Fortunately I can add an exception and use the website just fine since HKPK is not enabled.

**Comment by iSWORD** [comment]
@ijash That's very odd since they seem to have renewed it. http://prntscr.com/m57kuj

**Comment by ijash** [comment]
> @ijash That's very odd since they seem to have renewed it. http://prntscr.com/m57kuj

deleted my comments
